package cpp

import (
	"fmt"
	"io"
	"strings"

	"github.com/bholten/tools/idlc-go/internal/sema"
)

func emitHeader(w io.Writer, m *sema.Model, reg *sema.Registry) {
	emitHeaderPrelude(w, m, reg)

	// Root classes lay out everything-but-POD in one namespace block;
	// non-root classes split stub from impl/adapter/helper into a
	// second block. Both layouts then put POD in its own final block.
	emitNamespaceOpen(w, m.Package)
	emitStubHeader(w, m)

	if m.Class.IsRoot() {
		emitImplHeader(w, m)
		emitAdapterHeader(w, m)
		emitHelperHeader(w, m)
		emitMockHeader(w, m)
	}

	emitNamespaceClose(w, m.Package)
	emitUsingNamespace(w, m.Package)

	if !m.Class.IsRoot() {
		emitNamespaceOpen(w, m.Package)
		emitImplHeader(w, m)
		emitAdapterHeader(w, m)
		emitHelperHeader(w, m)
		emitMockHeader(w, m)
		emitNamespaceClose(w, m.Package)
		emitUsingNamespace(w, m.Package)
	}

	emitNamespaceOpen(w, m.Package)
	emitPODHeader(w, m)
	emitNamespaceClose(w, m.Package)
	emitUsingNamespace(w, m.Package)

	// JAR quirk: the ifndef token uses _H_ but the trailing comment
	// references *POD*_H_. Reproduce verbatim.
	fmt.Fprintf(w, "#endif /*%sPOD_H_*/\n", strings.ToUpper(m.Class.Name))
}

func emitHeaderPrelude(w io.Writer, m *sema.Model, reg *sema.Registry) {
	fmt.Fprintf(w, "/*\n")
	fmt.Fprintf(w, " *\t%s/%s.h generated by engine3 IDL compiler 0.70\n", m.HeaderPrefix(), pathlessIDL(m))
	fmt.Fprintf(w, " */\n\n")

	guard := guardName(m.Class.Name)

	fmt.Fprintf(w, "#ifndef %s\n", guard)
	fmt.Fprintf(w, "#define %s\n\n", guard)

	fmt.Fprintf(w, "#include \"engine/core/Core.h\"\n\n")
	fmt.Fprintf(w, "#include \"engine/core/ManagedReference.h\"\n\n")
	fmt.Fprintf(w, "#include \"engine/core/ManagedWeakReference.h\"\n\n")
	fmt.Fprintf(w, "#include \"system/util/Optional.h\"\n\n")

	// likely / unlikely macro block — emitted verbatim.
	io.WriteString(w, "#ifndef likely\n")
	io.WriteString(w, "#ifdef __GNUC__\n")
	io.WriteString(w, "#define likely(x)       __builtin_expect(!!(x), 1)\n")
	io.WriteString(w, "#define unlikely(x)     __builtin_expect(!!(x), 0)\n")
	io.WriteString(w, "#else\n")
	io.WriteString(w, "#define likely(x)       (x)\n")
	io.WriteString(w, "#define unlikely(x)     (x)\n")
	io.WriteString(w, "#endif\n")
	io.WriteString(w, "#endif\n")

	fmt.Fprintf(w, "#include \"engine/util/json_utils.h\"\n\n")

	// JAR layout: forward-decl IDL imports first (so any IDL-class
	// reference in method signatures resolves), then `gmock/gmock.h`
	// for `@mock` classes, then the `include` directives, then non-IDL
	// imports (parent class + utility headers).
	//
	// Classes whose parent is registered as non-managed (e.g.
	// `engine.util.Observable`) skip the forward-decl section entirely
	// — every IDL import is treated as a regular `#include`.
	parent := m.Class.Base
	allIncludes := reg.IsNonManagedParent(parent)
	thisClass := m.Class.Name

	for _, imp := range m.Imports {
		if !allIncludes && importIsForwardDecl(imp, thisClass, parent, reg) {
			emitImportForwardDecl(w, imp, reg)
		}
	}

	if m.Class.IsMock {
		fmt.Fprintf(w, "#include \"gmock/gmock.h\"\n\n")
	}

	for _, inc := range m.Includes {
		fmt.Fprintf(w, "#include \"%s\"\n\n", importToInclude(inc))
	}

	for _, imp := range m.Imports {
		if allIncludes || !importIsForwardDecl(imp, thisClass, parent, reg) {
			fmt.Fprintf(w, "#include \"%s\"\n\n", importToInclude(imp))
		}
	}
}

// emitMockHeader writes a `class Mock<Class> : public <Class>` shell
// for `@mock` classes. The body — the MOCK_METHODn lines for each
// inherited virtual method — is taken verbatim from m.MockBody. The
// JAR derives this list by walking the entire IDL inheritance chain;
// the Go reimplementation can't reproduce that without whole-corpus
// access, so tests inject the expected body explicitly. No-op when
// the class isn't `@mock`.
func emitMockHeader(w io.Writer, m *sema.Model) {
	if !m.Class.IsMock {
		return
	}

	fmt.Fprintf(w, "class Mock%s : public %s {\n", m.Class.Name, m.Class.Name)
	fmt.Fprintf(w, "public:\n")
	fmt.Fprintf(w, "\n")

	if m.MockBody != "" {
		fmt.Fprint(w, m.MockBody)
	}

	fmt.Fprintf(w, "};\n\n")
}

// importIsForwardDecl reports whether the given import qname should be
// emitted as a forward-decl block (IDL class) rather than a direct
// `#include`. The decision is simpler than it looks:
//
//   - non-IDL imports (engine3 utility headers like Vector, Logger):
//     always `#include` (we don't generate a forward-decl block for
//     types we have no IDL for).
//   - immediate parent: always `#include` (the parent's full type is
//     needed for the inheritance declaration).
//   - engine3 IDL classes (`engine.*`, `system.*`): always `#include`.
//     The JAR treats engine3 IDL classes the same as utility headers
//     for inclusion purposes — empirically verified against
//     ParentFields/LairObserver/etc.
//   - everything else (project IDL classes that aren't the immediate
//     parent): forward-decl.
func importIsForwardDecl(qname, thisClass, parent string, reg *sema.Registry) bool {
	if reg == nil {
		return false
	}

	if !reg.IsIDLClass(qname) {
		return false
	}

	if parent != "" && strings.HasSuffix(qname, "."+parent) {
		return false
	}

	if isEngine3Qname(qname) {
		return false
	}

	_ = thisClass
	return true
}

// isEngine3Qname reports whether the given import qname resolves to an
// engine3 IDL class — `engine.*` (Observable, ManagedObject, ...) or
// `system.*` (String, Time, Lockable, ...). The JAR treats these
// uniformly with `#include` even when they're transitively reachable
// through the parent's header, presumably because engine3 itself
// always provides the full headers.
func isEngine3Qname(qname string) bool {
	return strings.HasPrefix(qname, "engine.") || strings.HasPrefix(qname, "system.")
}

// emitImportForwardDecl writes the JAR's namespace + class-decl block
// for one IDL-class import:
//
//	namespace pkg { namespace sub {
//
//	class Foo;
//
//	class FooPOD;       (omitted when the registry marks the class no-POD)
//
//	} } // namespace
//
//	using namespace pkg::sub;
func emitImportForwardDecl(w io.Writer, qname string, reg *sema.Registry) {
	parts := strings.Split(qname, ".")

	if len(parts) < 2 {
		return
	}

	className := parts[len(parts)-1]
	pkg := parts[:len(parts)-1]

	for _, p := range pkg {
		fmt.Fprintf(w, "namespace %s {\n", p)
	}

	fmt.Fprintln(w)
	fmt.Fprintf(w, "class %s;\n\n", className)

	if reg == nil || !reg.IsNoPOD(qname) {
		fmt.Fprintf(w, "class %sPOD;\n\n", className)
	}

	for i := len(pkg) - 1; i >= 0; i-- {
		fmt.Fprintf(w, "} // namespace %s\n", pkg[i])
	}

	fmt.Fprintln(w)
	fmt.Fprintf(w, "using namespace ")

	for i, p := range pkg {
		if i > 0 {
			fmt.Fprintf(w, "::")
		}
		fmt.Fprintf(w, "%s", p)
	}

	fmt.Fprintf(w, ";\n\n")
}

// pathlessIDL returns "server/chat/ChatMessage" — the path-portion of
// the generated file-header comment (without `.h` / `.cpp` suffix).
//
// Derived from `m.HeaderPath`, NOT from `m.Package`, because Core3 has
// IDLs whose `package` declaration disagrees with their file location
// (e.g. `server/zone/managers/ZoneManager.idl` declares `package
// server.zone.manager` — singular). The JAR uses the file location
// for output paths and file-header comments, and the package only for
// the C++ namespace block. The CLI sets `HeaderPath` from the input
// path; tests / corpus that don't override it get the
// package-derived default from `sema.Resolve`.
func pathlessIDL(m *sema.Model) string {
	return strings.TrimSuffix(m.HeaderPath, ".h")
}

func emitNamespaceOpen(w io.Writer, pkg []string) {
	if len(pkg) == 0 {
		return
	}
	for _, p := range pkg {
		fmt.Fprintf(w, "namespace %s {\n", p)
	}

	fmt.Fprintln(w)
}

func emitNamespaceClose(w io.Writer, pkg []string) {
	if len(pkg) == 0 {
		return
	}
	for i := len(pkg) - 1; i >= 0; i-- {
		fmt.Fprintf(w, "} // namespace %s\n", pkg[i])
	}

	fmt.Fprintln(w)
}

func emitUsingNamespace(w io.Writer, pkg []string) {
	if len(pkg) == 0 {
		return
	}
	fmt.Fprintf(w, "using namespace ")

	for i, p := range pkg {
		if i > 0 {
			fmt.Fprintf(w, "::")
		}
		fmt.Fprintf(w, "%s", p)
	}

	fmt.Fprintf(w, ";\n\n")
}
