package cpp

import (
	"fmt"
	"io"

	"github.com/bholten/tools/idlc-go/internal/sema"
)

func emitSource(w io.Writer, m *sema.Model, reg *sema.Registry) {
	emitSourcePrelude(w, m, reg)
	emitStubSource(w, m)
	emitImplSource(w, m)
	emitAdapterSource(w, m)
	emitHelperSource(w, m)
	emitPODSource(w, m)
}

func emitSourcePrelude(w io.Writer, m *sema.Model, reg *sema.Registry) {
	fmt.Fprintf(w, "/*\n")
	fmt.Fprintf(w, " *\t%s/%s.cpp generated by engine3 IDL compiler 0.70\n", m.HeaderPrefix(), pathlessIDL(m))
	fmt.Fprintf(w, " */\n\n")
	fmt.Fprintf(w, "#include \"%s.h\"\n\n", m.Class.Name)
	// IDL-class imports were forward-declared in the header; the .cpp
	// needs the real `#include` so method bodies can see the full type.
	// Classes whose parent is non-managed (TreeEntry/LambdaObserver)
	// already pulled in everything as `#include` in the header — no
	// extra .cpp includes needed.
	if reg.IsNonManagedParent(m.Class.Base) {
		return
	}

	for _, imp := range m.Imports {
		if importIsForwardDecl(imp, m.Class.Name, m.Class.Base, reg) {
			fmt.Fprintf(w, "#include \"%s\"\n\n", importToInclude(imp))
		}
	}
}
