package hash

import "testing"

// Oracles extracted from testdata/autogen/. Each value appears as a
// "0x... //ClassName.fieldName" comment in the JAR-generated C++.
// If any of these regress, the on-disk BerkeleyDB schema breaks.
func TestNameHashCorpusFields(t *testing.T) {
	cases := map[string]uint32{
		// testdata/autogen/server/chat/ChatMessage.cpp
		"ChatMessage.message": 0xbd8f57ac,

		// testdata/autogen/server/chat/PendingMessageList.cpp
		"PendingMessageList.pendingMessages": 0x779b47a8,

		// testdata/autogen/server/chat/PersistentMessage.cpp
		"PersistentMessage.senderName":         0xa6c6ceb5,
		"PersistentMessage.subject":            0xe9fbfb82,
		"PersistentMessage.body":               0xcdb90e9b,
		"PersistentMessage.timeStamp":          0x848d409d,
		"PersistentMessage.status":             0xa74721f1,
		"PersistentMessage.receiverObjectID":   0xc0fc200f,
		"PersistentMessage.stringIdParameters": 0x1b2466ec,
		"PersistentMessage.waypointParameters": 0xcc670081,

		// docs/idl-toolchain-feasibility.md (verified by the design doc)
		"ChatManager.systemRoom": 0x783bbc2f,
	}
	runOracleCases(t, cases)
}

// Oracles freshly generated by running ref/idlc.jar against a probe IDL
// designed to exercise edge-case identifiers the engine3 corpus doesn't.
// Regenerate via scripts/gen-oracle.sh.
func TestNameHashProbeFields(t *testing.T) {
	cases := map[string]uint32{
		"Probe.a":                                     0xa04f1ce7,
		"Probe.A":                                     0x386caa07,
		"Probe.aB":                                    0x32c0ba5c,
		"Probe.ab_cd":                                 0x46e25503,
		"Probe.field1":                                0x25b47b7c,
		"Probe.very_long_field_name_with_underscores": 0x2f7e5f64,
		"Probe.CamelCase":                             0x9243a6d2,
		"Probe.snake_case":                            0x50aab8c3,
		"Probe.mixedCase123":                          0xac6485b4,
		"Probe.someBool":                              0x7943bb71,
	}
	runOracleCases(t, cases)
}

func runOracleCases(t *testing.T, cases map[string]uint32) {
	t.Helper()
	for input, want := range cases {
		t.Run(input, func(t *testing.T) {
			got := NameHash(input)
			if got != want {
				t.Fatalf("NameHash(%q) = %#08x, want %#08x", input, got, want)
			}
		})
	}
}

// CRC-32/BZIP2 of the empty string with init 0xFFFFFFFF and final XOR
// 0xFFFFFFFF is 0x00000000 — the init and the final XOR cancel. Useful
// guard against regressing the init/final-XOR constants.
func TestNameHashEmpty(t *testing.T) {
	if got := NameHash(""); got != 0 {
		t.Fatalf("NameHash(\"\") = %#08x, want 0x00000000", got)
	}
}

// "123456789" is the standard CRC test vector; the BZIP2 variant should
// produce 0xFC891918. Independent of the engine3 corpus — confirms the
// algorithm itself is correct, not just that it agrees with the JAR.
func TestNameHashStandardVector(t *testing.T) {
	const want = 0xFC891918
	if got := NameHash("123456789"); got != want {
		t.Fatalf("NameHash(\"123456789\") = %#08x, want %#08x", got, want)
	}
}

func BenchmarkNameHash(b *testing.B) {
	const s = "ChatMessage.message"
	b.SetBytes(int64(len(s)))
	for i := 0; i < b.N; i++ {
		_ = NameHash(s)
	}
}
