# idlc-go — friendly entry points for build, test, and corpus management.
#
# The Core3 corpus and idlc.jar are not redistributable, so they live
# outside the repo. Clone SWGEmu/Core3 (recursively, for the engine3
# submodule) to ./submodules/Core3 to use the default path, or set
# CORE3_PATH to point anywhere else. `make fetch-corpus` copies the
# IDLs + JAR autogen into testdata/ for the corpus tests; tests that
# need those auto-skip when missing (`internal/corpus` package).
#
# Override the Core3 location: `make CORE3_PATH=/abs/path test-corpus`.

CORE3_PATH ?= submodules/Core3
JAR        := $(CORE3_PATH)/MMOCoreORB/utils/engine3/MMOEngine/lib/idlc.jar
ENGINE3_SRC := $(CORE3_PATH)/MMOCoreORB/utils/engine3/MMOEngine/src

.PHONY: help build test test-corpus test-probes test-all \
        fmt vet fetch-corpus regen-probes regen-oracle \
        ensure-core3 clean-got \
        baseline-jar baseline-idlc-go baseline-diff baseline \
        compile-engine3 compile-engine3-diff

help:
	@echo "idlc-go — common targets"
	@echo ""
	@echo "  make build           Build the idlc-go binary"
	@echo "  make test            Run all tests (corpus tests skip if Core3 absent)"
	@echo "  make test-probes     Run only the probe tests"
	@echo "  make test-corpus     Run only the corpus tests (requires Core3)"
	@echo "  make test-all        Run everything; fail if Core3 isn't present"
	@echo "  make fmt             gofmt -w on the tree"
	@echo "  make vet             go vet ./..."
	@echo ""
	@echo "Corpus management (requires Core3 at \$$CORE3_PATH or ./submodules/Core3):"
	@echo "  make fetch-corpus    Copy IDLs + run JAR → testdata/idl/ + testdata/autogen/"
	@echo "  make regen-probes    Re-run JAR over testdata/probe/src/ → expected/"
	@echo "  make regen-oracle    Re-run JAR over scripts/oracle/src/ → hash test oracle"
	@echo ""
	@echo "Full-corpus baseline (requires Core3):"
	@echo "  make baseline-jar      Run JAR over every Core3 IDL → _baseline/jar/"
	@echo "  make baseline-idlc-go  Run idlc-go over every Core3 IDL → _baseline/idlc-go/"
	@echo "  make baseline          Both of the above"
	@echo "  make baseline-diff     Diff _baseline/jar vs _baseline/idlc-go, report"
	@echo "  make test-parity       Regenerate both baselines, then assert per-method"
	@echo "                         lock/dispatch parity with the JAR over the full corpus"
	@echo ""
	@echo "engine3 directory-walk (requires Core3):"
	@echo "  make compile-engine3      Run idlc-go in dir-walk mode against engine3"
	@echo "                            → _build/engine3/ (autogen alongside source)"
	@echo "  make compile-engine3-diff Diff that output against JAR's checked-in autogen"
	@echo ""
	@echo "Misc:"
	@echo "  make clean-got       Remove stale *.got files dropped by failed tests"
	@echo ""
	@echo "Override Core3 location: make CORE3_PATH=/abs/path <target>"

build:
	go build ./...

fmt:
	gofmt -w .

vet:
	go vet ./...

test:
	go test ./...

test-probes:
	go test ./internal/probe/...

test-corpus: ensure-core3
	go test ./internal/golden/... ./internal/parser/... ./internal/sema/...

test-parity: baseline
	go test ./internal/golden/ -run TestCorpusLockDispatchParity -v

test-all: ensure-core3 test

ensure-core3:
	@test -f "$(JAR)" || { \
		echo "Core3 not present (looked for $(JAR))."; \
		echo "Clone SWGEmu/Core3 (with --recursive for engine3) to ./submodules/Core3,"; \
		echo "or set CORE3_PATH=/abs/path/to/your/Core3 checkout."; \
		exit 1; \
	}
	@test -d "$(ENGINE3_SRC)" || { \
		echo "engine3 not present (looked for $(ENGINE3_SRC))."; \
		echo "Make sure your Core3 checkout was cloned recursively"; \
		echo "(\`git clone --recursive\`), so the engine3 submodule is initialised."; \
		exit 1; \
	}

fetch-corpus: ensure-core3
	CORE3_PATH=$(CORE3_PATH) bash scripts/fetch-corpus-from-core3.sh

regen-probes: ensure-core3
	CORE3_PATH=$(CORE3_PATH) bash scripts/gen-probe-goldens.sh

regen-oracle: ensure-core3
	CORE3_PATH=$(CORE3_PATH) bash scripts/gen-oracle.sh

clean-got:
	find testdata -name '*.got' -delete

baseline-jar: ensure-core3
	CORE3_PATH=$(CORE3_PATH) bash scripts/baseline-jar.sh

baseline-idlc-go: ensure-core3
	CORE3_PATH=$(CORE3_PATH) bash scripts/baseline-idlc-go.sh

baseline: baseline-jar baseline-idlc-go

baseline-diff:
	bash scripts/baseline-diff.sh

# compile-engine3: exercise the engine3 directory-walk invocation
# (`idlc-go -sd <src> anyadEclipse`) end-to-end. Copies engine3 src to
# _build/engine3/, strips JAR-generated autogen, then runs idlc-go in
# dir-walk mode so it regenerates everything alongside the .idl files.
ENGINE3_OUT := _build/engine3

compile-engine3: ensure-core3
	@rm -rf $(ENGINE3_OUT)
	@mkdir -p $(ENGINE3_OUT)
	@cp -r $(ENGINE3_SRC)/. $(ENGINE3_OUT)/
	@find $(ENGINE3_OUT) \( -name "*.h" -o -name "*.cpp" \) -print0 | xargs -0 -r -I{} \
	  bash -c 'head -1 "{}" 2>/dev/null | grep -q "generated by engine3 IDL compiler" && rm -f "{}"; true'
	@go run ./cmd/idlc -sd $(ENGINE3_OUT) anyadEclipse

compile-engine3-diff: compile-engine3
	@echo "diffing $(ENGINE3_OUT) vs JAR autogen at $(ENGINE3_SRC)"
	@diff -r $(ENGINE3_OUT) $(ENGINE3_SRC) | grep -E "^(diff |Only in)" | head -40 || true
