// Package sema lowers a parsed IDL AST into the emit-ready Model. It
// owns IDL → C++ type mapping, RPC name mangling, field-hash attachment,
// and annotation flag extraction.
package sema

import "github.com/bholten/idlc-go/internal/parser"

// Model is everything the emitter needs to produce one .h / .cpp pair.
type Model struct {
	Package    []string // ["server", "chat"]
	Imports    []string // qualified, e.g. "engine.core.ManagedObject"
	Includes   []string // qualified, e.g. "system.thread.ReadWriteLock"
	HeaderPath string   // "server/chat/ChatMessage.h"
	SourcePath string   // "server/chat/ChatMessage.cpp"
	OutputBase string   // "ChatMessage"
	IDLPath    string   // "server/chat/ChatMessage.idl" — used in body comments
	Class      Class

	// Registry of IDL-defined classes used to choose between
	// `ManagedReference<T*>`, `Reference<T*>`, and bare `T*` in field
	// and method-signature rendering. May be nil — code that consults
	// it must accept that case (treating every external type as
	// non-IDL).
	Registry *Registry

	// MockBody is an optional fixture string used when the class is
	// `@mock`-annotated. The JAR generates `MOCK_METHODn(name, sig);`
	// lines for each virtual method inherited from the parent chain;
	// reproducing that requires whole-corpus access. Tests pass the
	// expected body verbatim instead. Empty when not provided — the
	// emitter then writes an empty `class Mock<Class>` shell.
	MockBody string

	// OutdirPrefix is the path prefix used in the file-header comment
	// (`<prefix>/<pkg>/Foo.h generated by …`). The JAR embeds the
	// `-outdir` flag value here verbatim; we mirror that. Defaults to
	// "autogen" — matches Core3's `IDL_DIRECTIVES = -outdir autogen`
	// and keeps the corpus tests stable.
	OutdirPrefix string

	// NoOutdirPrefix, when set, suppresses the prefix entirely in the
	// file-header comment (`<pkg>/Foo.h generated by …`). Used by the
	// engine3 invocation style — `idlc.jar -sd src anyadEclipse` with
	// no `-outdir` writes outputs alongside the .idl files and uses
	// just the package path in the header. Distinct from `OutdirPrefix
	// == ""` because empty string still defaults to "autogen" for
	// backward compatibility with golden tests.
	NoOutdirPrefix bool
}

// HeaderPrefix returns the path prefix to use in the generated file
// header comment. Defaults to "autogen" when OutdirPrefix is empty
// (matches Core3's `-outdir autogen`); returns "" when
// NoOutdirPrefix is set (matches engine3's no-outdir invocation).
func (m *Model) HeaderPrefix() string {
	if m.NoOutdirPrefix {
		return ""
	}

	if m.OutdirPrefix == "" {
		return "autogen"
	}

	return m.OutdirPrefix
}

type Class struct {
	Name     string
	Doc      string // raw `/** ... */` text from the IDL preceding the class declaration, "" if none.
	Base     string // "" when the class has no IDL `extends` (root class)
	ImplName string
	Adapter  string
	Helper   string
	POD      string

	HasJSON    bool
	IsMock     bool     // @mock annotation — emit gmock.h include + Mock<Class> subclass.
	IsLua      bool     // @lua annotation — emit Luna-bridge wrapper class `Lua<Class>` + .cpp impl.
	Implements []string // unqualified type names from IDL `implements` clause.

	Fields  []Field
	Methods []Method
	Ctors   []Ctor

	// DereferencedFieldNames lists field names that carry @dereferenced
	// — used by emit to rewrite body references (`field.x` → `(&field)->x`).
	DereferencedFieldNames []string
}

// IsRoot reports whether this class has no IDL `extends` clause.
// Root classes (e.g. ManagedObject) get the runtime types as their
// C++ bases (DistributedObjectStub/Servant/Adapter/POD) and skip the
// `<Base>X::method` parent calls in serialization paths.
func (c Class) IsRoot() bool { return c.Base == "" }

// StubBase returns the C++ base class for the stub.
func (c Class) StubBase() string {
	if c.IsRoot() {
		return "DistributedObjectStub"
	}

	return c.Base
}

// ImplBase returns the C++ base class for the implementation.
func (c Class) ImplBase() string {
	if c.IsRoot() {
		return "DistributedObjectServant"
	}

	return c.Base + "Implementation"
}

// AdapterBase returns the C++ base class for the adapter.
func (c Class) AdapterBase() string {
	if c.IsRoot() {
		return "DistributedObjectAdapter"
	}

	return c.Base + "Adapter"
}

// PODBase returns the C++ base class for the POD.
func (c Class) PODBase() string {
	if c.IsRoot() {
		return "DistributedObjectPOD"
	}

	return c.Base + "POD"
}

type Field struct {
	Name      string
	IDLType   parser.Type
	HashInput string // "ChatMessage.message"
	Hash      uint32
	Vis       parser.Visibility

	Transient    bool
	Static       bool // `static` modifier — impl-class field decl renders as `static T x;` (out-of-line definition lives in hand-written .cpp).
	Final        bool // `final` modifier — non-managed class fields render as `Reference<const T*>` (read-only after construction).
	Dereferenced bool
	WeakRef      bool
	RawTemplate  string // @rawTemplate(value="...") inner — pasted into Type<inner > (no trailing `*`).

	// IsConst is set when the IDL declared `public static final <prim> X = N;`.
	// These are emitted as `static const T X = N;` in the stub + impl public
	// sections, never as regular fields, and are excluded from POD/serialization.
	IsConst bool
	Default string // raw RHS expression text, only meaningful when IsConst.
}

type Param struct {
	Name         string
	IDLType      parser.Type
	Final        bool
	Default      string // raw expression text, "" if none
	Dereferenced bool   // @dereferenced annotation on the parameter
	RawTemplate  string // @rawTemplate(value="...") inner — pasted into Type<inner* >.
}

type Method struct {
	Name       string
	Return     parser.Type
	Params     []Param
	Visibility parser.Visibility
	Doc        string // raw `/** ... */` text, "" if none

	// Annotation flags. Only the ones the emitter actually consults
	// are listed individually; others are added as we extend the corpus.
	IsRead                        bool
	IsLocal                       bool
	IsDirty                       bool
	IsPreLocked                   bool
	IsArg1PreLocked               bool
	IsArg2PreLocked               bool
	IsNativeStub                  bool
	IsVirtualStub                 bool
	IsNoImplementationDeclaration bool
	IsReference                   bool   // @reference — wraps return as Reference<T*>.
	IsWeakReference               bool   // @weakReference — wraps return as ManagedWeakReference<T*>.
	IsDereferenced                bool   // @dereferenced — return is by-value (no trailing `*`).
	IsMock                        bool   // @mock on a method — adds `virtual ` to the impl-class header decl so the gmock subclass can override.
	RawTemplate                   string // @rawTemplate(value="...") on a method — return type pastes inner: `Head<inner >*`.

	// Source modifiers.
	IsNative     bool
	IsAbstract   bool
	Synchronized bool
	IsFinal      bool // `final` modifier — return type renders as `const T` in C++.

	Body *parser.Body

	RPCName string  // RPC_SETSTRING__STRING_
	RPCSeed *uint32 // explicit enum value, if known via legacy CSV
}

func (m Method) IsVoid() bool { return m.Return.Name == "void" }

type Ctor struct {
	Name   string
	Params []Param
	Body   *parser.Body
}
