/*
 *	autogen/probe/Body.h generated by engine3 IDL compiler 0.70
 */

#ifndef BODY_H_
#define BODY_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "system/lang/System.h"

#include "engine/core/ManagedObject.h"

namespace probe {

class Body : public ManagedObject {
public:
	void nullRewrite();

	void thisRewrite();

	void classFieldArrow();

	void derefFieldArrow();

	void derefFieldBare();

	void importedClassCall();

	int ifWithSpaceAlreadyHasSpace(int x);

	int ifNoSpace(int x);

	void synchronizedBlock();

	void commentsInBody();

	void stringLiteralPreserved();

	void multipleRewritesPerLine();

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	Body(DummyConstructorParameter* param);

	virtual ~Body();

	friend class BodyHelper;
};

} // namespace probe

using namespace probe;

namespace probe {

class BodyImplementation : public ManagedObjectImplementation {
	ManagedReference<ManagedObject > derefField;

	ManagedReference<ManagedObject* > classField;

	String strField;

public:
	BodyImplementation();
	BodyImplementation(DummyConstructorParameter* param);

	void nullRewrite();

	void thisRewrite();

	void classFieldArrow();

	void derefFieldArrow();

	void derefFieldBare();

	void importedClassCall();

	int ifWithSpaceAlreadyHasSpace(int x);

	int ifNoSpace(int x);

	void synchronizedBlock();

	void commentsInBody();

	void stringLiteralPreserved();

	void multipleRewritesPerLine();

	WeakReference<Body*> _this;

	operator const Body*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~BodyImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class Body;
};

class BodyAdapter : public ManagedObjectAdapter {
public:
	BodyAdapter(Body* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

};

class BodyHelper : public DistributedObjectClassHelper, public Singleton<BodyHelper> {
	static BodyHelper* staticInitializer;

public:
	BodyHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<BodyHelper>;
};

} // namespace probe

using namespace probe;

namespace probe {

class BodyPOD : public ManagedObjectPOD {
public:
	Optional<ManagedReference<ManagedObject >> derefField;

	Optional<ManagedReference<ManagedObjectPOD* >> classField;

	Optional<String> strField;

	String _className;
	BodyPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~BodyPOD();

};

} // namespace probe

using namespace probe;

#endif /*BODYPOD_H_*/
