/*
 *	autogen/probe/Body.cpp generated by engine3 IDL compiler 0.70
 */

#include "Body.h"

/*
 *	BodyStub
 */

Body::Body(DummyConstructorParameter* param) : ManagedObject(param) {
	_setClassName("Body");
}

Body::~Body() {
}



void Body::nullRewrite() {
	BodyImplementation* _implementation = static_cast<BodyImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->nullRewrite();
	}
}

void Body::thisRewrite() {
	BodyImplementation* _implementation = static_cast<BodyImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->thisRewrite();
	}
}

void Body::classFieldArrow() {
	BodyImplementation* _implementation = static_cast<BodyImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->classFieldArrow();
	}
}

void Body::derefFieldArrow() {
	BodyImplementation* _implementation = static_cast<BodyImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->derefFieldArrow();
	}
}

void Body::derefFieldBare() {
	BodyImplementation* _implementation = static_cast<BodyImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->derefFieldBare();
	}
}

void Body::importedClassCall() {
	BodyImplementation* _implementation = static_cast<BodyImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->importedClassCall();
	}
}

int Body::ifWithSpaceAlreadyHasSpace(int x) {
	BodyImplementation* _implementation = static_cast<BodyImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		return _implementation->ifWithSpaceAlreadyHasSpace(x);
	}
}

int Body::ifNoSpace(int x) {
	BodyImplementation* _implementation = static_cast<BodyImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		return _implementation->ifNoSpace(x);
	}
}

void Body::synchronizedBlock() {
	BodyImplementation* _implementation = static_cast<BodyImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->synchronizedBlock();
	}
}

void Body::commentsInBody() {
	BodyImplementation* _implementation = static_cast<BodyImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->commentsInBody();
	}
}

void Body::stringLiteralPreserved() {
	BodyImplementation* _implementation = static_cast<BodyImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->stringLiteralPreserved();
	}
}

void Body::multipleRewritesPerLine() {
	BodyImplementation* _implementation = static_cast<BodyImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->multipleRewritesPerLine();
	}
}

DistributedObjectServant* Body::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* Body::_getImplementationForRead() const {
	return _impl;
}

void Body::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	BodyImplementation
 */

BodyImplementation::BodyImplementation() : ManagedObjectImplementation() {
	_initializeImplementation();
}

BodyImplementation::BodyImplementation(DummyConstructorParameter* param) : ManagedObjectImplementation(param) {
	_initializeImplementation();
}


BodyImplementation::~BodyImplementation() {
}


void BodyImplementation::finalize() {
}

void BodyImplementation::_initializeImplementation() {
	_setClassHelper(BodyHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void BodyImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<Body*>(stub);
	ManagedObjectImplementation::_setStub(stub);
}

DistributedObjectStub* BodyImplementation::_getStub() {
	return _this.get();
}

BodyImplementation::operator const Body*() {
	return _this.get();
}

void BodyImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void BodyImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void BodyImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void BodyImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void BodyImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void BodyImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void BodyImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void BodyImplementation::_serializationHelperMethod() {
	ManagedObjectImplementation::_serializationHelperMethod();

	_setClassName("Body");

}

void BodyImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(BodyImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool BodyImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0xcee3ff48: //Body.derefField
		TypeInfo<ManagedReference<ManagedObject > >::parseFromBinaryStream(&derefField, stream);
		return true;

	case 0xfda2bbd0: //Body.classField
		TypeInfo<ManagedReference<ManagedObject* > >::parseFromBinaryStream(&classField, stream);
		return true;

	case 0x6aa90bba: //Body.strField
		TypeInfo<String >::parseFromBinaryStream(&strField, stream);
		return true;

	}

	return false;
}

void BodyImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = BodyImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int BodyImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0xcee3ff48; //Body.derefField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedReference<ManagedObject > >::toBinaryStream(&derefField, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xfda2bbd0; //Body.classField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedReference<ManagedObject* > >::toBinaryStream(&classField, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x6aa90bba; //Body.strField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&strField, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

void BodyImplementation::nullRewrite() {
	// probe/Body.idl():  		classField = null;
	classField = NULL;
	// probe/Body.idl():  		strField = null;
	strField = NULL;
}

void BodyImplementation::thisRewrite() {
	// probe/Body.idl():  		classField.lock(this);
	classField->lock(_this.getReferenceUnsafeStaticCast());
	// probe/Body.idl():  		strField = "passing this and null";
	strField = "passing this and null";
}

void BodyImplementation::classFieldArrow() {
	// probe/Body.idl():  		classField.updateForWrite();
	classField->updateForWrite();
	// probe/Body.idl():  		classField.lock();
	classField->lock();
}

void BodyImplementation::derefFieldArrow() {
	// probe/Body.idl():  		derefField.updateForWrite();
	(&derefField)->updateForWrite();
	// probe/Body.idl():  		derefField.lock();
	(&derefField)->lock();
}

void BodyImplementation::derefFieldBare() {
	// probe/Body.idl():  		classField = derefField;
	classField = (&derefField);
}

void BodyImplementation::importedClassCall() {
	// probe/Body.idl():  		System.getTime();
	System::getTime();
}

int BodyImplementation::ifWithSpaceAlreadyHasSpace(int x) {
	// probe/Body.idl():  			return 0;
	if (x > 0)	// probe/Body.idl():  			return 1;
	return 1;

	else 	// probe/Body.idl():  			return 0;
	return 0;
}

int BodyImplementation::ifNoSpace(int x) {
	// probe/Body.idl():  			return 0;
	if (x > 0)	// probe/Body.idl():  			return 1;
	return 1;

	else 	// probe/Body.idl():  			return 0;
	return 0;
}

void BodyImplementation::synchronizedBlock() {
	// probe/Body.idl():  		}
{
	Locker _locker(classField);
	// probe/Body.idl():  			classField.updateForWrite();
	classField->updateForWrite();
}
}

void BodyImplementation::commentsInBody() {
	// probe/Body.idl():  		classField.updateForWrite();
	classField->updateForWrite();
}

void BodyImplementation::stringLiteralPreserved() {
	// probe/Body.idl():  		strField = "null this System.getTime classField.x";
	strField = "null this System.getTime classField.x";
}

void BodyImplementation::multipleRewritesPerLine() {
	// probe/Body.idl():  		classField.lock(this);
	classField->lock(_this.getReferenceUnsafeStaticCast());
	// probe/Body.idl():  		classField = null;
	classField = NULL;
}

/*
 *	BodyAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


BodyAdapter::BodyAdapter(Body* obj) : ManagedObjectAdapter(obj) {
}

void BodyAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	default:
		ManagedObjectAdapter::invokeMethod(methid, inv);
	}
}

/*
 *	BodyHelper
 */

BodyHelper* BodyHelper::staticInitializer = BodyHelper::instance();

BodyHelper::BodyHelper() {
	className = "Body";

	Core::getObjectBroker()->registerClass(className, this);
}

void BodyHelper::finalizeHelper() {
	BodyHelper::finalize();
}

DistributedObject* BodyHelper::instantiateObject() {
	return new Body(DummyConstructorParameter::instance());
}

DistributedObjectServant* BodyHelper::instantiateServant() {
	return new BodyImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* BodyHelper::instantiatePOD() {
	return new BodyPOD();
}

DistributedObjectAdapter* BodyHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new BodyAdapter(static_cast<Body*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	BodyPOD
 */

BodyPOD::~BodyPOD() {
}

BodyPOD::BodyPOD(void) {
	_className = "Body";
}


void BodyPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = BodyPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int BodyPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (derefField) {
	_nameHashCode = 0xcee3ff48; //Body.derefField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedReference<ManagedObject > >::toBinaryStream(&derefField.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (classField) {
	_nameHashCode = 0xfda2bbd0; //Body.classField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedReference<ManagedObjectPOD* > >::toBinaryStream(&classField.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (strField) {
	_nameHashCode = 0x6aa90bba; //Body.strField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&strField.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool BodyPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0xcee3ff48: //Body.derefField
		{
			ManagedReference<ManagedObject > _mnderefField;
			TypeInfo<ManagedReference<ManagedObject > >::parseFromBinaryStream(&_mnderefField, stream);
			derefField = std::move(_mnderefField);
		}
		return true;

	case 0xfda2bbd0: //Body.classField
		{
			ManagedReference<ManagedObjectPOD* > _mnclassField;
			TypeInfo<ManagedReference<ManagedObjectPOD* > >::parseFromBinaryStream(&_mnclassField, stream);
			classField = std::move(_mnclassField);
		}
		return true;

	case 0x6aa90bba: //Body.strField
		{
			String _mnstrField;
			TypeInfo<String >::parseFromBinaryStream(&_mnstrField, stream);
			strField = std::move(_mnstrField);
		}
		return true;

	}

	return false;
}

void BodyPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(BodyPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void BodyPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ManagedObjectPOD::writeObjectCompact(stream);

	TypeInfo<ManagedReference<ManagedObject > >::toBinaryStream(&derefField.value(), stream);

	TypeInfo<ManagedReference<ManagedObjectPOD* > >::toBinaryStream(&classField.value(), stream);

	TypeInfo<String >::toBinaryStream(&strField.value(), stream);


}

