/*
 *	autogen/probe/Cast.cpp generated by engine3 IDL compiler 0.70
 */

#include "Cast.h"

/*
 *	CastStub
 */

Cast::Cast(DummyConstructorParameter* param) : ManagedObject(param) {
	_setClassName("Cast");
}

Cast::~Cast() {
}



void Cast::castInAssignment(ManagedObject* obj) {
	CastImplementation* _implementation = static_cast<CastImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->castInAssignment(obj);
	}
}

void Cast::castAsArg(ManagedObject* obj) {
	CastImplementation* _implementation = static_cast<CastImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->castAsArg(obj);
	}
}

void Cast::castInComparison(ManagedObject* obj, ManagedObject* other) {
	CastImplementation* _implementation = static_cast<CastImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->castInComparison(obj, other);
	}
}

void Cast::castNoSpace(ManagedObject* obj) {
	CastImplementation* _implementation = static_cast<CastImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->castNoSpace(obj);
	}
}

DistributedObjectServant* Cast::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* Cast::_getImplementationForRead() const {
	return _impl;
}

void Cast::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	CastImplementation
 */

CastImplementation::CastImplementation() : ManagedObjectImplementation() {
	_initializeImplementation();
}

CastImplementation::CastImplementation(DummyConstructorParameter* param) : ManagedObjectImplementation(param) {
	_initializeImplementation();
}


CastImplementation::~CastImplementation() {
}


void CastImplementation::finalize() {
}

void CastImplementation::_initializeImplementation() {
	_setClassHelper(CastHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void CastImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<Cast*>(stub);
	ManagedObjectImplementation::_setStub(stub);
}

DistributedObjectStub* CastImplementation::_getStub() {
	return _this.get();
}

CastImplementation::operator const Cast*() {
	return _this.get();
}

void CastImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void CastImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void CastImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void CastImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void CastImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void CastImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void CastImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void CastImplementation::_serializationHelperMethod() {
	ManagedObjectImplementation::_serializationHelperMethod();

	_setClassName("Cast");

}

void CastImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(CastImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool CastImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x81ce82f4: //Cast.classField
		TypeInfo<ManagedReference<ManagedObject* > >::parseFromBinaryStream(&classField, stream);
		return true;

	}

	return false;
}

void CastImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = CastImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int CastImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0x81ce82f4; //Cast.classField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedReference<ManagedObject* > >::toBinaryStream(&classField, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

void CastImplementation::castInAssignment(ManagedObject* obj) {
	// probe/Cast.idl():  		ManagedObject target = (ManagedObject) obj;
	ManagedReference<ManagedObject* > target = dynamic_cast<ManagedObject*>(obj);
	// probe/Cast.idl():  		target.updateForWrite();
	target->updateForWrite();
}

void CastImplementation::castAsArg(ManagedObject* obj) {
	// probe/Cast.idl():  		classField.lock((ManagedObject) obj);
	classField->lock(dynamic_cast<ManagedObject*>(obj));
}

void CastImplementation::castInComparison(ManagedObject* obj, ManagedObject* other) {
	// probe/Cast.idl():  	}
	if (dynamic_cast<ManagedObject*>(obj) == other)	// probe/Cast.idl():  			obj.lock();
	obj->lock();
}

void CastImplementation::castNoSpace(ManagedObject* obj) {
	// probe/Cast.idl():  		classField.lock((ManagedObject)obj);
	classField->lock(dynamic_cast<ManagedObject*>(obj));
}

/*
 *	CastAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


CastAdapter::CastAdapter(Cast* obj) : ManagedObjectAdapter(obj) {
}

void CastAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	default:
		ManagedObjectAdapter::invokeMethod(methid, inv);
	}
}

/*
 *	CastHelper
 */

CastHelper* CastHelper::staticInitializer = CastHelper::instance();

CastHelper::CastHelper() {
	className = "Cast";

	Core::getObjectBroker()->registerClass(className, this);
}

void CastHelper::finalizeHelper() {
	CastHelper::finalize();
}

DistributedObject* CastHelper::instantiateObject() {
	return new Cast(DummyConstructorParameter::instance());
}

DistributedObjectServant* CastHelper::instantiateServant() {
	return new CastImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* CastHelper::instantiatePOD() {
	return new CastPOD();
}

DistributedObjectAdapter* CastHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new CastAdapter(static_cast<Cast*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	CastPOD
 */

CastPOD::~CastPOD() {
}

CastPOD::CastPOD(void) {
	_className = "Cast";
}


void CastPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = CastPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int CastPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (classField) {
	_nameHashCode = 0x81ce82f4; //Cast.classField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedReference<ManagedObjectPOD* > >::toBinaryStream(&classField.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool CastPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x81ce82f4: //Cast.classField
		{
			ManagedReference<ManagedObjectPOD* > _mnclassField;
			TypeInfo<ManagedReference<ManagedObjectPOD* > >::parseFromBinaryStream(&_mnclassField, stream);
			classField = std::move(_mnclassField);
		}
		return true;

	}

	return false;
}

void CastPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(CastPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void CastPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ManagedObjectPOD::writeObjectCompact(stream);

	TypeInfo<ManagedReference<ManagedObjectPOD* > >::toBinaryStream(&classField.value(), stream);


}

