/*
 *	autogen/probe/Cast.h generated by engine3 IDL compiler 0.70
 */

#ifndef CAST_H_
#define CAST_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "engine/core/ManagedObject.h"

namespace probe {

class Cast : public ManagedObject {
public:
	void castInAssignment(ManagedObject* obj);

	void castAsArg(ManagedObject* obj);

	void castInComparison(ManagedObject* obj, ManagedObject* other);

	void castNoSpace(ManagedObject* obj);

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	Cast(DummyConstructorParameter* param);

	virtual ~Cast();

	friend class CastHelper;
};

} // namespace probe

using namespace probe;

namespace probe {

class CastImplementation : public ManagedObjectImplementation {
	ManagedReference<ManagedObject* > classField;

public:
	CastImplementation();
	CastImplementation(DummyConstructorParameter* param);

	void castInAssignment(ManagedObject* obj);

	void castAsArg(ManagedObject* obj);

	void castInComparison(ManagedObject* obj, ManagedObject* other);

	void castNoSpace(ManagedObject* obj);

	WeakReference<Cast*> _this;

	operator const Cast*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~CastImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class Cast;
};

class CastAdapter : public ManagedObjectAdapter {
public:
	CastAdapter(Cast* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

};

class CastHelper : public DistributedObjectClassHelper, public Singleton<CastHelper> {
	static CastHelper* staticInitializer;

public:
	CastHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<CastHelper>;
};

} // namespace probe

using namespace probe;

namespace probe {

class CastPOD : public ManagedObjectPOD {
public:
	Optional<ManagedReference<ManagedObjectPOD* >> classField;

	String _className;
	CastPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~CastPOD();

};

} // namespace probe

using namespace probe;

#endif /*CASTPOD_H_*/
