/*
 *	autogen/probe/ChainedCall.cpp generated by engine3 IDL compiler 0.70
 */

#include "ChainedCall.h"

/*
 *	ChainedCallStub
 */

ChainedCall::ChainedCall(DummyConstructorParameter* param) : ManagedObject(param) {
	_setClassName("ChainedCall");
}

ChainedCall::~ChainedCall() {
}



ChainedCall* ChainedCall::getSelf() {
	ChainedCallImplementation* _implementation = static_cast<ChainedCallImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		return _implementation->getSelf();
	}
}

void ChainedCall::chainOnField() {
	ChainedCallImplementation* _implementation = static_cast<ChainedCallImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->chainOnField();
	}
}

void ChainedCall::chainOnThis() {
	ChainedCallImplementation* _implementation = static_cast<ChainedCallImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->chainOnThis();
	}
}

void ChainedCall::deepChain() {
	ChainedCallImplementation* _implementation = static_cast<ChainedCallImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->deepChain();
	}
}

void ChainedCall::chainPreservedInString() {
	ChainedCallImplementation* _implementation = static_cast<ChainedCallImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->chainPreservedInString();
	}
}

DistributedObjectServant* ChainedCall::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* ChainedCall::_getImplementationForRead() const {
	return _impl;
}

void ChainedCall::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	ChainedCallImplementation
 */

ChainedCallImplementation::ChainedCallImplementation() : ManagedObjectImplementation() {
	_initializeImplementation();
}

ChainedCallImplementation::ChainedCallImplementation(DummyConstructorParameter* param) : ManagedObjectImplementation(param) {
	_initializeImplementation();
}


ChainedCallImplementation::~ChainedCallImplementation() {
}


void ChainedCallImplementation::finalize() {
}

void ChainedCallImplementation::_initializeImplementation() {
	_setClassHelper(ChainedCallHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void ChainedCallImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<ChainedCall*>(stub);
	ManagedObjectImplementation::_setStub(stub);
}

DistributedObjectStub* ChainedCallImplementation::_getStub() {
	return _this.get();
}

ChainedCallImplementation::operator const ChainedCall*() {
	return _this.get();
}

void ChainedCallImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void ChainedCallImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void ChainedCallImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void ChainedCallImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void ChainedCallImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void ChainedCallImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void ChainedCallImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void ChainedCallImplementation::_serializationHelperMethod() {
	ManagedObjectImplementation::_serializationHelperMethod();

	_setClassName("ChainedCall");

}

void ChainedCallImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ChainedCallImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool ChainedCallImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x64b427e2: //ChainedCall.classField
		TypeInfo<ManagedReference<ChainedCall* > >::parseFromBinaryStream(&classField, stream);
		return true;

	}

	return false;
}

void ChainedCallImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ChainedCallImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ChainedCallImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0x64b427e2; //ChainedCall.classField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedReference<ChainedCall* > >::toBinaryStream(&classField, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

void ChainedCallImplementation::chainOnField() {
	// probe/ChainedCall.idl():  		classField.getSelf().updateForWrite();
	classField->getSelf()->updateForWrite();
}

void ChainedCallImplementation::chainOnThis() {
	// probe/ChainedCall.idl():  		this.getSelf().updateForWrite();
	_this.getReferenceUnsafeStaticCast()->getSelf()->updateForWrite();
}

void ChainedCallImplementation::deepChain() {
	// probe/ChainedCall.idl():  		classField.getSelf().getSelf().getSelf().updateForWrite();
	classField->getSelf()->getSelf()->getSelf()->updateForWrite();
}

void ChainedCallImplementation::chainPreservedInString() {
	// probe/ChainedCall.idl():  		classField.setLockName(").a) ).bar() literal");
	classField->setLockName(").a) ).bar() literal");
}

/*
 *	ChainedCallAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


ChainedCallAdapter::ChainedCallAdapter(ChainedCall* obj) : ManagedObjectAdapter(obj) {
}

void ChainedCallAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	default:
		ManagedObjectAdapter::invokeMethod(methid, inv);
	}
}

/*
 *	ChainedCallHelper
 */

ChainedCallHelper* ChainedCallHelper::staticInitializer = ChainedCallHelper::instance();

ChainedCallHelper::ChainedCallHelper() {
	className = "ChainedCall";

	Core::getObjectBroker()->registerClass(className, this);
}

void ChainedCallHelper::finalizeHelper() {
	ChainedCallHelper::finalize();
}

DistributedObject* ChainedCallHelper::instantiateObject() {
	return new ChainedCall(DummyConstructorParameter::instance());
}

DistributedObjectServant* ChainedCallHelper::instantiateServant() {
	return new ChainedCallImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* ChainedCallHelper::instantiatePOD() {
	return new ChainedCallPOD();
}

DistributedObjectAdapter* ChainedCallHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new ChainedCallAdapter(static_cast<ChainedCall*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	ChainedCallPOD
 */

ChainedCallPOD::~ChainedCallPOD() {
}

ChainedCallPOD::ChainedCallPOD(void) {
	_className = "ChainedCall";
}


void ChainedCallPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ChainedCallPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ChainedCallPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (classField) {
	_nameHashCode = 0x64b427e2; //ChainedCall.classField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedReference<ChainedCallPOD* > >::toBinaryStream(&classField.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool ChainedCallPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x64b427e2: //ChainedCall.classField
		{
			ManagedReference<ChainedCallPOD* > _mnclassField;
			TypeInfo<ManagedReference<ChainedCallPOD* > >::parseFromBinaryStream(&_mnclassField, stream);
			classField = std::move(_mnclassField);
		}
		return true;

	}

	return false;
}

void ChainedCallPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ChainedCallPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void ChainedCallPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ManagedObjectPOD::writeObjectCompact(stream);

	TypeInfo<ManagedReference<ChainedCallPOD* > >::toBinaryStream(&classField.value(), stream);


}

