/*
 *	autogen/probe/ChainedCall.h generated by engine3 IDL compiler 0.70
 */

#ifndef CHAINEDCALL_H_
#define CHAINEDCALL_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "engine/core/ManagedObject.h"

namespace probe {

class ChainedCall : public ManagedObject {
public:
	ChainedCall* getSelf();

	void chainOnField();

	void chainOnThis();

	void deepChain();

	void chainPreservedInString();

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	ChainedCall(DummyConstructorParameter* param);

	virtual ~ChainedCall();

	friend class ChainedCallHelper;
};

} // namespace probe

using namespace probe;

namespace probe {

class ChainedCallImplementation : public ManagedObjectImplementation {
	ManagedReference<ChainedCall* > classField;

public:
	ChainedCallImplementation();
	ChainedCallImplementation(DummyConstructorParameter* param);

	ChainedCall* getSelf();

	void chainOnField();

	void chainOnThis();

	void deepChain();

	void chainPreservedInString();

	WeakReference<ChainedCall*> _this;

	operator const ChainedCall*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~ChainedCallImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class ChainedCall;
};

class ChainedCallAdapter : public ManagedObjectAdapter {
public:
	ChainedCallAdapter(ChainedCall* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

};

class ChainedCallHelper : public DistributedObjectClassHelper, public Singleton<ChainedCallHelper> {
	static ChainedCallHelper* staticInitializer;

public:
	ChainedCallHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<ChainedCallHelper>;
};

} // namespace probe

using namespace probe;

namespace probe {

class ChainedCallPOD : public ManagedObjectPOD {
public:
	Optional<ManagedReference<ChainedCallPOD* >> classField;

	String _className;
	ChainedCallPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~ChainedCallPOD();

};

} // namespace probe

using namespace probe;

#endif /*CHAINEDCALLPOD_H_*/
