/*
 *	autogen/probe/ClassDoc.cpp generated by engine3 IDL compiler 0.70
 */

#include "ClassDoc.h"

/*
 *	ClassDocStub
 */

ClassDoc::ClassDoc(DummyConstructorParameter* param) : ManagedObject(param) {
	_setClassName("ClassDoc");
}

ClassDoc::~ClassDoc() {
}



void ClassDoc::noop() {
	ClassDocImplementation* _implementation = static_cast<ClassDocImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->noop();
	}
}

DistributedObjectServant* ClassDoc::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* ClassDoc::_getImplementationForRead() const {
	return _impl;
}

void ClassDoc::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	ClassDocImplementation
 */

ClassDocImplementation::ClassDocImplementation() : ManagedObjectImplementation() {
	_initializeImplementation();
}

ClassDocImplementation::ClassDocImplementation(DummyConstructorParameter* param) : ManagedObjectImplementation(param) {
	_initializeImplementation();
}


ClassDocImplementation::~ClassDocImplementation() {
}


void ClassDocImplementation::finalize() {
}

void ClassDocImplementation::_initializeImplementation() {
	_setClassHelper(ClassDocHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void ClassDocImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<ClassDoc*>(stub);
	ManagedObjectImplementation::_setStub(stub);
}

DistributedObjectStub* ClassDocImplementation::_getStub() {
	return _this.get();
}

ClassDocImplementation::operator const ClassDoc*() {
	return _this.get();
}

void ClassDocImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void ClassDocImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void ClassDocImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void ClassDocImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void ClassDocImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void ClassDocImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void ClassDocImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void ClassDocImplementation::_serializationHelperMethod() {
	ManagedObjectImplementation::_serializationHelperMethod();

	_setClassName("ClassDoc");

}

void ClassDocImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ClassDocImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool ClassDocImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void ClassDocImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ClassDocImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ClassDocImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

void ClassDocImplementation::noop() {
}

/*
 *	ClassDocAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


ClassDocAdapter::ClassDocAdapter(ClassDoc* obj) : ManagedObjectAdapter(obj) {
}

void ClassDocAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	default:
		ManagedObjectAdapter::invokeMethod(methid, inv);
	}
}

/*
 *	ClassDocHelper
 */

ClassDocHelper* ClassDocHelper::staticInitializer = ClassDocHelper::instance();

ClassDocHelper::ClassDocHelper() {
	className = "ClassDoc";

	Core::getObjectBroker()->registerClass(className, this);
}

void ClassDocHelper::finalizeHelper() {
	ClassDocHelper::finalize();
}

DistributedObject* ClassDocHelper::instantiateObject() {
	return new ClassDoc(DummyConstructorParameter::instance());
}

DistributedObjectServant* ClassDocHelper::instantiateServant() {
	return new ClassDocImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* ClassDocHelper::instantiatePOD() {
	return new ClassDocPOD();
}

DistributedObjectAdapter* ClassDocHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new ClassDocAdapter(static_cast<ClassDoc*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	ClassDocPOD
 */

ClassDocPOD::~ClassDocPOD() {
}

ClassDocPOD::ClassDocPOD(void) {
	_className = "ClassDoc";
}


void ClassDocPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ClassDocPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ClassDocPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

bool ClassDocPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void ClassDocPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ClassDocPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void ClassDocPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ManagedObjectPOD::writeObjectCompact(stream);


}

