/*
 *	autogen/probe/ClassDoc.h generated by engine3 IDL compiler 0.70
 */

#ifndef CLASSDOC_H_
#define CLASSDOC_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "engine/core/ManagedObject.h"

namespace probe {

	/**
 * Probe for class-level doc-comment emission.
 *
 * The JAR transcribes a doc-comment block that immediately precedes
 * a `class` declaration into the C++ output. The block goes before
 * the class declaration in the .h, and the JAR emits it once per
 * generated C++ class (stub, impl, etc.).
 *
 * Multi-line content with inline asterisks is preserved verbatim;
 * the JAR doesn't re-flow the text.
 */
class ClassDoc : public ManagedObject {
public:
	void noop();

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	ClassDoc(DummyConstructorParameter* param);

	virtual ~ClassDoc();

	friend class ClassDocHelper;
};

} // namespace probe

using namespace probe;

namespace probe {

class ClassDocImplementation : public ManagedObjectImplementation {

public:
	ClassDocImplementation();
	ClassDocImplementation(DummyConstructorParameter* param);

	void noop();

	WeakReference<ClassDoc*> _this;

	operator const ClassDoc*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~ClassDocImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class ClassDoc;
};

class ClassDocAdapter : public ManagedObjectAdapter {
public:
	ClassDocAdapter(ClassDoc* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

};

class ClassDocHelper : public DistributedObjectClassHelper, public Singleton<ClassDocHelper> {
	static ClassDocHelper* staticInitializer;

public:
	ClassDocHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<ClassDocHelper>;
};

} // namespace probe

using namespace probe;

namespace probe {

	/**
 * Probe for class-level doc-comment emission.
 *
 * The JAR transcribes a doc-comment block that immediately precedes
 * a `class` declaration into the C++ output. The block goes before
 * the class declaration in the .h, and the JAR emits it once per
 * generated C++ class (stub, impl, etc.).
 *
 * Multi-line content with inline asterisks is preserved verbatim;
 * the JAR doesn't re-flow the text.
 */
class ClassDocPOD : public ManagedObjectPOD {
public:

	ClassDocPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~ClassDocPOD();

};

} // namespace probe

using namespace probe;

#endif /*CLASSDOCPOD_H_*/
