/*
 *	autogen/probe/Constants.h generated by engine3 IDL compiler 0.70
 */

#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "engine/core/ManagedObject.h"

namespace probe {

class Constants : public ManagedObject {
public:
	static const int CONST_INT = 5;

	static const int CONST_INT_HEX = 0xFF;

	static const int CONST_INT_NEG = -1;

	static const int CONST_INT_ZERO = 0;

	unsigned static const int CONST_UINT;

	unsigned static const int CONST_UINT_HEX;

	static const long long CONST_LONG;

	static const long long CONST_LONG_HEX;

	unsigned static const long long CONST_ULONG;

	static const short CONST_SHORT = 7;

	unsigned static const short CONST_USHORT;

	static const byte CONST_BYTE;

	static const byte CONST_BYTE_HEX;

	static const bool CONST_BOOL_TRUE;

	static const bool CONST_BOOL_FALSE;

	static const float CONST_FLOAT;

	static const float CONST_FLOAT_NEG;

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	Constants(DummyConstructorParameter* param);

	virtual ~Constants();

	friend class ConstantsHelper;
};

} // namespace probe

using namespace probe;

namespace probe {

class ConstantsImplementation : public ManagedObjectImplementation {
public:
	static const int CONST_INT = 5;

	static const int CONST_INT_HEX = 0xFF;

	static const int CONST_INT_NEG = -1;

	static const int CONST_INT_ZERO = 0;

	unsigned static const int CONST_UINT;

	unsigned static const int CONST_UINT_HEX;

	static const long long CONST_LONG;

	static const long long CONST_LONG_HEX;

	unsigned static const long long CONST_ULONG;

	static const short CONST_SHORT = 7;

	unsigned static const short CONST_USHORT;

	static const byte CONST_BYTE;

	static const byte CONST_BYTE_HEX;

	static const bool CONST_BOOL_TRUE;

	static const bool CONST_BOOL_FALSE;

	static const float CONST_FLOAT;

	static const float CONST_FLOAT_NEG;

	ConstantsImplementation();
	ConstantsImplementation(DummyConstructorParameter* param);

	WeakReference<Constants*> _this;

	operator const Constants*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~ConstantsImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class Constants;
};

class ConstantsAdapter : public ManagedObjectAdapter {
public:
	ConstantsAdapter(Constants* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

};

class ConstantsHelper : public DistributedObjectClassHelper, public Singleton<ConstantsHelper> {
	static ConstantsHelper* staticInitializer;

public:
	ConstantsHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<ConstantsHelper>;
};

} // namespace probe

using namespace probe;

namespace probe {

class ConstantsPOD : public ManagedObjectPOD {
public:
	String _className;
	ConstantsPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~ConstantsPOD();

};

} // namespace probe

using namespace probe;

#endif /*CONSTANTSPOD_H_*/
