/*
 *	autogen/probe/Constants.cpp generated by engine3 IDL compiler 0.70
 */

#include "Constants.h"

/*
 *	ConstantsStub
 */

unsigned const int Constants::CONST_UINT = 100;

unsigned const int Constants::CONST_UINT_HEX = 0xFFFFFFFF;

const long long Constants::CONST_LONG = 12345;

const long long Constants::CONST_LONG_HEX = 0xFF;

unsigned const long long Constants::CONST_ULONG = 999;

unsigned const short Constants::CONST_USHORT = 8;

const byte Constants::CONST_BYTE = 1;

const byte Constants::CONST_BYTE_HEX = 0xFF;

const bool Constants::CONST_BOOL_TRUE = true;

const bool Constants::CONST_BOOL_FALSE = false;

const float Constants::CONST_FLOAT = 3.14;

const float Constants::CONST_FLOAT_NEG = -1.5;

Constants::Constants(DummyConstructorParameter* param) : ManagedObject(param) {
	_setClassName("Constants");
}

Constants::~Constants() {
}



DistributedObjectServant* Constants::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* Constants::_getImplementationForRead() const {
	return _impl;
}

void Constants::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	ConstantsImplementation
 */

unsigned const int ConstantsImplementation::CONST_UINT = 100;

unsigned const int ConstantsImplementation::CONST_UINT_HEX = 0xFFFFFFFF;

const long long ConstantsImplementation::CONST_LONG = 12345;

const long long ConstantsImplementation::CONST_LONG_HEX = 0xFF;

unsigned const long long ConstantsImplementation::CONST_ULONG = 999;

unsigned const short ConstantsImplementation::CONST_USHORT = 8;

const byte ConstantsImplementation::CONST_BYTE = 1;

const byte ConstantsImplementation::CONST_BYTE_HEX = 0xFF;

const bool ConstantsImplementation::CONST_BOOL_TRUE = true;

const bool ConstantsImplementation::CONST_BOOL_FALSE = false;

const float ConstantsImplementation::CONST_FLOAT = 3.14;

const float ConstantsImplementation::CONST_FLOAT_NEG = -1.5;

ConstantsImplementation::ConstantsImplementation() : ManagedObjectImplementation() {
	_initializeImplementation();
}

ConstantsImplementation::ConstantsImplementation(DummyConstructorParameter* param) : ManagedObjectImplementation(param) {
	_initializeImplementation();
}


ConstantsImplementation::~ConstantsImplementation() {
}


void ConstantsImplementation::finalize() {
}

void ConstantsImplementation::_initializeImplementation() {
	_setClassHelper(ConstantsHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void ConstantsImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<Constants*>(stub);
	ManagedObjectImplementation::_setStub(stub);
}

DistributedObjectStub* ConstantsImplementation::_getStub() {
	return _this.get();
}

ConstantsImplementation::operator const Constants*() {
	return _this.get();
}

void ConstantsImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void ConstantsImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void ConstantsImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void ConstantsImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void ConstantsImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void ConstantsImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void ConstantsImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void ConstantsImplementation::_serializationHelperMethod() {
	ManagedObjectImplementation::_serializationHelperMethod();

	_setClassName("Constants");

}

void ConstantsImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ConstantsImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool ConstantsImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void ConstantsImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ConstantsImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ConstantsImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

/*
 *	ConstantsAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


ConstantsAdapter::ConstantsAdapter(Constants* obj) : ManagedObjectAdapter(obj) {
}

void ConstantsAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	default:
		ManagedObjectAdapter::invokeMethod(methid, inv);
	}
}

/*
 *	ConstantsHelper
 */

ConstantsHelper* ConstantsHelper::staticInitializer = ConstantsHelper::instance();

ConstantsHelper::ConstantsHelper() {
	className = "Constants";

	Core::getObjectBroker()->registerClass(className, this);
}

void ConstantsHelper::finalizeHelper() {
	ConstantsHelper::finalize();
}

DistributedObject* ConstantsHelper::instantiateObject() {
	return new Constants(DummyConstructorParameter::instance());
}

DistributedObjectServant* ConstantsHelper::instantiateServant() {
	return new ConstantsImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* ConstantsHelper::instantiatePOD() {
	return new ConstantsPOD();
}

DistributedObjectAdapter* ConstantsHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new ConstantsAdapter(static_cast<Constants*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	ConstantsPOD
 */

ConstantsPOD::~ConstantsPOD() {
}

ConstantsPOD::ConstantsPOD(void) {
	_className = "Constants";
}


void ConstantsPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ConstantsPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ConstantsPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

bool ConstantsPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void ConstantsPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ConstantsPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void ConstantsPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ManagedObjectPOD::writeObjectCompact(stream);


}

