/*
 *	autogen/probe/DerefManaged.h generated by engine3 IDL compiler 0.70
 */

#ifndef DEREFMANAGED_H_
#define DEREFMANAGED_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "engine/core/ManagedObject.h"

namespace probe {

class DerefManaged : public ManagedObject {
public:
	void methodAccess();

	void chainedAccess();

	void assignmentNull();

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	DerefManaged(DummyConstructorParameter* param);

	virtual ~DerefManaged();

	friend class DerefManagedHelper;
};

} // namespace probe

using namespace probe;

namespace probe {

class DerefManagedImplementation : public ManagedObjectImplementation {
	ManagedReference<ManagedObject > derefManagedField;

public:
	DerefManagedImplementation();
	DerefManagedImplementation(DummyConstructorParameter* param);

	void methodAccess();

	void chainedAccess();

	void assignmentNull();

	WeakReference<DerefManaged*> _this;

	operator const DerefManaged*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~DerefManagedImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class DerefManaged;
};

class DerefManagedAdapter : public ManagedObjectAdapter {
public:
	DerefManagedAdapter(DerefManaged* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

};

class DerefManagedHelper : public DistributedObjectClassHelper, public Singleton<DerefManagedHelper> {
	static DerefManagedHelper* staticInitializer;

public:
	DerefManagedHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<DerefManagedHelper>;
};

} // namespace probe

using namespace probe;

namespace probe {

class DerefManagedPOD : public ManagedObjectPOD {
public:
	Optional<ManagedReference<ManagedObject >> derefManagedField;

	String _className;
	DerefManagedPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~DerefManagedPOD();

};

} // namespace probe

using namespace probe;

#endif /*DEREFMANAGEDPOD_H_*/
