/*
 *	autogen/probe/DerefManaged.cpp generated by engine3 IDL compiler 0.70
 */

#include "DerefManaged.h"

/*
 *	DerefManagedStub
 */

DerefManaged::DerefManaged(DummyConstructorParameter* param) : ManagedObject(param) {
	_setClassName("DerefManaged");
}

DerefManaged::~DerefManaged() {
}



void DerefManaged::methodAccess() {
	DerefManagedImplementation* _implementation = static_cast<DerefManagedImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->methodAccess();
	}
}

void DerefManaged::chainedAccess() {
	DerefManagedImplementation* _implementation = static_cast<DerefManagedImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->chainedAccess();
	}
}

void DerefManaged::assignmentNull() {
	DerefManagedImplementation* _implementation = static_cast<DerefManagedImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->assignmentNull();
	}
}

DistributedObjectServant* DerefManaged::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* DerefManaged::_getImplementationForRead() const {
	return _impl;
}

void DerefManaged::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	DerefManagedImplementation
 */

DerefManagedImplementation::DerefManagedImplementation() : ManagedObjectImplementation() {
	_initializeImplementation();
}

DerefManagedImplementation::DerefManagedImplementation(DummyConstructorParameter* param) : ManagedObjectImplementation(param) {
	_initializeImplementation();
}


DerefManagedImplementation::~DerefManagedImplementation() {
}


void DerefManagedImplementation::finalize() {
}

void DerefManagedImplementation::_initializeImplementation() {
	_setClassHelper(DerefManagedHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void DerefManagedImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<DerefManaged*>(stub);
	ManagedObjectImplementation::_setStub(stub);
}

DistributedObjectStub* DerefManagedImplementation::_getStub() {
	return _this.get();
}

DerefManagedImplementation::operator const DerefManaged*() {
	return _this.get();
}

void DerefManagedImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void DerefManagedImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void DerefManagedImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void DerefManagedImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void DerefManagedImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void DerefManagedImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void DerefManagedImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void DerefManagedImplementation::_serializationHelperMethod() {
	ManagedObjectImplementation::_serializationHelperMethod();

	_setClassName("DerefManaged");

}

void DerefManagedImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(DerefManagedImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool DerefManagedImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0xb76a2dc6: //DerefManaged.derefManagedField
		TypeInfo<ManagedReference<ManagedObject > >::parseFromBinaryStream(&derefManagedField, stream);
		return true;

	}

	return false;
}

void DerefManagedImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = DerefManagedImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int DerefManagedImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0xb76a2dc6; //DerefManaged.derefManagedField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedReference<ManagedObject > >::toBinaryStream(&derefManagedField, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

void DerefManagedImplementation::methodAccess() {
	// probe/DerefManaged.idl():  		derefManagedField.updateForWrite();
	(&derefManagedField)->updateForWrite();
}

void DerefManagedImplementation::chainedAccess() {
	// probe/DerefManaged.idl():  		derefManagedField.lock();
	(&derefManagedField)->lock();
	// probe/DerefManaged.idl():  		derefManagedField.unlock();
	(&derefManagedField)->unlock();
}

void DerefManagedImplementation::assignmentNull() {
	// probe/DerefManaged.idl():  		derefManagedField = null;
	(&derefManagedField) = NULL;
}

/*
 *	DerefManagedAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


DerefManagedAdapter::DerefManagedAdapter(DerefManaged* obj) : ManagedObjectAdapter(obj) {
}

void DerefManagedAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	default:
		ManagedObjectAdapter::invokeMethod(methid, inv);
	}
}

/*
 *	DerefManagedHelper
 */

DerefManagedHelper* DerefManagedHelper::staticInitializer = DerefManagedHelper::instance();

DerefManagedHelper::DerefManagedHelper() {
	className = "DerefManaged";

	Core::getObjectBroker()->registerClass(className, this);
}

void DerefManagedHelper::finalizeHelper() {
	DerefManagedHelper::finalize();
}

DistributedObject* DerefManagedHelper::instantiateObject() {
	return new DerefManaged(DummyConstructorParameter::instance());
}

DistributedObjectServant* DerefManagedHelper::instantiateServant() {
	return new DerefManagedImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* DerefManagedHelper::instantiatePOD() {
	return new DerefManagedPOD();
}

DistributedObjectAdapter* DerefManagedHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new DerefManagedAdapter(static_cast<DerefManaged*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	DerefManagedPOD
 */

DerefManagedPOD::~DerefManagedPOD() {
}

DerefManagedPOD::DerefManagedPOD(void) {
	_className = "DerefManaged";
}


void DerefManagedPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = DerefManagedPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int DerefManagedPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (derefManagedField) {
	_nameHashCode = 0xb76a2dc6; //DerefManaged.derefManagedField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedReference<ManagedObject > >::toBinaryStream(&derefManagedField.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool DerefManagedPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0xb76a2dc6: //DerefManaged.derefManagedField
		{
			ManagedReference<ManagedObject > _mnderefManagedField;
			TypeInfo<ManagedReference<ManagedObject > >::parseFromBinaryStream(&_mnderefManagedField, stream);
			derefManagedField = std::move(_mnderefManagedField);
		}
		return true;

	}

	return false;
}

void DerefManagedPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(DerefManagedPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void DerefManagedPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ManagedObjectPOD::writeObjectCompact(stream);

	TypeInfo<ManagedReference<ManagedObject > >::toBinaryStream(&derefManagedField.value(), stream);


}

