/*
 *	autogen/probe/DirtyClass.h generated by engine3 IDL compiler 0.70
 */

#ifndef DIRTYCLASS_H_
#define DIRTYCLASS_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "engine/core/ManagedObject.h"

namespace probe {

class DirtyClass : public ManagedObject {
public:
	int preLockedInDirtyClass(int x);

	int ownDirtyPreLocked(int x);

	int readPreLockedInDirtyClass(int x) const;

	int plainInDirtyClass(int x);

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	DirtyClass(DummyConstructorParameter* param);

	virtual ~DirtyClass();

	friend class DirtyClassHelper;
};

} // namespace probe

using namespace probe;

namespace probe {

class DirtyClassImplementation : public ManagedObjectImplementation {

public:
	DirtyClassImplementation();
	DirtyClassImplementation(DummyConstructorParameter* param);

	int preLockedInDirtyClass(int x);

	int ownDirtyPreLocked(int x);

	int readPreLockedInDirtyClass(int x) const;

	int plainInDirtyClass(int x);

	WeakReference<DirtyClass*> _this;

	operator const DirtyClass*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~DirtyClassImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class DirtyClass;
};

class DirtyClassAdapter : public ManagedObjectAdapter {
public:
	DirtyClassAdapter(DirtyClass* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	int preLockedInDirtyClass(int x);

	int ownDirtyPreLocked(int x);

	int readPreLockedInDirtyClass(int x) const;

	int plainInDirtyClass(int x);

};

class DirtyClassHelper : public DistributedObjectClassHelper, public Singleton<DirtyClassHelper> {
	static DirtyClassHelper* staticInitializer;

public:
	DirtyClassHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<DirtyClassHelper>;
};

} // namespace probe

using namespace probe;

namespace probe {

class DirtyClassPOD : public ManagedObjectPOD {
public:

	DirtyClassPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~DirtyClassPOD();

};

} // namespace probe

using namespace probe;

#endif /*DIRTYCLASSPOD_H_*/
