/*
 *	autogen/probe/DirtyClass.cpp generated by engine3 IDL compiler 0.70
 */

#include "DirtyClass.h"

/*
 *	DirtyClassStub
 */

enum {RPC_PRELOCKEDINDIRTYCLASS__INT_ = 2177907704,RPC_OWNDIRTYPRELOCKED__INT_,RPC_READPRELOCKEDINDIRTYCLASS__INT_,RPC_PLAININDIRTYCLASS__INT_};

DirtyClass::DirtyClass(DummyConstructorParameter* param) : ManagedObject(param) {
	_setClassName("DirtyClass");
}

DirtyClass::~DirtyClass() {
}



int DirtyClass::preLockedInDirtyClass(int x) {
	DirtyClassImplementation* _implementation = static_cast<DirtyClassImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_PRELOCKEDINDIRTYCLASS__INT_);
		method.addSignedIntParameter(x);

		return method.executeWithSignedIntReturn();
	} else {
		assert(this->isLockedByCurrentThread());
		return _implementation->preLockedInDirtyClass(x);
	}
}

int DirtyClass::ownDirtyPreLocked(int x) {
	DirtyClassImplementation* _implementation = static_cast<DirtyClassImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_OWNDIRTYPRELOCKED__INT_);
		method.addSignedIntParameter(x);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->ownDirtyPreLocked(x);
	}
}

int DirtyClass::readPreLockedInDirtyClass(int x) const {
	DirtyClassImplementation* _implementation = static_cast<DirtyClassImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_READPRELOCKEDINDIRTYCLASS__INT_);
		method.addSignedIntParameter(x);

		return method.executeWithSignedIntReturn();
	} else {
		assert(this->isLockedByCurrentThread());
		return _implementation->readPreLockedInDirtyClass(x);
	}
}

int DirtyClass::plainInDirtyClass(int x) {
	DirtyClassImplementation* _implementation = static_cast<DirtyClassImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_PLAININDIRTYCLASS__INT_);
		method.addSignedIntParameter(x);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->plainInDirtyClass(x);
	}
}

DistributedObjectServant* DirtyClass::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* DirtyClass::_getImplementationForRead() const {
	return _impl;
}

void DirtyClass::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	DirtyClassImplementation
 */

DirtyClassImplementation::DirtyClassImplementation() : ManagedObjectImplementation() {
	_initializeImplementation();
}

DirtyClassImplementation::DirtyClassImplementation(DummyConstructorParameter* param) : ManagedObjectImplementation(param) {
	_initializeImplementation();
}


DirtyClassImplementation::~DirtyClassImplementation() {
}


void DirtyClassImplementation::finalize() {
}

void DirtyClassImplementation::_initializeImplementation() {
	_setClassHelper(DirtyClassHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void DirtyClassImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<DirtyClass*>(stub);
	ManagedObjectImplementation::_setStub(stub);
}

DistributedObjectStub* DirtyClassImplementation::_getStub() {
	return _this.get();
}

DirtyClassImplementation::operator const DirtyClass*() {
	return _this.get();
}

void DirtyClassImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void DirtyClassImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void DirtyClassImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void DirtyClassImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void DirtyClassImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void DirtyClassImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void DirtyClassImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void DirtyClassImplementation::_serializationHelperMethod() {
	ManagedObjectImplementation::_serializationHelperMethod();

	_setClassName("DirtyClass");

}

void DirtyClassImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(DirtyClassImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool DirtyClassImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void DirtyClassImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = DirtyClassImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int DirtyClassImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

/*
 *	DirtyClassAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


DirtyClassAdapter::DirtyClassAdapter(DirtyClass* obj) : ManagedObjectAdapter(obj) {
}

void DirtyClassAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_PRELOCKEDINDIRTYCLASS__INT_:
		{
			int x = inv->getSignedIntParameter();
			
			int _m_res = preLockedInDirtyClass(x);
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_OWNDIRTYPRELOCKED__INT_:
		{
			int x = inv->getSignedIntParameter();
			
			int _m_res = ownDirtyPreLocked(x);
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_READPRELOCKEDINDIRTYCLASS__INT_:
		{
			int x = inv->getSignedIntParameter();
			
			int _m_res = readPreLockedInDirtyClass(x);
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_PLAININDIRTYCLASS__INT_:
		{
			int x = inv->getSignedIntParameter();
			
			int _m_res = plainInDirtyClass(x);
			resp->insertSignedInt(_m_res);
		}
		break;
	default:
		ManagedObjectAdapter::invokeMethod(methid, inv);
	}
}

int DirtyClassAdapter::preLockedInDirtyClass(int x) {
	return (static_cast<DirtyClass*>(stub))->preLockedInDirtyClass(x);
}

int DirtyClassAdapter::ownDirtyPreLocked(int x) {
	return (static_cast<DirtyClass*>(stub))->ownDirtyPreLocked(x);
}

int DirtyClassAdapter::readPreLockedInDirtyClass(int x) const {
	return (static_cast<DirtyClass*>(stub))->readPreLockedInDirtyClass(x);
}

int DirtyClassAdapter::plainInDirtyClass(int x) {
	return (static_cast<DirtyClass*>(stub))->plainInDirtyClass(x);
}

/*
 *	DirtyClassHelper
 */

DirtyClassHelper* DirtyClassHelper::staticInitializer = DirtyClassHelper::instance();

DirtyClassHelper::DirtyClassHelper() {
	className = "DirtyClass";

	Core::getObjectBroker()->registerClass(className, this);
}

void DirtyClassHelper::finalizeHelper() {
	DirtyClassHelper::finalize();
}

DistributedObject* DirtyClassHelper::instantiateObject() {
	return new DirtyClass(DummyConstructorParameter::instance());
}

DistributedObjectServant* DirtyClassHelper::instantiateServant() {
	return new DirtyClassImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* DirtyClassHelper::instantiatePOD() {
	return new DirtyClassPOD();
}

DistributedObjectAdapter* DirtyClassHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new DirtyClassAdapter(static_cast<DirtyClass*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	DirtyClassPOD
 */

DirtyClassPOD::~DirtyClassPOD() {
}

DirtyClassPOD::DirtyClassPOD(void) {
	_className = "DirtyClass";
}


void DirtyClassPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = DirtyClassPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int DirtyClassPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

bool DirtyClassPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void DirtyClassPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(DirtyClassPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void DirtyClassPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ManagedObjectPOD::writeObjectCompact(stream);


}

