/*
 *	autogen/probe/Dispatch.h generated by engine3 IDL compiler 0.70
 */

#ifndef DISPATCH_H_
#define DISPATCH_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "engine/core/ManagedObject.h"

namespace probe {

class Dispatch : public ManagedObject {
public:
	void plainNative();

	void plainBody();

	void abstractWithBody();

	void abstractNative();

	void localNative();

	void localBody();

	void nativeStub();

	void nativeStubAbstract();

	virtual void virtualStub();

	virtual void virtualStubAbstract();

	void nativeStubLocal();

	virtual void virtualStubLocal();

	virtual void nativeAndVirtualStub();

	void noImplDecl();

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	Dispatch(DummyConstructorParameter* param);

	virtual ~Dispatch();

	void __nativeStub();

	void __nativeStubAbstract();

	void __nativeStubLocal();

	void __nativeAndVirtualStub();

	friend class DispatchHelper;
};

} // namespace probe

using namespace probe;

namespace probe {

class DispatchImplementation : public ManagedObjectImplementation {

public:
	DispatchImplementation();
	DispatchImplementation(DummyConstructorParameter* param);

	void plainNative();

	void plainBody();

	virtual void abstractWithBody();

	virtual void abstractNative();

	void localNative();

	void localBody();

	void nativeStub();

	virtual void nativeStubAbstract();

	virtual void virtualStub();

	virtual void virtualStubAbstract();

	void nativeStubLocal();

	virtual void virtualStubLocal();

	virtual void nativeAndVirtualStub();

protected:
	void protectedMethod();

private:
	void privateMethod();

public:
	WeakReference<Dispatch*> _this;

	operator const Dispatch*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~DispatchImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class Dispatch;
};

class DispatchAdapter : public ManagedObjectAdapter {
public:
	DispatchAdapter(Dispatch* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	void plainNative();

	void plainBody();

	void abstractWithBody();

	void abstractNative();

	void nativeStub();

	void nativeStubAbstract();

	void virtualStub();

	void virtualStubAbstract();

	void nativeAndVirtualStub();

	void noImplDecl();

};

class DispatchHelper : public DistributedObjectClassHelper, public Singleton<DispatchHelper> {
	static DispatchHelper* staticInitializer;

public:
	DispatchHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<DispatchHelper>;
};

} // namespace probe

using namespace probe;

namespace probe {

class DispatchPOD : public ManagedObjectPOD {
public:

	DispatchPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~DispatchPOD();

};

} // namespace probe

using namespace probe;

#endif /*DISPATCHPOD_H_*/
