/*
 *	autogen/probe/Dispatch.cpp generated by engine3 IDL compiler 0.70
 */

#include "Dispatch.h"

/*
 *	DispatchStub
 */

enum {RPC_PLAINNATIVE__ = 2935911594,RPC_PLAINBODY__,RPC_ABSTRACTWITHBODY__,RPC_ABSTRACTNATIVE__,RPC_NATIVESTUB__,RPC_NATIVESTUBABSTRACT__,RPC_VIRTUALSTUB__,RPC_VIRTUALSTUBABSTRACT__,RPC_NATIVEANDVIRTUALSTUB__,RPC_NOIMPLDECL__,};

Dispatch::Dispatch(DummyConstructorParameter* param) : ManagedObject(param) {
	_setClassName("Dispatch");
}

Dispatch::~Dispatch() {
}



void Dispatch::plainNative() {
	DispatchImplementation* _implementation = static_cast<DispatchImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_PLAINNATIVE__);

		method.executeWithVoidReturn();
	} else {
		_implementation->plainNative();
	}
}

void Dispatch::plainBody() {
	DispatchImplementation* _implementation = static_cast<DispatchImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_PLAINBODY__);

		method.executeWithVoidReturn();
	} else {
		_implementation->plainBody();
	}
}

void Dispatch::abstractWithBody() {
	DispatchImplementation* _implementation = static_cast<DispatchImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ABSTRACTWITHBODY__);

		method.executeWithVoidReturn();
	} else {
		_implementation->abstractWithBody();
	}
}

void Dispatch::abstractNative() {
	DispatchImplementation* _implementation = static_cast<DispatchImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ABSTRACTNATIVE__);

		method.executeWithVoidReturn();
	} else {
		_implementation->abstractNative();
	}
}

void Dispatch::localNative() {
	DispatchImplementation* _implementation = static_cast<DispatchImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->localNative();
	}
}

void Dispatch::localBody() {
	DispatchImplementation* _implementation = static_cast<DispatchImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->localBody();
	}
}

void Dispatch::__nativeStub() {
	DispatchImplementation* _implementation = static_cast<DispatchImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_NATIVESTUB__);

		method.executeWithVoidReturn();
	} else {
		_implementation->nativeStub();
	}
}

void Dispatch::__nativeStubAbstract() {
	DispatchImplementation* _implementation = static_cast<DispatchImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_NATIVESTUBABSTRACT__);

		method.executeWithVoidReturn();
	} else {
		_implementation->nativeStubAbstract();
	}
}

void Dispatch::virtualStub() {
	DispatchImplementation* _implementation = static_cast<DispatchImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_VIRTUALSTUB__);

		method.executeWithVoidReturn();
	} else {
		_implementation->virtualStub();
	}
}

void Dispatch::virtualStubAbstract() {
	DispatchImplementation* _implementation = static_cast<DispatchImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_VIRTUALSTUBABSTRACT__);

		method.executeWithVoidReturn();
	} else {
		_implementation->virtualStubAbstract();
	}
}

void Dispatch::__nativeStubLocal() {
	DispatchImplementation* _implementation = static_cast<DispatchImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->nativeStubLocal();
	}
}

void Dispatch::virtualStubLocal() {
	DispatchImplementation* _implementation = static_cast<DispatchImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->virtualStubLocal();
	}
}

void Dispatch::__nativeAndVirtualStub() {
	DispatchImplementation* _implementation = static_cast<DispatchImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_NATIVEANDVIRTUALSTUB__);

		method.executeWithVoidReturn();
	} else {
		_implementation->nativeAndVirtualStub();
	}
}

void Dispatch::noImplDecl() {
	DispatchImplementation* _implementation = static_cast<DispatchImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_NOIMPLDECL__);

		method.executeWithVoidReturn();
	} else {
		_implementation->noImplDecl();
	}
}

DistributedObjectServant* Dispatch::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* Dispatch::_getImplementationForRead() const {
	return _impl;
}

void Dispatch::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	DispatchImplementation
 */

DispatchImplementation::DispatchImplementation() : ManagedObjectImplementation() {
	_initializeImplementation();
}

DispatchImplementation::DispatchImplementation(DummyConstructorParameter* param) : ManagedObjectImplementation(param) {
	_initializeImplementation();
}


DispatchImplementation::~DispatchImplementation() {
}


void DispatchImplementation::finalize() {
}

void DispatchImplementation::_initializeImplementation() {
	_setClassHelper(DispatchHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void DispatchImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<Dispatch*>(stub);
	ManagedObjectImplementation::_setStub(stub);
}

DistributedObjectStub* DispatchImplementation::_getStub() {
	return _this.get();
}

DispatchImplementation::operator const Dispatch*() {
	return _this.get();
}

void DispatchImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void DispatchImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void DispatchImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void DispatchImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void DispatchImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void DispatchImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void DispatchImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void DispatchImplementation::_serializationHelperMethod() {
	ManagedObjectImplementation::_serializationHelperMethod();

	_setClassName("Dispatch");

}

void DispatchImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(DispatchImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool DispatchImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void DispatchImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = DispatchImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int DispatchImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

void DispatchImplementation::plainBody() {
}

void DispatchImplementation::abstractWithBody() {
}

void DispatchImplementation::localBody() {
}

/*
 *	DispatchAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


DispatchAdapter::DispatchAdapter(Dispatch* obj) : ManagedObjectAdapter(obj) {
}

void DispatchAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_PLAINNATIVE__:
		{
			
			plainNative();
			
		}
		break;
	case RPC_PLAINBODY__:
		{
			
			plainBody();
			
		}
		break;
	case RPC_ABSTRACTWITHBODY__:
		{
			
			abstractWithBody();
			
		}
		break;
	case RPC_ABSTRACTNATIVE__:
		{
			
			abstractNative();
			
		}
		break;
	case RPC_NATIVESTUB__:
		{
			
			nativeStub();
			
		}
		break;
	case RPC_NATIVESTUBABSTRACT__:
		{
			
			nativeStubAbstract();
			
		}
		break;
	case RPC_VIRTUALSTUB__:
		{
			
			virtualStub();
			
		}
		break;
	case RPC_VIRTUALSTUBABSTRACT__:
		{
			
			virtualStubAbstract();
			
		}
		break;
	case RPC_NATIVEANDVIRTUALSTUB__:
		{
			
			nativeAndVirtualStub();
			
		}
		break;
	case RPC_NOIMPLDECL__:
		{
			
			noImplDecl();
			
		}
		break;
	default:
		ManagedObjectAdapter::invokeMethod(methid, inv);
	}
}

void DispatchAdapter::plainNative() {
	(static_cast<Dispatch*>(stub))->plainNative();
}

void DispatchAdapter::plainBody() {
	(static_cast<Dispatch*>(stub))->plainBody();
}

void DispatchAdapter::abstractWithBody() {
	(static_cast<Dispatch*>(stub))->abstractWithBody();
}

void DispatchAdapter::abstractNative() {
	(static_cast<Dispatch*>(stub))->abstractNative();
}

void DispatchAdapter::nativeStub() {
	(static_cast<Dispatch*>(stub))->nativeStub();
}

void DispatchAdapter::nativeStubAbstract() {
	(static_cast<Dispatch*>(stub))->nativeStubAbstract();
}

void DispatchAdapter::virtualStub() {
	(static_cast<Dispatch*>(stub))->virtualStub();
}

void DispatchAdapter::virtualStubAbstract() {
	(static_cast<Dispatch*>(stub))->virtualStubAbstract();
}

void DispatchAdapter::nativeAndVirtualStub() {
	(static_cast<Dispatch*>(stub))->nativeAndVirtualStub();
}

void DispatchAdapter::noImplDecl() {
	(static_cast<Dispatch*>(stub))->noImplDecl();
}

/*
 *	DispatchHelper
 */

DispatchHelper* DispatchHelper::staticInitializer = DispatchHelper::instance();

DispatchHelper::DispatchHelper() {
	className = "Dispatch";

	Core::getObjectBroker()->registerClass(className, this);
}

void DispatchHelper::finalizeHelper() {
	DispatchHelper::finalize();
}

DistributedObject* DispatchHelper::instantiateObject() {
	return new Dispatch(DummyConstructorParameter::instance());
}

DistributedObjectServant* DispatchHelper::instantiateServant() {
	return new DispatchImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* DispatchHelper::instantiatePOD() {
	return new DispatchPOD();
}

DistributedObjectAdapter* DispatchHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new DispatchAdapter(static_cast<Dispatch*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	DispatchPOD
 */

DispatchPOD::~DispatchPOD() {
}

DispatchPOD::DispatchPOD(void) {
	_className = "Dispatch";
}


void DispatchPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = DispatchPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int DispatchPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

bool DispatchPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void DispatchPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(DispatchPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void DispatchPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ManagedObjectPOD::writeObjectCompact(stream);


}

