/*
 *	autogen/probe/Fields.h generated by engine3 IDL compiler 0.70
 */

#ifndef FIELDS_H_
#define FIELDS_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "system/util/Vector.h"

#include "engine/core/ManagedObject.h"

namespace probe {

class Fields : public ManagedObject {
public:
	static const int CONST_INT = 5;

	static const byte CONST_BYTE;

	unsigned static const int CONST_UINT;

	static const long long CONST_LONG;

	static const bool CONST_BOOL;

	static const float CONST_FLOAT;

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	Fields(DummyConstructorParameter* param);

	virtual ~Fields();

	friend class FieldsHelper;
};

} // namespace probe

using namespace probe;

namespace probe {

class FieldsImplementation : public ManagedObjectImplementation {
	int defaultVisField;

public:
	String pubField;

protected:
	int protField;

private:
	int explicitPrivField;

	int transientInt;

	ManagedReference<ManagedObject* > transientClass;

	ManagedReference<ManagedObject > derefClass;

	ManagedReference<ManagedObject > derefTransient;

protected:
	ManagedWeakReference<ManagedObject* > weakClass;

private:
	ManagedWeakReference<ManagedObject* > weakTransient;

	ManagedWeakReference<ManagedObject > weakDeref;

	Reference<Vector<int>* > vecPrim;

	Reference<Vector<ManagedReference<ManagedObject* > >* > vecClass;

public:
	static const int CONST_INT = 5;

	static const byte CONST_BYTE;

	unsigned static const int CONST_UINT;

	static const long long CONST_LONG;

	static const bool CONST_BOOL;

	static const float CONST_FLOAT;

	FieldsImplementation();
	FieldsImplementation(DummyConstructorParameter* param);

	WeakReference<Fields*> _this;

	operator const Fields*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~FieldsImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class Fields;
};

class FieldsAdapter : public ManagedObjectAdapter {
public:
	FieldsAdapter(Fields* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

};

class FieldsHelper : public DistributedObjectClassHelper, public Singleton<FieldsHelper> {
	static FieldsHelper* staticInitializer;

public:
	FieldsHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<FieldsHelper>;
};

} // namespace probe

using namespace probe;

namespace probe {

class FieldsPOD : public ManagedObjectPOD {
public:
	Optional<int> defaultVisField;

	Optional<String> pubField;

	Optional<int> protField;

	Optional<int> explicitPrivField;

	Optional<ManagedReference<ManagedObject >> derefClass;

	Optional<ManagedWeakReference<ManagedObjectPOD* >> weakClass;

	Optional<ManagedWeakReference<ManagedObject >> weakDeref;

	Optional<Reference<Vector<int>* >> vecPrim;

	Optional<Reference<Vector<ManagedReference<ManagedObjectPOD* > >* >> vecClass;

	String _className;
	FieldsPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~FieldsPOD();

};

} // namespace probe

using namespace probe;

#endif /*FIELDSPOD_H_*/
