/*
 *	autogen/probe/Fields.cpp generated by engine3 IDL compiler 0.70
 */

#include "Fields.h"

/*
 *	FieldsStub
 */

const byte Fields::CONST_BYTE = 1;

unsigned const int Fields::CONST_UINT = 100;

const long long Fields::CONST_LONG = 12345;

const bool Fields::CONST_BOOL = true;

const float Fields::CONST_FLOAT = 3.14;

Fields::Fields(DummyConstructorParameter* param) : ManagedObject(param) {
	_setClassName("Fields");
}

Fields::~Fields() {
}



DistributedObjectServant* Fields::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* Fields::_getImplementationForRead() const {
	return _impl;
}

void Fields::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	FieldsImplementation
 */

const byte FieldsImplementation::CONST_BYTE = 1;

unsigned const int FieldsImplementation::CONST_UINT = 100;

const long long FieldsImplementation::CONST_LONG = 12345;

const bool FieldsImplementation::CONST_BOOL = true;

const float FieldsImplementation::CONST_FLOAT = 3.14;

FieldsImplementation::FieldsImplementation() : ManagedObjectImplementation() {
	_initializeImplementation();
}

FieldsImplementation::FieldsImplementation(DummyConstructorParameter* param) : ManagedObjectImplementation(param) {
	_initializeImplementation();
}


FieldsImplementation::~FieldsImplementation() {
}


void FieldsImplementation::finalize() {
}

void FieldsImplementation::_initializeImplementation() {
	_setClassHelper(FieldsHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void FieldsImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<Fields*>(stub);
	ManagedObjectImplementation::_setStub(stub);
}

DistributedObjectStub* FieldsImplementation::_getStub() {
	return _this.get();
}

FieldsImplementation::operator const Fields*() {
	return _this.get();
}

void FieldsImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void FieldsImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void FieldsImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void FieldsImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void FieldsImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void FieldsImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void FieldsImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void FieldsImplementation::_serializationHelperMethod() {
	ManagedObjectImplementation::_serializationHelperMethod();

	_setClassName("Fields");

}

void FieldsImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(FieldsImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool FieldsImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x76935242: //Fields.defaultVisField
		TypeInfo<int >::parseFromBinaryStream(&defaultVisField, stream);
		return true;

	case 0x6a1afdd7: //Fields.pubField
		TypeInfo<String >::parseFromBinaryStream(&pubField, stream);
		return true;

	case 0x45a4b9c5: //Fields.protField
		TypeInfo<int >::parseFromBinaryStream(&protField, stream);
		return true;

	case 0x18cd94f0: //Fields.explicitPrivField
		TypeInfo<int >::parseFromBinaryStream(&explicitPrivField, stream);
		return true;

	case 0x63d809b2: //Fields.derefClass
		TypeInfo<ManagedReference<ManagedObject > >::parseFromBinaryStream(&derefClass, stream);
		return true;

	case 0x720841d5: //Fields.weakClass
		TypeInfo<ManagedWeakReference<ManagedObject* > >::parseFromBinaryStream(&weakClass, stream);
		return true;

	case 0x1ddcc12b: //Fields.weakDeref
		TypeInfo<ManagedWeakReference<ManagedObject > >::parseFromBinaryStream(&weakDeref, stream);
		return true;

	case 0x16968fe4: //Fields.vecPrim
		TypeInfo<Reference<Vector<int>* > >::parseFromBinaryStream(&vecPrim, stream);
		return true;

	case 0x7bc67d86: //Fields.vecClass
		TypeInfo<Reference<Vector<ManagedReference<ManagedObject* > >* > >::parseFromBinaryStream(&vecClass, stream);
		return true;

	}

	return false;
}

void FieldsImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = FieldsImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int FieldsImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0x76935242; //Fields.defaultVisField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&defaultVisField, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x6a1afdd7; //Fields.pubField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&pubField, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x45a4b9c5; //Fields.protField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&protField, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x18cd94f0; //Fields.explicitPrivField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&explicitPrivField, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x63d809b2; //Fields.derefClass
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedReference<ManagedObject > >::toBinaryStream(&derefClass, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x720841d5; //Fields.weakClass
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedWeakReference<ManagedObject* > >::toBinaryStream(&weakClass, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x1ddcc12b; //Fields.weakDeref
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedWeakReference<ManagedObject > >::toBinaryStream(&weakDeref, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x16968fe4; //Fields.vecPrim
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Reference<Vector<int>* > >::toBinaryStream(&vecPrim, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x7bc67d86; //Fields.vecClass
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Reference<Vector<ManagedReference<ManagedObject* > >* > >::toBinaryStream(&vecClass, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

/*
 *	FieldsAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


FieldsAdapter::FieldsAdapter(Fields* obj) : ManagedObjectAdapter(obj) {
}

void FieldsAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	default:
		ManagedObjectAdapter::invokeMethod(methid, inv);
	}
}

/*
 *	FieldsHelper
 */

FieldsHelper* FieldsHelper::staticInitializer = FieldsHelper::instance();

FieldsHelper::FieldsHelper() {
	className = "Fields";

	Core::getObjectBroker()->registerClass(className, this);
}

void FieldsHelper::finalizeHelper() {
	FieldsHelper::finalize();
}

DistributedObject* FieldsHelper::instantiateObject() {
	return new Fields(DummyConstructorParameter::instance());
}

DistributedObjectServant* FieldsHelper::instantiateServant() {
	return new FieldsImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* FieldsHelper::instantiatePOD() {
	return new FieldsPOD();
}

DistributedObjectAdapter* FieldsHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new FieldsAdapter(static_cast<Fields*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	FieldsPOD
 */

FieldsPOD::~FieldsPOD() {
}

FieldsPOD::FieldsPOD(void) {
	_className = "Fields";
}


void FieldsPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = FieldsPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int FieldsPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (defaultVisField) {
	_nameHashCode = 0x76935242; //Fields.defaultVisField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&defaultVisField.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (pubField) {
	_nameHashCode = 0x6a1afdd7; //Fields.pubField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&pubField.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (protField) {
	_nameHashCode = 0x45a4b9c5; //Fields.protField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&protField.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (explicitPrivField) {
	_nameHashCode = 0x18cd94f0; //Fields.explicitPrivField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&explicitPrivField.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (derefClass) {
	_nameHashCode = 0x63d809b2; //Fields.derefClass
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedReference<ManagedObject > >::toBinaryStream(&derefClass.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (weakClass) {
	_nameHashCode = 0x720841d5; //Fields.weakClass
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedWeakReference<ManagedObjectPOD* > >::toBinaryStream(&weakClass.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (weakDeref) {
	_nameHashCode = 0x1ddcc12b; //Fields.weakDeref
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedWeakReference<ManagedObject > >::toBinaryStream(&weakDeref.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (vecPrim) {
	_nameHashCode = 0x16968fe4; //Fields.vecPrim
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Reference<Vector<int>* > >::toBinaryStream(&vecPrim.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (vecClass) {
	_nameHashCode = 0x7bc67d86; //Fields.vecClass
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Reference<Vector<ManagedReference<ManagedObjectPOD* > >* > >::toBinaryStream(&vecClass.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool FieldsPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x76935242: //Fields.defaultVisField
		{
			int _mndefaultVisField;
			TypeInfo<int >::parseFromBinaryStream(&_mndefaultVisField, stream);
			defaultVisField = std::move(_mndefaultVisField);
		}
		return true;

	case 0x6a1afdd7: //Fields.pubField
		{
			String _mnpubField;
			TypeInfo<String >::parseFromBinaryStream(&_mnpubField, stream);
			pubField = std::move(_mnpubField);
		}
		return true;

	case 0x45a4b9c5: //Fields.protField
		{
			int _mnprotField;
			TypeInfo<int >::parseFromBinaryStream(&_mnprotField, stream);
			protField = std::move(_mnprotField);
		}
		return true;

	case 0x18cd94f0: //Fields.explicitPrivField
		{
			int _mnexplicitPrivField;
			TypeInfo<int >::parseFromBinaryStream(&_mnexplicitPrivField, stream);
			explicitPrivField = std::move(_mnexplicitPrivField);
		}
		return true;

	case 0x63d809b2: //Fields.derefClass
		{
			ManagedReference<ManagedObject > _mnderefClass;
			TypeInfo<ManagedReference<ManagedObject > >::parseFromBinaryStream(&_mnderefClass, stream);
			derefClass = std::move(_mnderefClass);
		}
		return true;

	case 0x720841d5: //Fields.weakClass
		{
			ManagedWeakReference<ManagedObjectPOD* > _mnweakClass;
			TypeInfo<ManagedWeakReference<ManagedObjectPOD* > >::parseFromBinaryStream(&_mnweakClass, stream);
			weakClass = std::move(_mnweakClass);
		}
		return true;

	case 0x1ddcc12b: //Fields.weakDeref
		{
			ManagedWeakReference<ManagedObject > _mnweakDeref;
			TypeInfo<ManagedWeakReference<ManagedObject > >::parseFromBinaryStream(&_mnweakDeref, stream);
			weakDeref = std::move(_mnweakDeref);
		}
		return true;

	case 0x16968fe4: //Fields.vecPrim
		{
			Reference<Vector<int>* > _mnvecPrim;
			TypeInfo<Reference<Vector<int>* > >::parseFromBinaryStream(&_mnvecPrim, stream);
			vecPrim = std::move(_mnvecPrim);
		}
		return true;

	case 0x7bc67d86: //Fields.vecClass
		{
			Reference<Vector<ManagedReference<ManagedObjectPOD* > >* > _mnvecClass;
			TypeInfo<Reference<Vector<ManagedReference<ManagedObjectPOD* > >* > >::parseFromBinaryStream(&_mnvecClass, stream);
			vecClass = std::move(_mnvecClass);
		}
		return true;

	}

	return false;
}

void FieldsPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(FieldsPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void FieldsPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ManagedObjectPOD::writeObjectCompact(stream);

	TypeInfo<int >::toBinaryStream(&defaultVisField.value(), stream);

	TypeInfo<String >::toBinaryStream(&pubField.value(), stream);

	TypeInfo<int >::toBinaryStream(&protField.value(), stream);

	TypeInfo<int >::toBinaryStream(&explicitPrivField.value(), stream);

	TypeInfo<ManagedReference<ManagedObject > >::toBinaryStream(&derefClass.value(), stream);

	TypeInfo<ManagedWeakReference<ManagedObjectPOD* > >::toBinaryStream(&weakClass.value(), stream);

	TypeInfo<ManagedWeakReference<ManagedObject > >::toBinaryStream(&weakDeref.value(), stream);

	TypeInfo<Reference<Vector<int>* > >::toBinaryStream(&vecPrim.value(), stream);

	TypeInfo<Reference<Vector<ManagedReference<ManagedObjectPOD* > >* > >::toBinaryStream(&vecClass.value(), stream);


}

