/*
 *	autogen/probe/Generics.h generated by engine3 IDL compiler 0.70
 */

#ifndef GENERICS_H_
#define GENERICS_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "system/util/Vector.h"

#include "system/util/VectorMap.h"

#include "system/util/SortedVector.h"

#include "system/util/SynchronizedSortedVector.h"

#include "engine/core/ManagedObject.h"

namespace probe {

class Generics : public ManagedObject {
public:
	Vector<int>* retVecInt();

	Vector<ManagedReference<ManagedObject* > >* retVecClass();

	SortedVector<int>* retSVecInt();

	SortedVector<ManagedReference<ManagedObject* > >* retSVecClass();

	SynchronizedSortedVector<ManagedReference<ManagedObject* > >* retSSVecClass();

	VectorMap<String, int>* retVMapStrInt();

	VectorMap<String, ManagedReference<ManagedObject* > >* retVMapStrClass();

	VectorMap<ManagedReference<ManagedObject* >, ManagedReference<ManagedObject* > >* retVMapClassClass();

	Vector<Vector<int>*>* retNestedVecPrim();

	VectorMap<String, Vector<int>*>* retVMapStrVecInt();

	Vector<int> derefRetVecInt();

	VectorMap<String, ManagedReference<ManagedObject* > > derefRetVMapStrClass();

	void paramVecInt(Vector<int>* v);

	void paramVMapStrClass(VectorMap<String, ManagedReference<ManagedObject* > >* m);

	void paramVecClass(const Vector<ManagedReference<ManagedObject* > >* v);

	void derefParamVMap(VectorMap<String, ManagedReference<ManagedObject* > >* m);

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	Generics(DummyConstructorParameter* param);

	virtual ~Generics();

	friend class GenericsHelper;
};

} // namespace probe

using namespace probe;

namespace probe {

class GenericsImplementation : public ManagedObjectImplementation {
	Reference<Vector<int>* > fieldVecInt;

	Reference<Vector<ManagedReference<ManagedObject* > >* > fieldVecClass;

	Reference<VectorMap<String, ManagedReference<ManagedObject* > >* > fieldVMapStrClass;

	Vector<int> derefFieldVecInt;

	VectorMap<String, ManagedReference<ManagedObject* > > derefFieldVMap;

public:
	GenericsImplementation();
	GenericsImplementation(DummyConstructorParameter* param);

	Vector<int>* retVecInt();

	Vector<ManagedReference<ManagedObject* > >* retVecClass();

	SortedVector<int>* retSVecInt();

	SortedVector<ManagedReference<ManagedObject* > >* retSVecClass();

	SynchronizedSortedVector<ManagedReference<ManagedObject* > >* retSSVecClass();

	VectorMap<String, int>* retVMapStrInt();

	VectorMap<String, ManagedReference<ManagedObject* > >* retVMapStrClass();

	VectorMap<ManagedReference<ManagedObject* >, ManagedReference<ManagedObject* > >* retVMapClassClass();

	Vector<Vector<int>*>* retNestedVecPrim();

	VectorMap<String, Vector<int>*>* retVMapStrVecInt();

	Vector<int> derefRetVecInt();

	VectorMap<String, ManagedReference<ManagedObject* > > derefRetVMapStrClass();

	void paramVecInt(Vector<int>* v);

	void paramVMapStrClass(VectorMap<String, ManagedReference<ManagedObject* > >* m);

	void paramVecClass(const Vector<ManagedReference<ManagedObject* > >* v);

	void derefParamVMap(VectorMap<String, ManagedReference<ManagedObject* > >* m);

	WeakReference<Generics*> _this;

	operator const Generics*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~GenericsImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class Generics;
};

class GenericsAdapter : public ManagedObjectAdapter {
public:
	GenericsAdapter(Generics* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	Vector<int>* retVecInt();

	Vector<ManagedReference<ManagedObject* > >* retVecClass();

	SortedVector<int>* retSVecInt();

	SortedVector<ManagedReference<ManagedObject* > >* retSVecClass();

	SynchronizedSortedVector<ManagedReference<ManagedObject* > >* retSSVecClass();

	VectorMap<String, int>* retVMapStrInt();

	VectorMap<String, ManagedReference<ManagedObject* > >* retVMapStrClass();

	VectorMap<ManagedReference<ManagedObject* >, ManagedReference<ManagedObject* > >* retVMapClassClass();

	Vector<Vector<int>*>* retNestedVecPrim();

	VectorMap<String, Vector<int>*>* retVMapStrVecInt();

	Vector<int> derefRetVecInt();

	VectorMap<String, ManagedReference<ManagedObject* > > derefRetVMapStrClass();

	void paramVecInt(Vector<int>* v);

	void paramVMapStrClass(VectorMap<String, ManagedReference<ManagedObject* > >* m);

	void paramVecClass(const Vector<ManagedReference<ManagedObject* > >* v);

	void derefParamVMap(VectorMap<String, ManagedReference<ManagedObject* > >* m);

};

class GenericsHelper : public DistributedObjectClassHelper, public Singleton<GenericsHelper> {
	static GenericsHelper* staticInitializer;

public:
	GenericsHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<GenericsHelper>;
};

} // namespace probe

using namespace probe;

namespace probe {

class GenericsPOD : public ManagedObjectPOD {
public:
	Optional<Reference<Vector<int>* >> fieldVecInt;

	Optional<Reference<Vector<ManagedReference<ManagedObjectPOD* > >* >> fieldVecClass;

	Optional<Reference<VectorMap<String, ManagedReference<ManagedObjectPOD* > >* >> fieldVMapStrClass;

	Optional<Vector<int>> derefFieldVecInt;

	Optional<VectorMap<String, ManagedReference<ManagedObjectPOD* > >> derefFieldVMap;

	String _className;
	GenericsPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~GenericsPOD();

};

} // namespace probe

using namespace probe;

#endif /*GENERICSPOD_H_*/
