/*
 *	autogen/probe/Generics.cpp generated by engine3 IDL compiler 0.70
 */

#include "Generics.h"

/*
 *	GenericsStub
 */

enum {RPC_RETVECINT__ = 534223235,RPC_RETVECCLASS__,RPC_RETSVECINT__,RPC_RETSVECCLASS__,RPC_RETSSVECCLASS__,RPC_RETVMAPSTRINT__,RPC_RETVMAPSTRCLASS__,RPC_RETVMAPCLASSCLASS__,RPC_RETNESTEDVECPRIM__,RPC_RETVMAPSTRVECINT__,RPC_DEREFRETVECINT__,RPC_DEREFRETVMAPSTRCLASS__,RPC_PARAMVECINT__VECTOR_,RPC_PARAMVMAPSTRCLASS__VECTORMAP_,RPC_PARAMVECCLASS__VECTOR_,RPC_DEREFPARAMVMAP__VECTORMAP_};

Generics::Generics(DummyConstructorParameter* param) : ManagedObject(param) {
	_setClassName("Generics");
}

Generics::~Generics() {
}



Vector<int>* Generics::retVecInt() {
	GenericsImplementation* _implementation = static_cast<GenericsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_RETVECINT__);

		return static_cast<Vector<int>*>(method.executeWithObjectReturn());
	} else {
		return _implementation->retVecInt();
	}
}

Vector<ManagedReference<ManagedObject* > >* Generics::retVecClass() {
	GenericsImplementation* _implementation = static_cast<GenericsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_RETVECCLASS__);

		return static_cast<Vector<ManagedReference<ManagedObject* > >*>(method.executeWithObjectReturn());
	} else {
		return _implementation->retVecClass();
	}
}

SortedVector<int>* Generics::retSVecInt() {
	GenericsImplementation* _implementation = static_cast<GenericsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_RETSVECINT__);

		return static_cast<SortedVector<int>*>(method.executeWithObjectReturn());
	} else {
		return _implementation->retSVecInt();
	}
}

SortedVector<ManagedReference<ManagedObject* > >* Generics::retSVecClass() {
	GenericsImplementation* _implementation = static_cast<GenericsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_RETSVECCLASS__);

		return static_cast<SortedVector<ManagedReference<ManagedObject* > >*>(method.executeWithObjectReturn());
	} else {
		return _implementation->retSVecClass();
	}
}

SynchronizedSortedVector<ManagedReference<ManagedObject* > >* Generics::retSSVecClass() {
	GenericsImplementation* _implementation = static_cast<GenericsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_RETSSVECCLASS__);

		return static_cast<SynchronizedSortedVector<ManagedReference<ManagedObject* > >*>(method.executeWithObjectReturn());
	} else {
		return _implementation->retSSVecClass();
	}
}

VectorMap<String, int>* Generics::retVMapStrInt() {
	GenericsImplementation* _implementation = static_cast<GenericsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_RETVMAPSTRINT__);

		return static_cast<VectorMap<String, int>*>(method.executeWithObjectReturn());
	} else {
		return _implementation->retVMapStrInt();
	}
}

VectorMap<String, ManagedReference<ManagedObject* > >* Generics::retVMapStrClass() {
	GenericsImplementation* _implementation = static_cast<GenericsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_RETVMAPSTRCLASS__);

		return static_cast<VectorMap<String, ManagedReference<ManagedObject* > >*>(method.executeWithObjectReturn());
	} else {
		return _implementation->retVMapStrClass();
	}
}

VectorMap<ManagedReference<ManagedObject* >, ManagedReference<ManagedObject* > >* Generics::retVMapClassClass() {
	GenericsImplementation* _implementation = static_cast<GenericsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_RETVMAPCLASSCLASS__);

		return static_cast<VectorMap<ManagedReference<ManagedObject* >, ManagedReference<ManagedObject* > >*>(method.executeWithObjectReturn());
	} else {
		return _implementation->retVMapClassClass();
	}
}

Vector<Vector<int>*>* Generics::retNestedVecPrim() {
	GenericsImplementation* _implementation = static_cast<GenericsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_RETNESTEDVECPRIM__);

		return static_cast<Vector<Vector<int>*>*>(method.executeWithObjectReturn());
	} else {
		return _implementation->retNestedVecPrim();
	}
}

VectorMap<String, Vector<int>*>* Generics::retVMapStrVecInt() {
	GenericsImplementation* _implementation = static_cast<GenericsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_RETVMAPSTRVECINT__);

		return static_cast<VectorMap<String, Vector<int>*>*>(method.executeWithObjectReturn());
	} else {
		return _implementation->retVMapStrVecInt();
	}
}

Vector<int> Generics::derefRetVecInt() {
	GenericsImplementation* _implementation = static_cast<GenericsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_DEREFRETVECINT__);

		return static_cast<Vector<int>>(method.executeWithObjectReturn());
	} else {
		return _implementation->derefRetVecInt();
	}
}

VectorMap<String, ManagedReference<ManagedObject* > > Generics::derefRetVMapStrClass() {
	GenericsImplementation* _implementation = static_cast<GenericsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_DEREFRETVMAPSTRCLASS__);

		return static_cast<VectorMap<String, ManagedReference<ManagedObject* > >>(method.executeWithObjectReturn());
	} else {
		return _implementation->derefRetVMapStrClass();
	}
}

void Generics::paramVecInt(Vector<int>* v) {
	GenericsImplementation* _implementation = static_cast<GenericsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_PARAMVECINT__VECTOR_);
		method.addObjectParameter(v);

		method.executeWithVoidReturn();
	} else {
		_implementation->paramVecInt(v);
	}
}

void Generics::paramVMapStrClass(VectorMap<String, ManagedReference<ManagedObject* > >* m) {
	GenericsImplementation* _implementation = static_cast<GenericsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_PARAMVMAPSTRCLASS__VECTORMAP_);
		method.addObjectParameter(m);

		method.executeWithVoidReturn();
	} else {
		_implementation->paramVMapStrClass(m);
	}
}

void Generics::paramVecClass(const Vector<ManagedReference<ManagedObject* > >* v) {
	GenericsImplementation* _implementation = static_cast<GenericsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_PARAMVECCLASS__VECTOR_);
		method.addObjectParameter(v);

		method.executeWithVoidReturn();
	} else {
		_implementation->paramVecClass(v);
	}
}

void Generics::derefParamVMap(VectorMap<String, ManagedReference<ManagedObject* > >* m) {
	GenericsImplementation* _implementation = static_cast<GenericsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_DEREFPARAMVMAP__VECTORMAP_);
		method.addObjectParameter(m);

		method.executeWithVoidReturn();
	} else {
		_implementation->derefParamVMap(m);
	}
}

DistributedObjectServant* Generics::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* Generics::_getImplementationForRead() const {
	return _impl;
}

void Generics::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	GenericsImplementation
 */

GenericsImplementation::GenericsImplementation() : ManagedObjectImplementation() {
	_initializeImplementation();
}

GenericsImplementation::GenericsImplementation(DummyConstructorParameter* param) : ManagedObjectImplementation(param) {
	_initializeImplementation();
}


GenericsImplementation::~GenericsImplementation() {
}


void GenericsImplementation::finalize() {
}

void GenericsImplementation::_initializeImplementation() {
	_setClassHelper(GenericsHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void GenericsImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<Generics*>(stub);
	ManagedObjectImplementation::_setStub(stub);
}

DistributedObjectStub* GenericsImplementation::_getStub() {
	return _this.get();
}

GenericsImplementation::operator const Generics*() {
	return _this.get();
}

void GenericsImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void GenericsImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void GenericsImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void GenericsImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void GenericsImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void GenericsImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void GenericsImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void GenericsImplementation::_serializationHelperMethod() {
	ManagedObjectImplementation::_serializationHelperMethod();

	_setClassName("Generics");

}

void GenericsImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(GenericsImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool GenericsImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0xdbac855b: //Generics.fieldVecInt
		TypeInfo<Reference<Vector<int>* > >::parseFromBinaryStream(&fieldVecInt, stream);
		return true;

	case 0xf79f614: //Generics.fieldVecClass
		TypeInfo<Reference<Vector<ManagedReference<ManagedObject* > >* > >::parseFromBinaryStream(&fieldVecClass, stream);
		return true;

	case 0xd1ce21e2: //Generics.fieldVMapStrClass
		TypeInfo<Reference<VectorMap<String, ManagedReference<ManagedObject* > >* > >::parseFromBinaryStream(&fieldVMapStrClass, stream);
		return true;

	case 0x21e4962: //Generics.derefFieldVecInt
		TypeInfo<Vector<int> >::parseFromBinaryStream(&derefFieldVecInt, stream);
		return true;

	case 0x1b89ea6: //Generics.derefFieldVMap
		TypeInfo<VectorMap<String, ManagedReference<ManagedObject* > > >::parseFromBinaryStream(&derefFieldVMap, stream);
		return true;

	}

	return false;
}

void GenericsImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = GenericsImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int GenericsImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0xdbac855b; //Generics.fieldVecInt
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Reference<Vector<int>* > >::toBinaryStream(&fieldVecInt, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xf79f614; //Generics.fieldVecClass
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Reference<Vector<ManagedReference<ManagedObject* > >* > >::toBinaryStream(&fieldVecClass, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xd1ce21e2; //Generics.fieldVMapStrClass
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Reference<VectorMap<String, ManagedReference<ManagedObject* > >* > >::toBinaryStream(&fieldVMapStrClass, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x21e4962; //Generics.derefFieldVecInt
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Vector<int> >::toBinaryStream(&derefFieldVecInt, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x1b89ea6; //Generics.derefFieldVMap
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<VectorMap<String, ManagedReference<ManagedObject* > > >::toBinaryStream(&derefFieldVMap, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

/*
 *	GenericsAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


GenericsAdapter::GenericsAdapter(Generics* obj) : ManagedObjectAdapter(obj) {
}

void GenericsAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_RETVECINT__:
		{
			
			DistributedObject* _m_res = retVecInt();
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	case RPC_RETVECCLASS__:
		{
			
			DistributedObject* _m_res = retVecClass();
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	case RPC_RETSVECINT__:
		{
			
			DistributedObject* _m_res = retSVecInt();
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	case RPC_RETSVECCLASS__:
		{
			
			DistributedObject* _m_res = retSVecClass();
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	case RPC_RETSSVECCLASS__:
		{
			
			DistributedObject* _m_res = retSSVecClass();
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	case RPC_RETVMAPSTRINT__:
		{
			
			DistributedObject* _m_res = retVMapStrInt();
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	case RPC_RETVMAPSTRCLASS__:
		{
			
			DistributedObject* _m_res = retVMapStrClass();
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	case RPC_RETVMAPCLASSCLASS__:
		{
			
			DistributedObject* _m_res = retVMapClassClass();
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	case RPC_RETNESTEDVECPRIM__:
		{
			
			DistributedObject* _m_res = retNestedVecPrim();
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	case RPC_RETVMAPSTRVECINT__:
		{
			
			DistributedObject* _m_res = retVMapStrVecInt();
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	case RPC_DEREFRETVECINT__:
		{
			
			DistributedObject* _m_res = derefRetVecInt();
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	case RPC_DEREFRETVMAPSTRCLASS__:
		{
			
			DistributedObject* _m_res = derefRetVMapStrClass();
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	case RPC_PARAMVECINT__VECTOR_:
		{
			Vector<int>* v = static_cast<Vector*>(inv->getObjectParameter());
			
			paramVecInt(v);
			
		}
		break;
	case RPC_PARAMVMAPSTRCLASS__VECTORMAP_:
		{
			VectorMap<String, ManagedReference<ManagedObject* > >* m = static_cast<VectorMap*>(inv->getObjectParameter());
			
			paramVMapStrClass(m);
			
		}
		break;
	case RPC_PARAMVECCLASS__VECTOR_:
		{
			 Vector<ManagedReference<ManagedObject* > >* v = static_cast<Vector*>(inv->getObjectParameter());
			
			paramVecClass(v);
			
		}
		break;
	case RPC_DEREFPARAMVMAP__VECTORMAP_:
		{
			VectorMap<String, ManagedReference<ManagedObject* > >* m = static_cast<VectorMap*>(inv->getObjectParameter());
			
			derefParamVMap(m);
			
		}
		break;
	default:
		ManagedObjectAdapter::invokeMethod(methid, inv);
	}
}

Vector<int>* GenericsAdapter::retVecInt() {
	return (static_cast<Generics*>(stub))->retVecInt();
}

Vector<ManagedReference<ManagedObject* > >* GenericsAdapter::retVecClass() {
	return (static_cast<Generics*>(stub))->retVecClass();
}

SortedVector<int>* GenericsAdapter::retSVecInt() {
	return (static_cast<Generics*>(stub))->retSVecInt();
}

SortedVector<ManagedReference<ManagedObject* > >* GenericsAdapter::retSVecClass() {
	return (static_cast<Generics*>(stub))->retSVecClass();
}

SynchronizedSortedVector<ManagedReference<ManagedObject* > >* GenericsAdapter::retSSVecClass() {
	return (static_cast<Generics*>(stub))->retSSVecClass();
}

VectorMap<String, int>* GenericsAdapter::retVMapStrInt() {
	return (static_cast<Generics*>(stub))->retVMapStrInt();
}

VectorMap<String, ManagedReference<ManagedObject* > >* GenericsAdapter::retVMapStrClass() {
	return (static_cast<Generics*>(stub))->retVMapStrClass();
}

VectorMap<ManagedReference<ManagedObject* >, ManagedReference<ManagedObject* > >* GenericsAdapter::retVMapClassClass() {
	return (static_cast<Generics*>(stub))->retVMapClassClass();
}

Vector<Vector<int>*>* GenericsAdapter::retNestedVecPrim() {
	return (static_cast<Generics*>(stub))->retNestedVecPrim();
}

VectorMap<String, Vector<int>*>* GenericsAdapter::retVMapStrVecInt() {
	return (static_cast<Generics*>(stub))->retVMapStrVecInt();
}

Vector<int> GenericsAdapter::derefRetVecInt() {
	return (static_cast<Generics*>(stub))->derefRetVecInt();
}

VectorMap<String, ManagedReference<ManagedObject* > > GenericsAdapter::derefRetVMapStrClass() {
	return (static_cast<Generics*>(stub))->derefRetVMapStrClass();
}

void GenericsAdapter::paramVecInt(Vector<int>* v) {
	(static_cast<Generics*>(stub))->paramVecInt(v);
}

void GenericsAdapter::paramVMapStrClass(VectorMap<String, ManagedReference<ManagedObject* > >* m) {
	(static_cast<Generics*>(stub))->paramVMapStrClass(m);
}

void GenericsAdapter::paramVecClass(const Vector<ManagedReference<ManagedObject* > >* v) {
	(static_cast<Generics*>(stub))->paramVecClass(v);
}

void GenericsAdapter::derefParamVMap(VectorMap<String, ManagedReference<ManagedObject* > >* m) {
	(static_cast<Generics*>(stub))->derefParamVMap(m);
}

/*
 *	GenericsHelper
 */

GenericsHelper* GenericsHelper::staticInitializer = GenericsHelper::instance();

GenericsHelper::GenericsHelper() {
	className = "Generics";

	Core::getObjectBroker()->registerClass(className, this);
}

void GenericsHelper::finalizeHelper() {
	GenericsHelper::finalize();
}

DistributedObject* GenericsHelper::instantiateObject() {
	return new Generics(DummyConstructorParameter::instance());
}

DistributedObjectServant* GenericsHelper::instantiateServant() {
	return new GenericsImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* GenericsHelper::instantiatePOD() {
	return new GenericsPOD();
}

DistributedObjectAdapter* GenericsHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new GenericsAdapter(static_cast<Generics*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	GenericsPOD
 */

GenericsPOD::~GenericsPOD() {
}

GenericsPOD::GenericsPOD(void) {
	_className = "Generics";
}


void GenericsPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = GenericsPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int GenericsPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (fieldVecInt) {
	_nameHashCode = 0xdbac855b; //Generics.fieldVecInt
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Reference<Vector<int>* > >::toBinaryStream(&fieldVecInt.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (fieldVecClass) {
	_nameHashCode = 0xf79f614; //Generics.fieldVecClass
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Reference<Vector<ManagedReference<ManagedObjectPOD* > >* > >::toBinaryStream(&fieldVecClass.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (fieldVMapStrClass) {
	_nameHashCode = 0xd1ce21e2; //Generics.fieldVMapStrClass
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Reference<VectorMap<String, ManagedReference<ManagedObjectPOD* > >* > >::toBinaryStream(&fieldVMapStrClass.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (derefFieldVecInt) {
	_nameHashCode = 0x21e4962; //Generics.derefFieldVecInt
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Vector<int> >::toBinaryStream(&derefFieldVecInt.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (derefFieldVMap) {
	_nameHashCode = 0x1b89ea6; //Generics.derefFieldVMap
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<VectorMap<String, ManagedReference<ManagedObjectPOD* > > >::toBinaryStream(&derefFieldVMap.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool GenericsPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0xdbac855b: //Generics.fieldVecInt
		{
			Reference<Vector<int>* > _mnfieldVecInt;
			TypeInfo<Reference<Vector<int>* > >::parseFromBinaryStream(&_mnfieldVecInt, stream);
			fieldVecInt = std::move(_mnfieldVecInt);
		}
		return true;

	case 0xf79f614: //Generics.fieldVecClass
		{
			Reference<Vector<ManagedReference<ManagedObjectPOD* > >* > _mnfieldVecClass;
			TypeInfo<Reference<Vector<ManagedReference<ManagedObjectPOD* > >* > >::parseFromBinaryStream(&_mnfieldVecClass, stream);
			fieldVecClass = std::move(_mnfieldVecClass);
		}
		return true;

	case 0xd1ce21e2: //Generics.fieldVMapStrClass
		{
			Reference<VectorMap<String, ManagedReference<ManagedObjectPOD* > >* > _mnfieldVMapStrClass;
			TypeInfo<Reference<VectorMap<String, ManagedReference<ManagedObjectPOD* > >* > >::parseFromBinaryStream(&_mnfieldVMapStrClass, stream);
			fieldVMapStrClass = std::move(_mnfieldVMapStrClass);
		}
		return true;

	case 0x21e4962: //Generics.derefFieldVecInt
		{
			Vector<int> _mnderefFieldVecInt;
			TypeInfo<Vector<int> >::parseFromBinaryStream(&_mnderefFieldVecInt, stream);
			derefFieldVecInt = std::move(_mnderefFieldVecInt);
		}
		return true;

	case 0x1b89ea6: //Generics.derefFieldVMap
		{
			VectorMap<String, ManagedReference<ManagedObjectPOD* > > _mnderefFieldVMap;
			TypeInfo<VectorMap<String, ManagedReference<ManagedObjectPOD* > > >::parseFromBinaryStream(&_mnderefFieldVMap, stream);
			derefFieldVMap = std::move(_mnderefFieldVMap);
		}
		return true;

	}

	return false;
}

void GenericsPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(GenericsPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void GenericsPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ManagedObjectPOD::writeObjectCompact(stream);

	TypeInfo<Reference<Vector<int>* > >::toBinaryStream(&fieldVecInt.value(), stream);

	TypeInfo<Reference<Vector<ManagedReference<ManagedObjectPOD* > >* > >::toBinaryStream(&fieldVecClass.value(), stream);

	TypeInfo<Reference<VectorMap<String, ManagedReference<ManagedObjectPOD* > >* > >::toBinaryStream(&fieldVMapStrClass.value(), stream);

	TypeInfo<Vector<int> >::toBinaryStream(&derefFieldVecInt.value(), stream);

	TypeInfo<VectorMap<String, ManagedReference<ManagedObjectPOD* > > >::toBinaryStream(&derefFieldVMap.value(), stream);


}

