/*
 *	autogen/probe/Inheritance.cpp generated by engine3 IDL compiler 0.70
 */

#include "Inheritance.h"

/*
 *	InheritanceStub
 */

enum {RPC_FINALIZE__ = 2585546652,RPC_DONATIVE__,RPC_GETNAME__,RPC_ABSTRACTWITHBODY__,RPC_ABSTRACTNATIVE__};

Inheritance::Inheritance() : ManagedObject(DummyConstructorParameter::instance()) {
	InheritanceImplementation* _implementation = new InheritanceImplementation();
	_impl = _implementation;
	_impl->_setStub(this);
	_setClassName("Inheritance");
}

Inheritance::Inheritance(DummyConstructorParameter* param) : ManagedObject(param) {
	_setClassName("Inheritance");
}

Inheritance::~Inheritance() {
}



void Inheritance::doNative() {
	InheritanceImplementation* _implementation = static_cast<InheritanceImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_DONATIVE__);

		method.executeWithVoidReturn();
	} else {
		_implementation->doNative();
	}
}

int Inheritance::getCounter() {
	InheritanceImplementation* _implementation = static_cast<InheritanceImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		return _implementation->getCounter();
	}
}

String Inheritance::getName() const {
	InheritanceImplementation* _implementation = static_cast<InheritanceImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETNAME__);

		String _return_getName;
		method.executeWithAsciiReturn(_return_getName);
		return _return_getName;
	} else {
		return _implementation->getName();
	}
}

void Inheritance::abstractWithBody() {
	InheritanceImplementation* _implementation = static_cast<InheritanceImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ABSTRACTWITHBODY__);

		method.executeWithVoidReturn();
	} else {
		_implementation->abstractWithBody();
	}
}

void Inheritance::abstractNative() {
	InheritanceImplementation* _implementation = static_cast<InheritanceImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ABSTRACTNATIVE__);

		method.executeWithVoidReturn();
	} else {
		_implementation->abstractNative();
	}
}

DistributedObjectServant* Inheritance::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* Inheritance::_getImplementationForRead() const {
	return _impl;
}

void Inheritance::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	InheritanceImplementation
 */

InheritanceImplementation::InheritanceImplementation(DummyConstructorParameter* param) : ManagedObjectImplementation(param) {
	_initializeImplementation();
}


InheritanceImplementation::~InheritanceImplementation() {
	InheritanceImplementation::finalize();
}


void InheritanceImplementation::_initializeImplementation() {
	_setClassHelper(InheritanceHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void InheritanceImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<Inheritance*>(stub);
	ManagedObjectImplementation::_setStub(stub);
}

DistributedObjectStub* InheritanceImplementation::_getStub() {
	return _this.get();
}

InheritanceImplementation::operator const Inheritance*() {
	return _this.get();
}

void InheritanceImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void InheritanceImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void InheritanceImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void InheritanceImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void InheritanceImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void InheritanceImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void InheritanceImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void InheritanceImplementation::_serializationHelperMethod() {
	ManagedObjectImplementation::_serializationHelperMethod();

	_setClassName("Inheritance");

}

void InheritanceImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(InheritanceImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool InheritanceImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x74cd987b: //Inheritance.counter
		TypeInfo<int >::parseFromBinaryStream(&counter, stream);
		return true;

	case 0xce8e772a: //Inheritance.name
		TypeInfo<String >::parseFromBinaryStream(&name, stream);
		return true;

	}

	return false;
}

void InheritanceImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = InheritanceImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int InheritanceImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0x74cd987b; //Inheritance.counter
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&counter, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xce8e772a; //Inheritance.name
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&name, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

InheritanceImplementation::InheritanceImplementation() {
	_initializeImplementation();
	// probe/Inheritance.idl():  		counter = 0;
	counter = 0;
	// probe/Inheritance.idl():  		name = "default";
	name = "default";
}

int InheritanceImplementation::getCounter() {
	// probe/Inheritance.idl():  		return counter;
	return counter;
}

String InheritanceImplementation::getName() const{
	// probe/Inheritance.idl():  		return name;
	return name;
}

void InheritanceImplementation::abstractWithBody() {
	// probe/Inheritance.idl():  		counter = counter + 1;
	counter = counter + 1;
}

/*
 *	InheritanceAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


InheritanceAdapter::InheritanceAdapter(Inheritance* obj) : ManagedObjectAdapter(obj) {
}

void InheritanceAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_FINALIZE__:
		{
			
			finalize();
			
		}
		break;
	case RPC_DONATIVE__:
		{
			
			doNative();
			
		}
		break;
	case RPC_GETNAME__:
		{
			
			String _m_res = getName();
			resp->insertAscii(_m_res);
		}
		break;
	case RPC_ABSTRACTWITHBODY__:
		{
			
			abstractWithBody();
			
		}
		break;
	case RPC_ABSTRACTNATIVE__:
		{
			
			abstractNative();
			
		}
		break;
	default:
		ManagedObjectAdapter::invokeMethod(methid, inv);
	}
}

void InheritanceAdapter::finalize() {
	(static_cast<Inheritance*>(stub))->finalize();
}

void InheritanceAdapter::doNative() {
	(static_cast<Inheritance*>(stub))->doNative();
}

String InheritanceAdapter::getName() const {
	return (static_cast<Inheritance*>(stub))->getName();
}

void InheritanceAdapter::abstractWithBody() {
	(static_cast<Inheritance*>(stub))->abstractWithBody();
}

void InheritanceAdapter::abstractNative() {
	(static_cast<Inheritance*>(stub))->abstractNative();
}

/*
 *	InheritanceHelper
 */

InheritanceHelper* InheritanceHelper::staticInitializer = InheritanceHelper::instance();

InheritanceHelper::InheritanceHelper() {
	className = "Inheritance";

	Core::getObjectBroker()->registerClass(className, this);
}

void InheritanceHelper::finalizeHelper() {
	InheritanceHelper::finalize();
}

DistributedObject* InheritanceHelper::instantiateObject() {
	return new Inheritance(DummyConstructorParameter::instance());
}

DistributedObjectServant* InheritanceHelper::instantiateServant() {
	return new InheritanceImplementation();
}

DistributedObjectPOD* InheritanceHelper::instantiatePOD() {
	return new InheritancePOD();
}

DistributedObjectAdapter* InheritanceHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new InheritanceAdapter(static_cast<Inheritance*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	InheritancePOD
 */

InheritancePOD::~InheritancePOD() {
	finalize();
}

InheritancePOD::InheritancePOD(void) {
	_className = "Inheritance";
}


void InheritancePOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = InheritancePOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int InheritancePOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (counter) {
	_nameHashCode = 0x74cd987b; //Inheritance.counter
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&counter.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (name) {
	_nameHashCode = 0xce8e772a; //Inheritance.name
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&name.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool InheritancePOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x74cd987b: //Inheritance.counter
		{
			int _mncounter;
			TypeInfo<int >::parseFromBinaryStream(&_mncounter, stream);
			counter = std::move(_mncounter);
		}
		return true;

	case 0xce8e772a: //Inheritance.name
		{
			String _mnname;
			TypeInfo<String >::parseFromBinaryStream(&_mnname, stream);
			name = std::move(_mnname);
		}
		return true;

	}

	return false;
}

void InheritancePOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(InheritancePOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void InheritancePOD::writeObjectCompact(ObjectOutputStream* stream) {
	ManagedObjectPOD::writeObjectCompact(stream);

	TypeInfo<int >::toBinaryStream(&counter.value(), stream);

	TypeInfo<String >::toBinaryStream(&name.value(), stream);


}

