/*
 *	autogen/probe/Inheritance.h generated by engine3 IDL compiler 0.70
 */

#ifndef INHERITANCE_H_
#define INHERITANCE_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "engine/log/Logger.h"

#include "system/thread/Lockable.h"

#include "engine/core/ManagedObject.h"

namespace probe {

class Inheritance : public ManagedObject {
public:
	Inheritance();

	void doNative();

	int getCounter();

	String getName() const;

	void abstractWithBody();

	void abstractNative();

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	Inheritance(DummyConstructorParameter* param);

	virtual ~Inheritance();

	friend class InheritanceHelper;
};

} // namespace probe

using namespace probe;

namespace probe {

class InheritanceImplementation : public ManagedObjectImplementation, public Logger, public Lockable {
	int counter;

	String name;

public:
	InheritanceImplementation();

	InheritanceImplementation(DummyConstructorParameter* param);

	void finalize();

	void doNative();

	int getCounter();

	String getName() const;

	virtual void abstractWithBody();

	virtual void abstractNative();

	WeakReference<Inheritance*> _this;

	operator const Inheritance*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~InheritanceImplementation();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class Inheritance;
};

class InheritanceAdapter : public ManagedObjectAdapter {
public:
	InheritanceAdapter(Inheritance* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	void finalize();

	void doNative();

	String getName() const;

	void abstractWithBody();

	void abstractNative();

};

class InheritanceHelper : public DistributedObjectClassHelper, public Singleton<InheritanceHelper> {
	static InheritanceHelper* staticInitializer;

public:
	InheritanceHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<InheritanceHelper>;
};

} // namespace probe

using namespace probe;

namespace probe {

class InheritancePOD : public ManagedObjectPOD {
public:
	Optional<int> counter;

	Optional<String> name;

	String _className;
	InheritancePOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~InheritancePOD();

};

} // namespace probe

using namespace probe;

#endif /*INHERITANCEPOD_H_*/
