/*
 *	autogen/probe/Json.cpp generated by engine3 IDL compiler 0.70
 */

#include "Json.h"

/*
 *	JsonStub
 */

const byte Json::CONST_BYTE = 1;

Json::Json(DummyConstructorParameter* param) : ManagedObject(param) {
	_setClassName("Json");
}

Json::~Json() {
}



DistributedObjectServant* Json::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* Json::_getImplementationForRead() const {
	return _impl;
}

void Json::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	JsonImplementation
 */

const byte JsonImplementation::CONST_BYTE = 1;

JsonImplementation::JsonImplementation() : ManagedObjectImplementation() {
	_initializeImplementation();
}

JsonImplementation::JsonImplementation(DummyConstructorParameter* param) : ManagedObjectImplementation(param) {
	_initializeImplementation();
}


JsonImplementation::~JsonImplementation() {
}


void JsonImplementation::finalize() {
}

void JsonImplementation::_initializeImplementation() {
	_setClassHelper(JsonHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void JsonImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<Json*>(stub);
	ManagedObjectImplementation::_setStub(stub);
}

DistributedObjectStub* JsonImplementation::_getStub() {
	return _this.get();
}

JsonImplementation::operator const Json*() {
	return _this.get();
}

void JsonImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void JsonImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void JsonImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void JsonImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void JsonImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void JsonImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void JsonImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void JsonImplementation::_serializationHelperMethod() {
	ManagedObjectImplementation::_serializationHelperMethod();

	_setClassName("Json");

}

void JsonImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(JsonImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool JsonImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x8d69a972: //Json.intField
		TypeInfo<int >::parseFromBinaryStream(&intField, stream);
		return true;

	case 0xaa1b4591: //Json.stringField
		TypeInfo<String >::parseFromBinaryStream(&stringField, stream);
		return true;

	case 0x82d86670: //Json.boolField
		TypeInfo<bool >::parseFromBinaryStream(&boolField, stream);
		return true;

	case 0x9274b726: //Json.longField
		TypeInfo<long long >::parseFromBinaryStream(&longField, stream);
		return true;

	case 0xfb3a872a: //Json.floatField
		TypeInfo<float >::parseFromBinaryStream(&floatField, stream);
		return true;

	case 0x40e7920c: //Json.classField
		TypeInfo<ManagedReference<ManagedObject* > >::parseFromBinaryStream(&classField, stream);
		return true;

	case 0x73a6d694: //Json.derefField
		TypeInfo<ManagedReference<ManagedObject > >::parseFromBinaryStream(&derefField, stream);
		return true;

	case 0x5bc0087f: //Json.weakField
		TypeInfo<ManagedWeakReference<ManagedObject* > >::parseFromBinaryStream(&weakField, stream);
		return true;

	case 0xbec32ef0: //Json.derefWeakField
		TypeInfo<ManagedWeakReference<ManagedObject > >::parseFromBinaryStream(&derefWeakField, stream);
		return true;

	case 0x5bfe4131: //Json.vecPrim
		TypeInfo<Reference<Vector<int>* > >::parseFromBinaryStream(&vecPrim, stream);
		return true;

	case 0x16435e22: //Json.vecClass
		TypeInfo<Reference<Vector<ManagedReference<ManagedObject* > >* > >::parseFromBinaryStream(&vecClass, stream);
		return true;

	case 0x531ff7e: //Json.derefVecPrim
		TypeInfo<Vector<int> >::parseFromBinaryStream(&derefVecPrim, stream);
		return true;

	case 0x3edfda06: //Json.timeField
		TypeInfo<Time >::parseFromBinaryStream(&timeField, stream);
		return true;

	}

	return false;
}

void JsonImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = JsonImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int JsonImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0x8d69a972; //Json.intField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&intField, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xaa1b4591; //Json.stringField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&stringField, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x82d86670; //Json.boolField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<bool >::toBinaryStream(&boolField, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x9274b726; //Json.longField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<long long >::toBinaryStream(&longField, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xfb3a872a; //Json.floatField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&floatField, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x40e7920c; //Json.classField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedReference<ManagedObject* > >::toBinaryStream(&classField, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x73a6d694; //Json.derefField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedReference<ManagedObject > >::toBinaryStream(&derefField, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x5bc0087f; //Json.weakField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedWeakReference<ManagedObject* > >::toBinaryStream(&weakField, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xbec32ef0; //Json.derefWeakField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedWeakReference<ManagedObject > >::toBinaryStream(&derefWeakField, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x5bfe4131; //Json.vecPrim
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Reference<Vector<int>* > >::toBinaryStream(&vecPrim, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x16435e22; //Json.vecClass
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Reference<Vector<ManagedReference<ManagedObject* > >* > >::toBinaryStream(&vecClass, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x531ff7e; //Json.derefVecPrim
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Vector<int> >::toBinaryStream(&derefVecPrim, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x3edfda06; //Json.timeField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Time >::toBinaryStream(&timeField, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

void JsonImplementation::writeJSON(nlohmann::json& j) {
	ManagedObjectImplementation::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
	thisObject["intField"] = intField;

	thisObject["stringField"] = stringField;

	thisObject["boolField"] = boolField;

	thisObject["longField"] = longField;

	thisObject["floatField"] = floatField;

	thisObject["classField"] = classField;

	thisObject["derefField"] = derefField;

	thisObject["weakField"] = weakField;

	thisObject["derefWeakField"] = derefWeakField;

	thisObject["vecPrim"] = vecPrim;

	thisObject["vecClass"] = vecClass;

	thisObject["derefVecPrim"] = derefVecPrim;

	thisObject["timeField"] = timeField;

	j["Json"] = thisObject;
}

/*
 *	JsonAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


JsonAdapter::JsonAdapter(Json* obj) : ManagedObjectAdapter(obj) {
}

void JsonAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	default:
		ManagedObjectAdapter::invokeMethod(methid, inv);
	}
}

/*
 *	JsonHelper
 */

JsonHelper* JsonHelper::staticInitializer = JsonHelper::instance();

JsonHelper::JsonHelper() {
	className = "Json";

	Core::getObjectBroker()->registerClass(className, this);
}

void JsonHelper::finalizeHelper() {
	JsonHelper::finalize();
}

DistributedObject* JsonHelper::instantiateObject() {
	return new Json(DummyConstructorParameter::instance());
}

DistributedObjectServant* JsonHelper::instantiateServant() {
	return new JsonImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* JsonHelper::instantiatePOD() {
	return new JsonPOD();
}

DistributedObjectAdapter* JsonHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new JsonAdapter(static_cast<Json*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	JsonPOD
 */

JsonPOD::~JsonPOD() {
}

JsonPOD::JsonPOD(void) {
	_className = "Json";
}


void JsonPOD::writeJSON(nlohmann::json& j) {
	ManagedObjectPOD::writeJSON(j);

	nlohmann::json thisObject = nlohmann::json::object();
	if (intField)
		thisObject["intField"] = intField.value();

	if (stringField)
		thisObject["stringField"] = stringField.value();

	if (boolField)
		thisObject["boolField"] = boolField.value();

	if (longField)
		thisObject["longField"] = longField.value();

	if (floatField)
		thisObject["floatField"] = floatField.value();

	if (classField)
		thisObject["classField"] = classField.value();

	if (derefField)
		thisObject["derefField"] = derefField.value();

	if (weakField)
		thisObject["weakField"] = weakField.value();

	if (derefWeakField)
		thisObject["derefWeakField"] = derefWeakField.value();

	if (vecPrim)
		thisObject["vecPrim"] = vecPrim.value();

	if (vecClass)
		thisObject["vecClass"] = vecClass.value();

	if (derefVecPrim)
		thisObject["derefVecPrim"] = derefVecPrim.value();

	if (timeField)
		thisObject["timeField"] = timeField.value();

	j["Json"] = thisObject;
}


void JsonPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = JsonPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int JsonPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (intField) {
	_nameHashCode = 0x8d69a972; //Json.intField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&intField.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (stringField) {
	_nameHashCode = 0xaa1b4591; //Json.stringField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&stringField.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (boolField) {
	_nameHashCode = 0x82d86670; //Json.boolField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<bool >::toBinaryStream(&boolField.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (longField) {
	_nameHashCode = 0x9274b726; //Json.longField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<long long >::toBinaryStream(&longField.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (floatField) {
	_nameHashCode = 0xfb3a872a; //Json.floatField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<float >::toBinaryStream(&floatField.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (classField) {
	_nameHashCode = 0x40e7920c; //Json.classField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedReference<ManagedObjectPOD* > >::toBinaryStream(&classField.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (derefField) {
	_nameHashCode = 0x73a6d694; //Json.derefField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedReference<ManagedObject > >::toBinaryStream(&derefField.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (weakField) {
	_nameHashCode = 0x5bc0087f; //Json.weakField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedWeakReference<ManagedObjectPOD* > >::toBinaryStream(&weakField.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (derefWeakField) {
	_nameHashCode = 0xbec32ef0; //Json.derefWeakField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedWeakReference<ManagedObject > >::toBinaryStream(&derefWeakField.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (vecPrim) {
	_nameHashCode = 0x5bfe4131; //Json.vecPrim
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Reference<Vector<int>* > >::toBinaryStream(&vecPrim.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (vecClass) {
	_nameHashCode = 0x16435e22; //Json.vecClass
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Reference<Vector<ManagedReference<ManagedObjectPOD* > >* > >::toBinaryStream(&vecClass.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (derefVecPrim) {
	_nameHashCode = 0x531ff7e; //Json.derefVecPrim
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Vector<int> >::toBinaryStream(&derefVecPrim.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (timeField) {
	_nameHashCode = 0x3edfda06; //Json.timeField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Time >::toBinaryStream(&timeField.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool JsonPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x8d69a972: //Json.intField
		{
			int _mnintField;
			TypeInfo<int >::parseFromBinaryStream(&_mnintField, stream);
			intField = std::move(_mnintField);
		}
		return true;

	case 0xaa1b4591: //Json.stringField
		{
			String _mnstringField;
			TypeInfo<String >::parseFromBinaryStream(&_mnstringField, stream);
			stringField = std::move(_mnstringField);
		}
		return true;

	case 0x82d86670: //Json.boolField
		{
			bool _mnboolField;
			TypeInfo<bool >::parseFromBinaryStream(&_mnboolField, stream);
			boolField = std::move(_mnboolField);
		}
		return true;

	case 0x9274b726: //Json.longField
		{
			long long _mnlongField;
			TypeInfo<long long >::parseFromBinaryStream(&_mnlongField, stream);
			longField = std::move(_mnlongField);
		}
		return true;

	case 0xfb3a872a: //Json.floatField
		{
			float _mnfloatField;
			TypeInfo<float >::parseFromBinaryStream(&_mnfloatField, stream);
			floatField = std::move(_mnfloatField);
		}
		return true;

	case 0x40e7920c: //Json.classField
		{
			ManagedReference<ManagedObjectPOD* > _mnclassField;
			TypeInfo<ManagedReference<ManagedObjectPOD* > >::parseFromBinaryStream(&_mnclassField, stream);
			classField = std::move(_mnclassField);
		}
		return true;

	case 0x73a6d694: //Json.derefField
		{
			ManagedReference<ManagedObject > _mnderefField;
			TypeInfo<ManagedReference<ManagedObject > >::parseFromBinaryStream(&_mnderefField, stream);
			derefField = std::move(_mnderefField);
		}
		return true;

	case 0x5bc0087f: //Json.weakField
		{
			ManagedWeakReference<ManagedObjectPOD* > _mnweakField;
			TypeInfo<ManagedWeakReference<ManagedObjectPOD* > >::parseFromBinaryStream(&_mnweakField, stream);
			weakField = std::move(_mnweakField);
		}
		return true;

	case 0xbec32ef0: //Json.derefWeakField
		{
			ManagedWeakReference<ManagedObject > _mnderefWeakField;
			TypeInfo<ManagedWeakReference<ManagedObject > >::parseFromBinaryStream(&_mnderefWeakField, stream);
			derefWeakField = std::move(_mnderefWeakField);
		}
		return true;

	case 0x5bfe4131: //Json.vecPrim
		{
			Reference<Vector<int>* > _mnvecPrim;
			TypeInfo<Reference<Vector<int>* > >::parseFromBinaryStream(&_mnvecPrim, stream);
			vecPrim = std::move(_mnvecPrim);
		}
		return true;

	case 0x16435e22: //Json.vecClass
		{
			Reference<Vector<ManagedReference<ManagedObjectPOD* > >* > _mnvecClass;
			TypeInfo<Reference<Vector<ManagedReference<ManagedObjectPOD* > >* > >::parseFromBinaryStream(&_mnvecClass, stream);
			vecClass = std::move(_mnvecClass);
		}
		return true;

	case 0x531ff7e: //Json.derefVecPrim
		{
			Vector<int> _mnderefVecPrim;
			TypeInfo<Vector<int> >::parseFromBinaryStream(&_mnderefVecPrim, stream);
			derefVecPrim = std::move(_mnderefVecPrim);
		}
		return true;

	case 0x3edfda06: //Json.timeField
		{
			Time _mntimeField;
			TypeInfo<Time >::parseFromBinaryStream(&_mntimeField, stream);
			timeField = std::move(_mntimeField);
		}
		return true;

	}

	return false;
}

void JsonPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(JsonPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void JsonPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ManagedObjectPOD::writeObjectCompact(stream);

	TypeInfo<int >::toBinaryStream(&intField.value(), stream);

	TypeInfo<String >::toBinaryStream(&stringField.value(), stream);

	TypeInfo<bool >::toBinaryStream(&boolField.value(), stream);

	TypeInfo<long long >::toBinaryStream(&longField.value(), stream);

	TypeInfo<float >::toBinaryStream(&floatField.value(), stream);

	TypeInfo<ManagedReference<ManagedObjectPOD* > >::toBinaryStream(&classField.value(), stream);

	TypeInfo<ManagedReference<ManagedObject > >::toBinaryStream(&derefField.value(), stream);

	TypeInfo<ManagedWeakReference<ManagedObjectPOD* > >::toBinaryStream(&weakField.value(), stream);

	TypeInfo<ManagedWeakReference<ManagedObject > >::toBinaryStream(&derefWeakField.value(), stream);

	TypeInfo<Reference<Vector<int>* > >::toBinaryStream(&vecPrim.value(), stream);

	TypeInfo<Reference<Vector<ManagedReference<ManagedObjectPOD* > >* > >::toBinaryStream(&vecClass.value(), stream);

	TypeInfo<Vector<int> >::toBinaryStream(&derefVecPrim.value(), stream);

	TypeInfo<Time >::toBinaryStream(&timeField.value(), stream);


}

