/*
 *	autogen/probe/LocalVar.h generated by engine3 IDL compiler 0.70
 */

#ifndef LOCALVAR_H_
#define LOCALVAR_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "engine/core/ManagedObject.h"

namespace probe {

class LocalVar : public ManagedObject {
public:
	void managedClassLocal();

	void managedLocalThenAccess();

	void primitiveLocal();

	void multipleManagedLocals();

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	LocalVar(DummyConstructorParameter* param);

	virtual ~LocalVar();

	friend class LocalVarHelper;
};

} // namespace probe

using namespace probe;

namespace probe {

class LocalVarImplementation : public ManagedObjectImplementation {
	ManagedReference<ManagedObject* > classField;

	String strField;

public:
	LocalVarImplementation();
	LocalVarImplementation(DummyConstructorParameter* param);

	void managedClassLocal();

	void managedLocalThenAccess();

	void primitiveLocal();

	void multipleManagedLocals();

	WeakReference<LocalVar*> _this;

	operator const LocalVar*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~LocalVarImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class LocalVar;
};

class LocalVarAdapter : public ManagedObjectAdapter {
public:
	LocalVarAdapter(LocalVar* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

};

class LocalVarHelper : public DistributedObjectClassHelper, public Singleton<LocalVarHelper> {
	static LocalVarHelper* staticInitializer;

public:
	LocalVarHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<LocalVarHelper>;
};

} // namespace probe

using namespace probe;

namespace probe {

class LocalVarPOD : public ManagedObjectPOD {
public:
	Optional<ManagedReference<ManagedObjectPOD* >> classField;

	Optional<String> strField;

	String _className;
	LocalVarPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~LocalVarPOD();

};

} // namespace probe

using namespace probe;

#endif /*LOCALVARPOD_H_*/
