/*
 *	autogen/probe/LocalVar.cpp generated by engine3 IDL compiler 0.70
 */

#include "LocalVar.h"

/*
 *	LocalVarStub
 */

LocalVar::LocalVar(DummyConstructorParameter* param) : ManagedObject(param) {
	_setClassName("LocalVar");
}

LocalVar::~LocalVar() {
}



void LocalVar::managedClassLocal() {
	LocalVarImplementation* _implementation = static_cast<LocalVarImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->managedClassLocal();
	}
}

void LocalVar::managedLocalThenAccess() {
	LocalVarImplementation* _implementation = static_cast<LocalVarImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->managedLocalThenAccess();
	}
}

void LocalVar::primitiveLocal() {
	LocalVarImplementation* _implementation = static_cast<LocalVarImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->primitiveLocal();
	}
}

void LocalVar::multipleManagedLocals() {
	LocalVarImplementation* _implementation = static_cast<LocalVarImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->multipleManagedLocals();
	}
}

DistributedObjectServant* LocalVar::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* LocalVar::_getImplementationForRead() const {
	return _impl;
}

void LocalVar::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	LocalVarImplementation
 */

LocalVarImplementation::LocalVarImplementation() : ManagedObjectImplementation() {
	_initializeImplementation();
}

LocalVarImplementation::LocalVarImplementation(DummyConstructorParameter* param) : ManagedObjectImplementation(param) {
	_initializeImplementation();
}


LocalVarImplementation::~LocalVarImplementation() {
}


void LocalVarImplementation::finalize() {
}

void LocalVarImplementation::_initializeImplementation() {
	_setClassHelper(LocalVarHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void LocalVarImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<LocalVar*>(stub);
	ManagedObjectImplementation::_setStub(stub);
}

DistributedObjectStub* LocalVarImplementation::_getStub() {
	return _this.get();
}

LocalVarImplementation::operator const LocalVar*() {
	return _this.get();
}

void LocalVarImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void LocalVarImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void LocalVarImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void LocalVarImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void LocalVarImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void LocalVarImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void LocalVarImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void LocalVarImplementation::_serializationHelperMethod() {
	ManagedObjectImplementation::_serializationHelperMethod();

	_setClassName("LocalVar");

}

void LocalVarImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(LocalVarImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool LocalVarImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x4f8ca4b6: //LocalVar.classField
		TypeInfo<ManagedReference<ManagedObject* > >::parseFromBinaryStream(&classField, stream);
		return true;

	case 0x739c3263: //LocalVar.strField
		TypeInfo<String >::parseFromBinaryStream(&strField, stream);
		return true;

	}

	return false;
}

void LocalVarImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = LocalVarImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int LocalVarImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0x4f8ca4b6; //LocalVar.classField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedReference<ManagedObject* > >::toBinaryStream(&classField, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x739c3263; //LocalVar.strField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&strField, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

void LocalVarImplementation::managedClassLocal() {
	// probe/LocalVar.idl():  		ManagedObject local = classField;
	ManagedReference<ManagedObject* > local = classField;
}

void LocalVarImplementation::managedLocalThenAccess() {
	// probe/LocalVar.idl():  		ManagedObject local = classField;
	ManagedReference<ManagedObject* > local = classField;
	// probe/LocalVar.idl():  		local.updateForWrite();
	local->updateForWrite();
	// probe/LocalVar.idl():  		local.lock();
	local->lock();
}

void LocalVarImplementation::primitiveLocal() {
	// probe/LocalVar.idl():  		string local = "hello";
	String local = "hello";
	// probe/LocalVar.idl():  		strField = local;
	strField = local;
}

void LocalVarImplementation::multipleManagedLocals() {
	// probe/LocalVar.idl():  		ManagedObject a = classField;
	ManagedReference<ManagedObject* > a = classField;
	// probe/LocalVar.idl():  		ManagedObject b = classField;
	ManagedReference<ManagedObject* > b = classField;
	// probe/LocalVar.idl():  		a.updateForWrite();
	a->updateForWrite();
	// probe/LocalVar.idl():  		b.lock();
	b->lock();
}

/*
 *	LocalVarAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


LocalVarAdapter::LocalVarAdapter(LocalVar* obj) : ManagedObjectAdapter(obj) {
}

void LocalVarAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	default:
		ManagedObjectAdapter::invokeMethod(methid, inv);
	}
}

/*
 *	LocalVarHelper
 */

LocalVarHelper* LocalVarHelper::staticInitializer = LocalVarHelper::instance();

LocalVarHelper::LocalVarHelper() {
	className = "LocalVar";

	Core::getObjectBroker()->registerClass(className, this);
}

void LocalVarHelper::finalizeHelper() {
	LocalVarHelper::finalize();
}

DistributedObject* LocalVarHelper::instantiateObject() {
	return new LocalVar(DummyConstructorParameter::instance());
}

DistributedObjectServant* LocalVarHelper::instantiateServant() {
	return new LocalVarImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* LocalVarHelper::instantiatePOD() {
	return new LocalVarPOD();
}

DistributedObjectAdapter* LocalVarHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new LocalVarAdapter(static_cast<LocalVar*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	LocalVarPOD
 */

LocalVarPOD::~LocalVarPOD() {
}

LocalVarPOD::LocalVarPOD(void) {
	_className = "LocalVar";
}


void LocalVarPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = LocalVarPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int LocalVarPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (classField) {
	_nameHashCode = 0x4f8ca4b6; //LocalVar.classField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedReference<ManagedObjectPOD* > >::toBinaryStream(&classField.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (strField) {
	_nameHashCode = 0x739c3263; //LocalVar.strField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<String >::toBinaryStream(&strField.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool LocalVarPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x4f8ca4b6: //LocalVar.classField
		{
			ManagedReference<ManagedObjectPOD* > _mnclassField;
			TypeInfo<ManagedReference<ManagedObjectPOD* > >::parseFromBinaryStream(&_mnclassField, stream);
			classField = std::move(_mnclassField);
		}
		return true;

	case 0x739c3263: //LocalVar.strField
		{
			String _mnstrField;
			TypeInfo<String >::parseFromBinaryStream(&_mnstrField, stream);
			strField = std::move(_mnstrField);
		}
		return true;

	}

	return false;
}

void LocalVarPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(LocalVarPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void LocalVarPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ManagedObjectPOD::writeObjectCompact(stream);

	TypeInfo<ManagedReference<ManagedObjectPOD* > >::toBinaryStream(&classField.value(), stream);

	TypeInfo<String >::toBinaryStream(&strField.value(), stream);


}

