/*
 *	autogen/probe/Locking.cpp generated by engine3 IDL compiler 0.70
 */

#include "Locking.h"

/*
 *	LockingStub
 */

enum {RPC_PLAIN__INT_ = 49071539,RPC_PRELOCKEDONLY__,RPC_ARG1ONLYLOCKED__MANAGEDOBJECT_,RPC_ARG2ONLYLOCKED__INT_MANAGEDOBJECT_,RPC_PREANDARG1__MANAGEDOBJECT_,RPC_PREANDARG1ANDARG2__MANAGEDOBJECT_MANAGEDOBJECT_,RPC_READPLAIN__,RPC_DIRTYPLAIN__,RPC_READPRELOCKED__INT_,RPC_DIRTYARG1LOCKED__MANAGEDOBJECT_,};

Locking::Locking(DummyConstructorParameter* param) : ManagedObject(param) {
	_setClassName("Locking");
}

Locking::~Locking() {
}



void Locking::plain(int x) {
	LockingImplementation* _implementation = static_cast<LockingImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_PLAIN__INT_);
		method.addSignedIntParameter(x);

		method.executeWithVoidReturn();
	} else {
		_implementation->plain(x);
	}
}

void Locking::preLockedOnly() {
	LockingImplementation* _implementation = static_cast<LockingImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_PRELOCKEDONLY__);

		method.executeWithVoidReturn();
	} else {
		assert(this->isLockedByCurrentThread());
		_implementation->preLockedOnly();
	}
}

void Locking::arg1OnlyLocked(ManagedObject* obj) {
	LockingImplementation* _implementation = static_cast<LockingImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ARG1ONLYLOCKED__MANAGEDOBJECT_);
		method.addObjectParameter(obj);

		method.executeWithVoidReturn();
	} else {
		assert((obj == NULL) || obj->isLockedByCurrentThread());
		_implementation->arg1OnlyLocked(obj);
	}
}

void Locking::arg2OnlyLocked(int x, ManagedObject* obj) {
	LockingImplementation* _implementation = static_cast<LockingImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ARG2ONLYLOCKED__INT_MANAGEDOBJECT_);
		method.addSignedIntParameter(x);
		method.addObjectParameter(obj);

		method.executeWithVoidReturn();
	} else {
		assert((obj == NULL) || obj->isLockedByCurrentThread());
		_implementation->arg2OnlyLocked(x, obj);
	}
}

void Locking::preAndArg1(ManagedObject* obj) {
	LockingImplementation* _implementation = static_cast<LockingImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_PREANDARG1__MANAGEDOBJECT_);
		method.addObjectParameter(obj);

		method.executeWithVoidReturn();
	} else {
		assert(this->isLockedByCurrentThread());
		assert((obj == NULL) || obj->isLockedByCurrentThread());
		_implementation->preAndArg1(obj);
	}
}

void Locking::preAndArg1AndArg2(ManagedObject* a, ManagedObject* b) {
	LockingImplementation* _implementation = static_cast<LockingImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_PREANDARG1ANDARG2__MANAGEDOBJECT_MANAGEDOBJECT_);
		method.addObjectParameter(a);
		method.addObjectParameter(b);

		method.executeWithVoidReturn();
	} else {
		assert(this->isLockedByCurrentThread());
		assert((a == NULL) || a->isLockedByCurrentThread());
		assert((b == NULL) || b->isLockedByCurrentThread());
		_implementation->preAndArg1AndArg2(a, b);
	}
}

int Locking::readPlain() const {
	LockingImplementation* _implementation = static_cast<LockingImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_READPLAIN__);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->readPlain();
	}
}

int Locking::dirtyPlain() {
	LockingImplementation* _implementation = static_cast<LockingImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_DIRTYPLAIN__);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->dirtyPlain();
	}
}

int Locking::readPreLocked(int x) const {
	LockingImplementation* _implementation = static_cast<LockingImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_READPRELOCKED__INT_);
		method.addSignedIntParameter(x);

		return method.executeWithSignedIntReturn();
	} else {
		assert(this->isLockedByCurrentThread());
		return _implementation->readPreLocked(x);
	}
}

void Locking::dirtyArg1Locked(ManagedObject* obj) {
	LockingImplementation* _implementation = static_cast<LockingImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_DIRTYARG1LOCKED__MANAGEDOBJECT_);
		method.addObjectParameter(obj);

		method.executeWithVoidReturn();
	} else {
		assert((obj == NULL) || obj->isLockedByCurrentThread());
		_implementation->dirtyArg1Locked(obj);
	}
}

void Locking::localPreLocked(int x) {
	LockingImplementation* _implementation = static_cast<LockingImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		assert(this->isLockedByCurrentThread());
		_implementation->localPreLocked(x);
	}
}

int Locking::localDirty() {
	LockingImplementation* _implementation = static_cast<LockingImplementation*>(_getImplementationForRead());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		return _implementation->localDirty();
	}
}

DistributedObjectServant* Locking::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* Locking::_getImplementationForRead() const {
	return _impl;
}

void Locking::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	LockingImplementation
 */

LockingImplementation::LockingImplementation() : ManagedObjectImplementation() {
	_initializeImplementation();
}

LockingImplementation::LockingImplementation(DummyConstructorParameter* param) : ManagedObjectImplementation(param) {
	_initializeImplementation();
}


LockingImplementation::~LockingImplementation() {
}


void LockingImplementation::finalize() {
}

void LockingImplementation::_initializeImplementation() {
	_setClassHelper(LockingHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void LockingImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<Locking*>(stub);
	ManagedObjectImplementation::_setStub(stub);
}

DistributedObjectStub* LockingImplementation::_getStub() {
	return _this.get();
}

LockingImplementation::operator const Locking*() {
	return _this.get();
}

void LockingImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void LockingImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void LockingImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void LockingImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void LockingImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void LockingImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void LockingImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void LockingImplementation::_serializationHelperMethod() {
	ManagedObjectImplementation::_serializationHelperMethod();

	_setClassName("Locking");

}

void LockingImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(LockingImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool LockingImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void LockingImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = LockingImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int LockingImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

void LockingImplementation::localPreLocked(int x) {
}

int LockingImplementation::localDirty() {
	// probe/Locking.idl():  		return 1;
	return 1;
}

/*
 *	LockingAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


LockingAdapter::LockingAdapter(Locking* obj) : ManagedObjectAdapter(obj) {
}

void LockingAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_PLAIN__INT_:
		{
			int x = inv->getSignedIntParameter();
			
			plain(x);
			
		}
		break;
	case RPC_PRELOCKEDONLY__:
		{
			
			preLockedOnly();
			
		}
		break;
	case RPC_ARG1ONLYLOCKED__MANAGEDOBJECT_:
		{
			ManagedObject* obj = static_cast<ManagedObject*>(inv->getObjectParameter());
			
			arg1OnlyLocked(obj);
			
		}
		break;
	case RPC_ARG2ONLYLOCKED__INT_MANAGEDOBJECT_:
		{
			int x = inv->getSignedIntParameter();
			ManagedObject* obj = static_cast<ManagedObject*>(inv->getObjectParameter());
			
			arg2OnlyLocked(x, obj);
			
		}
		break;
	case RPC_PREANDARG1__MANAGEDOBJECT_:
		{
			ManagedObject* obj = static_cast<ManagedObject*>(inv->getObjectParameter());
			
			preAndArg1(obj);
			
		}
		break;
	case RPC_PREANDARG1ANDARG2__MANAGEDOBJECT_MANAGEDOBJECT_:
		{
			ManagedObject* a = static_cast<ManagedObject*>(inv->getObjectParameter());
			ManagedObject* b = static_cast<ManagedObject*>(inv->getObjectParameter());
			
			preAndArg1AndArg2(a, b);
			
		}
		break;
	case RPC_READPLAIN__:
		{
			
			int _m_res = readPlain();
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_DIRTYPLAIN__:
		{
			
			int _m_res = dirtyPlain();
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_READPRELOCKED__INT_:
		{
			int x = inv->getSignedIntParameter();
			
			int _m_res = readPreLocked(x);
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_DIRTYARG1LOCKED__MANAGEDOBJECT_:
		{
			ManagedObject* obj = static_cast<ManagedObject*>(inv->getObjectParameter());
			
			dirtyArg1Locked(obj);
			
		}
		break;
	default:
		ManagedObjectAdapter::invokeMethod(methid, inv);
	}
}

void LockingAdapter::plain(int x) {
	(static_cast<Locking*>(stub))->plain(x);
}

void LockingAdapter::preLockedOnly() {
	(static_cast<Locking*>(stub))->preLockedOnly();
}

void LockingAdapter::arg1OnlyLocked(ManagedObject* obj) {
	(static_cast<Locking*>(stub))->arg1OnlyLocked(obj);
}

void LockingAdapter::arg2OnlyLocked(int x, ManagedObject* obj) {
	(static_cast<Locking*>(stub))->arg2OnlyLocked(x, obj);
}

void LockingAdapter::preAndArg1(ManagedObject* obj) {
	(static_cast<Locking*>(stub))->preAndArg1(obj);
}

void LockingAdapter::preAndArg1AndArg2(ManagedObject* a, ManagedObject* b) {
	(static_cast<Locking*>(stub))->preAndArg1AndArg2(a, b);
}

int LockingAdapter::readPlain() const {
	return (static_cast<Locking*>(stub))->readPlain();
}

int LockingAdapter::dirtyPlain() {
	return (static_cast<Locking*>(stub))->dirtyPlain();
}

int LockingAdapter::readPreLocked(int x) const {
	return (static_cast<Locking*>(stub))->readPreLocked(x);
}

void LockingAdapter::dirtyArg1Locked(ManagedObject* obj) {
	(static_cast<Locking*>(stub))->dirtyArg1Locked(obj);
}

/*
 *	LockingHelper
 */

LockingHelper* LockingHelper::staticInitializer = LockingHelper::instance();

LockingHelper::LockingHelper() {
	className = "Locking";

	Core::getObjectBroker()->registerClass(className, this);
}

void LockingHelper::finalizeHelper() {
	LockingHelper::finalize();
}

DistributedObject* LockingHelper::instantiateObject() {
	return new Locking(DummyConstructorParameter::instance());
}

DistributedObjectServant* LockingHelper::instantiateServant() {
	return new LockingImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* LockingHelper::instantiatePOD() {
	return new LockingPOD();
}

DistributedObjectAdapter* LockingHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new LockingAdapter(static_cast<Locking*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	LockingPOD
 */

LockingPOD::~LockingPOD() {
}

LockingPOD::LockingPOD(void) {
	_className = "Locking";
}


void LockingPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = LockingPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int LockingPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

bool LockingPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void LockingPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(LockingPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void LockingPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ManagedObjectPOD::writeObjectCompact(stream);


}

