/*
 *	autogen/probe/Locking.h generated by engine3 IDL compiler 0.70
 */

#ifndef LOCKING_H_
#define LOCKING_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "engine/core/ManagedObject.h"

namespace probe {

class Locking : public ManagedObject {
public:
	void plain(int x);

	void preLockedOnly();

	void arg1OnlyLocked(ManagedObject* obj);

	void arg2OnlyLocked(int x, ManagedObject* obj);

	void preAndArg1(ManagedObject* obj);

	void preAndArg1AndArg2(ManagedObject* a, ManagedObject* b);

	int readPlain() const;

	int dirtyPlain();

	int readPreLocked(int x) const;

	void dirtyArg1Locked(ManagedObject* obj);

	void localPreLocked(int x);

	int localDirty();

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	Locking(DummyConstructorParameter* param);

	virtual ~Locking();

	friend class LockingHelper;
};

} // namespace probe

using namespace probe;

namespace probe {

class LockingImplementation : public ManagedObjectImplementation {

public:
	LockingImplementation();
	LockingImplementation(DummyConstructorParameter* param);

	void plain(int x);

	void preLockedOnly();

	void arg1OnlyLocked(ManagedObject* obj);

	void arg2OnlyLocked(int x, ManagedObject* obj);

	void preAndArg1(ManagedObject* obj);

	void preAndArg1AndArg2(ManagedObject* a, ManagedObject* b);

	int readPlain() const;

	int dirtyPlain();

	int readPreLocked(int x) const;

	void dirtyArg1Locked(ManagedObject* obj);

	void localPreLocked(int x);

	int localDirty();

	WeakReference<Locking*> _this;

	operator const Locking*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~LockingImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class Locking;
};

class LockingAdapter : public ManagedObjectAdapter {
public:
	LockingAdapter(Locking* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	void plain(int x);

	void preLockedOnly();

	void arg1OnlyLocked(ManagedObject* obj);

	void arg2OnlyLocked(int x, ManagedObject* obj);

	void preAndArg1(ManagedObject* obj);

	void preAndArg1AndArg2(ManagedObject* a, ManagedObject* b);

	int readPlain() const;

	int dirtyPlain();

	int readPreLocked(int x) const;

	void dirtyArg1Locked(ManagedObject* obj);

};

class LockingHelper : public DistributedObjectClassHelper, public Singleton<LockingHelper> {
	static LockingHelper* staticInitializer;

public:
	LockingHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<LockingHelper>;
};

} // namespace probe

using namespace probe;

namespace probe {

class LockingPOD : public ManagedObjectPOD {
public:

	LockingPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~LockingPOD();

};

} // namespace probe

using namespace probe;

#endif /*LOCKINGPOD_H_*/
