/*
 *	autogen/probe/NativeCtor.cpp generated by engine3 IDL compiler 0.70
 */

#include "NativeCtor.h"

/*
 *	NativeCtorStub
 */

enum {RPC_GETVALUE__ = 3307767849};

NativeCtor::NativeCtor() : ManagedObject(DummyConstructorParameter::instance()) {
	NativeCtorImplementation* _implementation = new NativeCtorImplementation();
	_impl = _implementation;
	_implementation->_initializeImplementation();
	_impl->_setStub(this);
	_setClassName("NativeCtor");
}

NativeCtor::NativeCtor(DummyConstructorParameter* param) : ManagedObject(param) {
	_setClassName("NativeCtor");
}

NativeCtor::~NativeCtor() {
}



int NativeCtor::getValue() {
	NativeCtorImplementation* _implementation = static_cast<NativeCtorImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETVALUE__);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->getValue();
	}
}

DistributedObjectServant* NativeCtor::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* NativeCtor::_getImplementationForRead() const {
	return _impl;
}

void NativeCtor::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	NativeCtorImplementation
 */

NativeCtorImplementation::NativeCtorImplementation(DummyConstructorParameter* param) : ManagedObjectImplementation(param) {
	_initializeImplementation();
}


NativeCtorImplementation::~NativeCtorImplementation() {
}


void NativeCtorImplementation::finalize() {
}

void NativeCtorImplementation::_initializeImplementation() {
	_setClassHelper(NativeCtorHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void NativeCtorImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<NativeCtor*>(stub);
	ManagedObjectImplementation::_setStub(stub);
}

DistributedObjectStub* NativeCtorImplementation::_getStub() {
	return _this.get();
}

NativeCtorImplementation::operator const NativeCtor*() {
	return _this.get();
}

void NativeCtorImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void NativeCtorImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void NativeCtorImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void NativeCtorImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void NativeCtorImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void NativeCtorImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void NativeCtorImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void NativeCtorImplementation::_serializationHelperMethod() {
	ManagedObjectImplementation::_serializationHelperMethod();

	_setClassName("NativeCtor");

}

void NativeCtorImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(NativeCtorImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool NativeCtorImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void NativeCtorImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = NativeCtorImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int NativeCtorImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

int NativeCtorImplementation::getValue() {
	// probe/NativeCtor.idl():  		return 0;
	return 0;
}

/*
 *	NativeCtorAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


NativeCtorAdapter::NativeCtorAdapter(NativeCtor* obj) : ManagedObjectAdapter(obj) {
}

void NativeCtorAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_GETVALUE__:
		{
			
			int _m_res = getValue();
			resp->insertSignedInt(_m_res);
		}
		break;
	default:
		ManagedObjectAdapter::invokeMethod(methid, inv);
	}
}

int NativeCtorAdapter::getValue() {
	return (static_cast<NativeCtor*>(stub))->getValue();
}

/*
 *	NativeCtorHelper
 */

NativeCtorHelper* NativeCtorHelper::staticInitializer = NativeCtorHelper::instance();

NativeCtorHelper::NativeCtorHelper() {
	className = "NativeCtor";

	Core::getObjectBroker()->registerClass(className, this);
}

void NativeCtorHelper::finalizeHelper() {
	NativeCtorHelper::finalize();
}

DistributedObject* NativeCtorHelper::instantiateObject() {
	return new NativeCtor(DummyConstructorParameter::instance());
}

DistributedObjectServant* NativeCtorHelper::instantiateServant() {
	return new NativeCtorImplementation();
}

DistributedObjectPOD* NativeCtorHelper::instantiatePOD() {
	return new NativeCtorPOD();
}

DistributedObjectAdapter* NativeCtorHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new NativeCtorAdapter(static_cast<NativeCtor*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	NativeCtorPOD
 */

NativeCtorPOD::~NativeCtorPOD() {
}

NativeCtorPOD::NativeCtorPOD(void) {
	_className = "NativeCtor";
}


void NativeCtorPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = NativeCtorPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int NativeCtorPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

bool NativeCtorPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void NativeCtorPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(NativeCtorPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void NativeCtorPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ManagedObjectPOD::writeObjectCompact(stream);


}

