/*
 *	autogen/probe/NestedGenerics.h generated by engine3 IDL compiler 0.70
 */

#ifndef NESTEDGENERICS_H_
#define NESTEDGENERICS_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "engine/core/ManagedObject.h"

#include "system/util/Vector.h"

#include "system/util/VectorMap.h"

#include "system/lang/ref/Reference.h"

namespace probe {

class NestedGenerics : public ManagedObject {
public:
	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	NestedGenerics(DummyConstructorParameter* param);

	virtual ~NestedGenerics();

	friend class NestedGenericsHelper;
};

} // namespace probe

using namespace probe;

namespace probe {

class NestedGenericsImplementation : public ManagedObjectImplementation {
	Vector<unsigned long long> primitiveVector;

	Reference<Reference<ManagedReference<ManagedObject* > > > refToManaged;

	VectorMap<int, Reference<ManagedReference<ManagedObject* > > > mapWithRef;

	Reference<Reference<Vector<int>*> > refToVector;

	Reference<Reference<Vector<Reference<ManagedReference<ManagedObject* > > >*> > threeDeep;

public:
	NestedGenericsImplementation();
	NestedGenericsImplementation(DummyConstructorParameter* param);

	WeakReference<NestedGenerics*> _this;

	operator const NestedGenerics*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~NestedGenericsImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class NestedGenerics;
};

class NestedGenericsAdapter : public ManagedObjectAdapter {
public:
	NestedGenericsAdapter(NestedGenerics* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

};

class NestedGenericsHelper : public DistributedObjectClassHelper, public Singleton<NestedGenericsHelper> {
	static NestedGenericsHelper* staticInitializer;

public:
	NestedGenericsHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<NestedGenericsHelper>;
};

} // namespace probe

using namespace probe;

namespace probe {

class NestedGenericsPOD : public ManagedObjectPOD {
public:
	Optional<Vector<unsigned long long>> primitiveVector;

	Optional<Reference<Reference<ManagedReference<ManagedObjectPOD* > > >> refToManaged;

	Optional<VectorMap<int, Reference<ManagedReference<ManagedObjectPOD* > > >> mapWithRef;

	Optional<Reference<Reference<Vector<int>*> >> refToVector;

	Optional<Reference<Reference<Vector<Reference<ManagedReference<ManagedObjectPOD* > > >*> >> threeDeep;

	String _className;
	NestedGenericsPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~NestedGenericsPOD();

};

} // namespace probe

using namespace probe;

#endif /*NESTEDGENERICSPOD_H_*/
