/*
 *	autogen/probe/NestedGenerics.cpp generated by engine3 IDL compiler 0.70
 */

#include "NestedGenerics.h"

/*
 *	NestedGenericsStub
 */

NestedGenerics::NestedGenerics(DummyConstructorParameter* param) : ManagedObject(param) {
	_setClassName("NestedGenerics");
}

NestedGenerics::~NestedGenerics() {
}



DistributedObjectServant* NestedGenerics::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* NestedGenerics::_getImplementationForRead() const {
	return _impl;
}

void NestedGenerics::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	NestedGenericsImplementation
 */

NestedGenericsImplementation::NestedGenericsImplementation() : ManagedObjectImplementation() {
	_initializeImplementation();
}

NestedGenericsImplementation::NestedGenericsImplementation(DummyConstructorParameter* param) : ManagedObjectImplementation(param) {
	_initializeImplementation();
}


NestedGenericsImplementation::~NestedGenericsImplementation() {
}


void NestedGenericsImplementation::finalize() {
}

void NestedGenericsImplementation::_initializeImplementation() {
	_setClassHelper(NestedGenericsHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void NestedGenericsImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<NestedGenerics*>(stub);
	ManagedObjectImplementation::_setStub(stub);
}

DistributedObjectStub* NestedGenericsImplementation::_getStub() {
	return _this.get();
}

NestedGenericsImplementation::operator const NestedGenerics*() {
	return _this.get();
}

void NestedGenericsImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void NestedGenericsImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void NestedGenericsImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void NestedGenericsImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void NestedGenericsImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void NestedGenericsImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void NestedGenericsImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void NestedGenericsImplementation::_serializationHelperMethod() {
	ManagedObjectImplementation::_serializationHelperMethod();

	_setClassName("NestedGenerics");

}

void NestedGenericsImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(NestedGenericsImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool NestedGenericsImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x97150966: //NestedGenerics.primitiveVector
		TypeInfo<Vector<unsigned long long> >::parseFromBinaryStream(&primitiveVector, stream);
		return true;

	case 0x9f6b4b5d: //NestedGenerics.refToManaged
		TypeInfo<Reference<Reference<ManagedReference<ManagedObject* > > > >::parseFromBinaryStream(&refToManaged, stream);
		return true;

	case 0x1bf25f4a: //NestedGenerics.mapWithRef
		TypeInfo<VectorMap<int, Reference<ManagedReference<ManagedObject* > > > >::parseFromBinaryStream(&mapWithRef, stream);
		return true;

	case 0xd7e03438: //NestedGenerics.refToVector
		TypeInfo<Reference<Reference<Vector<int>*> > >::parseFromBinaryStream(&refToVector, stream);
		return true;

	case 0x7ad82fdf: //NestedGenerics.threeDeep
		TypeInfo<Reference<Reference<Vector<Reference<ManagedReference<ManagedObject* > > >*> > >::parseFromBinaryStream(&threeDeep, stream);
		return true;

	}

	return false;
}

void NestedGenericsImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = NestedGenericsImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int NestedGenericsImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0x97150966; //NestedGenerics.primitiveVector
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Vector<unsigned long long> >::toBinaryStream(&primitiveVector, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x9f6b4b5d; //NestedGenerics.refToManaged
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Reference<Reference<ManagedReference<ManagedObject* > > > >::toBinaryStream(&refToManaged, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x1bf25f4a; //NestedGenerics.mapWithRef
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<VectorMap<int, Reference<ManagedReference<ManagedObject* > > > >::toBinaryStream(&mapWithRef, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xd7e03438; //NestedGenerics.refToVector
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Reference<Reference<Vector<int>*> > >::toBinaryStream(&refToVector, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0x7ad82fdf; //NestedGenerics.threeDeep
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Reference<Reference<Vector<Reference<ManagedReference<ManagedObject* > > >*> > >::toBinaryStream(&threeDeep, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

/*
 *	NestedGenericsAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


NestedGenericsAdapter::NestedGenericsAdapter(NestedGenerics* obj) : ManagedObjectAdapter(obj) {
}

void NestedGenericsAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	default:
		ManagedObjectAdapter::invokeMethod(methid, inv);
	}
}

/*
 *	NestedGenericsHelper
 */

NestedGenericsHelper* NestedGenericsHelper::staticInitializer = NestedGenericsHelper::instance();

NestedGenericsHelper::NestedGenericsHelper() {
	className = "NestedGenerics";

	Core::getObjectBroker()->registerClass(className, this);
}

void NestedGenericsHelper::finalizeHelper() {
	NestedGenericsHelper::finalize();
}

DistributedObject* NestedGenericsHelper::instantiateObject() {
	return new NestedGenerics(DummyConstructorParameter::instance());
}

DistributedObjectServant* NestedGenericsHelper::instantiateServant() {
	return new NestedGenericsImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* NestedGenericsHelper::instantiatePOD() {
	return new NestedGenericsPOD();
}

DistributedObjectAdapter* NestedGenericsHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new NestedGenericsAdapter(static_cast<NestedGenerics*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	NestedGenericsPOD
 */

NestedGenericsPOD::~NestedGenericsPOD() {
}

NestedGenericsPOD::NestedGenericsPOD(void) {
	_className = "NestedGenerics";
}


void NestedGenericsPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = NestedGenericsPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int NestedGenericsPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (primitiveVector) {
	_nameHashCode = 0x97150966; //NestedGenerics.primitiveVector
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Vector<unsigned long long> >::toBinaryStream(&primitiveVector.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (refToManaged) {
	_nameHashCode = 0x9f6b4b5d; //NestedGenerics.refToManaged
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Reference<Reference<ManagedReference<ManagedObjectPOD* > > > >::toBinaryStream(&refToManaged.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (mapWithRef) {
	_nameHashCode = 0x1bf25f4a; //NestedGenerics.mapWithRef
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<VectorMap<int, Reference<ManagedReference<ManagedObjectPOD* > > > >::toBinaryStream(&mapWithRef.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (refToVector) {
	_nameHashCode = 0xd7e03438; //NestedGenerics.refToVector
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Reference<Reference<Vector<int>*> > >::toBinaryStream(&refToVector.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (threeDeep) {
	_nameHashCode = 0x7ad82fdf; //NestedGenerics.threeDeep
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<Reference<Reference<Vector<Reference<ManagedReference<ManagedObjectPOD* > > >*> > >::toBinaryStream(&threeDeep.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool NestedGenericsPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x97150966: //NestedGenerics.primitiveVector
		{
			Vector<unsigned long long> _mnprimitiveVector;
			TypeInfo<Vector<unsigned long long> >::parseFromBinaryStream(&_mnprimitiveVector, stream);
			primitiveVector = std::move(_mnprimitiveVector);
		}
		return true;

	case 0x9f6b4b5d: //NestedGenerics.refToManaged
		{
			Reference<Reference<ManagedReference<ManagedObjectPOD* > > > _mnrefToManaged;
			TypeInfo<Reference<Reference<ManagedReference<ManagedObjectPOD* > > > >::parseFromBinaryStream(&_mnrefToManaged, stream);
			refToManaged = std::move(_mnrefToManaged);
		}
		return true;

	case 0x1bf25f4a: //NestedGenerics.mapWithRef
		{
			VectorMap<int, Reference<ManagedReference<ManagedObjectPOD* > > > _mnmapWithRef;
			TypeInfo<VectorMap<int, Reference<ManagedReference<ManagedObjectPOD* > > > >::parseFromBinaryStream(&_mnmapWithRef, stream);
			mapWithRef = std::move(_mnmapWithRef);
		}
		return true;

	case 0xd7e03438: //NestedGenerics.refToVector
		{
			Reference<Reference<Vector<int>*> > _mnrefToVector;
			TypeInfo<Reference<Reference<Vector<int>*> > >::parseFromBinaryStream(&_mnrefToVector, stream);
			refToVector = std::move(_mnrefToVector);
		}
		return true;

	case 0x7ad82fdf: //NestedGenerics.threeDeep
		{
			Reference<Reference<Vector<Reference<ManagedReference<ManagedObjectPOD* > > >*> > _mnthreeDeep;
			TypeInfo<Reference<Reference<Vector<Reference<ManagedReference<ManagedObjectPOD* > > >*> > >::parseFromBinaryStream(&_mnthreeDeep, stream);
			threeDeep = std::move(_mnthreeDeep);
		}
		return true;

	}

	return false;
}

void NestedGenericsPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(NestedGenericsPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void NestedGenericsPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ManagedObjectPOD::writeObjectCompact(stream);

	TypeInfo<Vector<unsigned long long> >::toBinaryStream(&primitiveVector.value(), stream);

	TypeInfo<Reference<Reference<ManagedReference<ManagedObjectPOD* > > > >::toBinaryStream(&refToManaged.value(), stream);

	TypeInfo<VectorMap<int, Reference<ManagedReference<ManagedObjectPOD* > > > >::toBinaryStream(&mapWithRef.value(), stream);

	TypeInfo<Reference<Reference<Vector<int>*> > >::toBinaryStream(&refToVector.value(), stream);

	TypeInfo<Reference<Reference<Vector<Reference<ManagedReference<ManagedObjectPOD* > > >*> > >::toBinaryStream(&threeDeep.value(), stream);


}

