/*
 *	autogen/probe/Params.cpp generated by engine3 IDL compiler 0.70
 */

#include "Params.h"

/*
 *	ParamsStub
 */

enum {RPC_PLAININT__INT_ = 1117188990,RPC_PLAINSTRING__STRING_,RPC_PLAINCLASS__MANAGEDOBJECT_,RPC_PLAINGENERICPRIM__VECTOR_,RPC_PLAINGENERICCLASS__VECTOR_,RPC_FINALINT__INT_,RPC_FINALSTRING__STRING_,RPC_FINALCLASS__MANAGEDOBJECT_,RPC_FINALGENERICCLASS__VECTOR_,RPC_DEREFCLASS__MANAGEDOBJECT_,RPC_DEREFFINALCLASS__MANAGEDOBJECT_,RPC_DEREFFINALSTRING__STRING_,RPC_DEREFGENERICCLASS__VECTOR_,RPC_RAWWITHSTAR__REFERENCE_,RPC_RAWNOSTAR__REFERENCE_,RPC_DEFAULTINT__INT_,RPC_DEFAULTBOOL__BOOL_,RPC_DEFAULTNULL__MANAGEDOBJECT_,RPC_DEFAULTLONG__LONG_,RPC_DEFAULTLONGHEX__LONG_,RPC_MULTIDEFAULTS__INT_INT_INT_};

Params::Params(DummyConstructorParameter* param) : ManagedObject(param) {
	_setClassName("Params");
}

Params::~Params() {
}



void Params::plainInt(int x) {
	ParamsImplementation* _implementation = static_cast<ParamsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_PLAININT__INT_);
		method.addSignedIntParameter(x);

		method.executeWithVoidReturn();
	} else {
		_implementation->plainInt(x);
	}
}

void Params::plainString(String& s) {
	ParamsImplementation* _implementation = static_cast<ParamsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_PLAINSTRING__STRING_);
		method.addAsciiParameter(s);

		method.executeWithVoidReturn();
	} else {
		_implementation->plainString(s);
	}
}

void Params::plainClass(ManagedObject* obj) {
	ParamsImplementation* _implementation = static_cast<ParamsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_PLAINCLASS__MANAGEDOBJECT_);
		method.addObjectParameter(obj);

		method.executeWithVoidReturn();
	} else {
		_implementation->plainClass(obj);
	}
}

void Params::plainGenericPrim(Vector<int>* v) {
	ParamsImplementation* _implementation = static_cast<ParamsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_PLAINGENERICPRIM__VECTOR_);
		method.addObjectParameter(v);

		method.executeWithVoidReturn();
	} else {
		_implementation->plainGenericPrim(v);
	}
}

void Params::plainGenericClass(Vector<ManagedReference<ManagedObject* > >* v) {
	ParamsImplementation* _implementation = static_cast<ParamsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_PLAINGENERICCLASS__VECTOR_);
		method.addObjectParameter(v);

		method.executeWithVoidReturn();
	} else {
		_implementation->plainGenericClass(v);
	}
}

void Params::finalInt(const int x) {
	ParamsImplementation* _implementation = static_cast<ParamsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_FINALINT__INT_);
		method.addSignedIntParameter(x);

		method.executeWithVoidReturn();
	} else {
		_implementation->finalInt(x);
	}
}

void Params::finalString(const String& s) {
	ParamsImplementation* _implementation = static_cast<ParamsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_FINALSTRING__STRING_);
		method.addAsciiParameter(s);

		method.executeWithVoidReturn();
	} else {
		_implementation->finalString(s);
	}
}

void Params::finalClass(const ManagedObject* obj) {
	ParamsImplementation* _implementation = static_cast<ParamsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_FINALCLASS__MANAGEDOBJECT_);
		method.addObjectParameter(obj);

		method.executeWithVoidReturn();
	} else {
		_implementation->finalClass(obj);
	}
}

void Params::finalGenericClass(const Vector<ManagedReference<ManagedObject* > >* v) {
	ParamsImplementation* _implementation = static_cast<ParamsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_FINALGENERICCLASS__VECTOR_);
		method.addObjectParameter(v);

		method.executeWithVoidReturn();
	} else {
		_implementation->finalGenericClass(v);
	}
}

void Params::derefClass(ManagedObject& obj) {
	ParamsImplementation* _implementation = static_cast<ParamsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_DEREFCLASS__MANAGEDOBJECT_);
		method.addDereferencedSerializableParameter(obj);

		method.executeWithVoidReturn();
	} else {
		_implementation->derefClass(obj);
	}
}

void Params::derefFinalClass(const ManagedObject& obj) {
	ParamsImplementation* _implementation = static_cast<ParamsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_DEREFFINALCLASS__MANAGEDOBJECT_);
		method.addDereferencedSerializableParameter(obj);

		method.executeWithVoidReturn();
	} else {
		_implementation->derefFinalClass(obj);
	}
}

void Params::derefFinalString(const String& s) {
	ParamsImplementation* _implementation = static_cast<ParamsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_DEREFFINALSTRING__STRING_);
		method.addAsciiParameter(s);

		method.executeWithVoidReturn();
	} else {
		_implementation->derefFinalString(s);
	}
}

void Params::derefGenericClass(Vector<ManagedReference<ManagedObject* > >& v) {
	ParamsImplementation* _implementation = static_cast<ParamsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_DEREFGENERICCLASS__VECTOR_);
		method.addDereferencedSerializableParameter(v);

		method.executeWithVoidReturn();
	} else {
		_implementation->derefGenericClass(v);
	}
}

void Params::rawWithStar(Reference<ManagedObject* >* x) {
	ParamsImplementation* _implementation = static_cast<ParamsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_RAWWITHSTAR__REFERENCE_);
		method.addObjectParameter(x);

		method.executeWithVoidReturn();
	} else {
		_implementation->rawWithStar(x);
	}
}

void Params::rawNoStar(Reference<ManagedObject >* x) {
	ParamsImplementation* _implementation = static_cast<ParamsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_RAWNOSTAR__REFERENCE_);
		method.addObjectParameter(x);

		method.executeWithVoidReturn();
	} else {
		_implementation->rawNoStar(x);
	}
}

void Params::defaultInt(int x) {
	ParamsImplementation* _implementation = static_cast<ParamsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_DEFAULTINT__INT_);
		method.addSignedIntParameter(x);

		method.executeWithVoidReturn();
	} else {
		_implementation->defaultInt(x);
	}
}

void Params::defaultBool(bool b) {
	ParamsImplementation* _implementation = static_cast<ParamsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_DEFAULTBOOL__BOOL_);
		method.addBooleanParameter(b);

		method.executeWithVoidReturn();
	} else {
		_implementation->defaultBool(b);
	}
}

void Params::defaultNull(ManagedObject* obj) {
	ParamsImplementation* _implementation = static_cast<ParamsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_DEFAULTNULL__MANAGEDOBJECT_);
		method.addObjectParameter(obj);

		method.executeWithVoidReturn();
	} else {
		_implementation->defaultNull(obj);
	}
}

void Params::defaultLong(long long n) {
	ParamsImplementation* _implementation = static_cast<ParamsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_DEFAULTLONG__LONG_);
		method.addSignedLongParameter(n);

		method.executeWithVoidReturn();
	} else {
		_implementation->defaultLong(n);
	}
}

void Params::defaultLongHex(long long n) {
	ParamsImplementation* _implementation = static_cast<ParamsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_DEFAULTLONGHEX__LONG_);
		method.addSignedLongParameter(n);

		method.executeWithVoidReturn();
	} else {
		_implementation->defaultLongHex(n);
	}
}

void Params::multiDefaults(int x, int y, int z) {
	ParamsImplementation* _implementation = static_cast<ParamsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_MULTIDEFAULTS__INT_INT_INT_);
		method.addSignedIntParameter(x);
		method.addSignedIntParameter(y);
		method.addSignedIntParameter(z);

		method.executeWithVoidReturn();
	} else {
		_implementation->multiDefaults(x, y, z);
	}
}

DistributedObjectServant* Params::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* Params::_getImplementationForRead() const {
	return _impl;
}

void Params::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	ParamsImplementation
 */

ParamsImplementation::ParamsImplementation() : ManagedObjectImplementation() {
	_initializeImplementation();
}

ParamsImplementation::ParamsImplementation(DummyConstructorParameter* param) : ManagedObjectImplementation(param) {
	_initializeImplementation();
}


ParamsImplementation::~ParamsImplementation() {
}


void ParamsImplementation::finalize() {
}

void ParamsImplementation::_initializeImplementation() {
	_setClassHelper(ParamsHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void ParamsImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<Params*>(stub);
	ManagedObjectImplementation::_setStub(stub);
}

DistributedObjectStub* ParamsImplementation::_getStub() {
	return _this.get();
}

ParamsImplementation::operator const Params*() {
	return _this.get();
}

void ParamsImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void ParamsImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void ParamsImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void ParamsImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void ParamsImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void ParamsImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void ParamsImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void ParamsImplementation::_serializationHelperMethod() {
	ManagedObjectImplementation::_serializationHelperMethod();

	_setClassName("Params");

}

void ParamsImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ParamsImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool ParamsImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void ParamsImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ParamsImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ParamsImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

/*
 *	ParamsAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


ParamsAdapter::ParamsAdapter(Params* obj) : ManagedObjectAdapter(obj) {
}

void ParamsAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_PLAININT__INT_:
		{
			int x = inv->getSignedIntParameter();
			
			plainInt(x);
			
		}
		break;
	case RPC_PLAINSTRING__STRING_:
		{
			String s; inv->getAsciiParameter(s);
			
			plainString(s);
			
		}
		break;
	case RPC_PLAINCLASS__MANAGEDOBJECT_:
		{
			ManagedObject* obj = static_cast<ManagedObject*>(inv->getObjectParameter());
			
			plainClass(obj);
			
		}
		break;
	case RPC_PLAINGENERICPRIM__VECTOR_:
		{
			Vector<int>* v = static_cast<Vector*>(inv->getObjectParameter());
			
			plainGenericPrim(v);
			
		}
		break;
	case RPC_PLAINGENERICCLASS__VECTOR_:
		{
			Vector<ManagedReference<ManagedObject* > >* v = static_cast<Vector*>(inv->getObjectParameter());
			
			plainGenericClass(v);
			
		}
		break;
	case RPC_FINALINT__INT_:
		{
			 int x = inv->getSignedIntParameter();
			
			finalInt(x);
			
		}
		break;
	case RPC_FINALSTRING__STRING_:
		{
			 String s; inv->getAsciiParameter(s);
			
			finalString(s);
			
		}
		break;
	case RPC_FINALCLASS__MANAGEDOBJECT_:
		{
			 ManagedObject* obj = static_cast<ManagedObject*>(inv->getObjectParameter());
			
			finalClass(obj);
			
		}
		break;
	case RPC_FINALGENERICCLASS__VECTOR_:
		{
			 Vector<ManagedReference<ManagedObject* > >* v = static_cast<Vector*>(inv->getObjectParameter());
			
			finalGenericClass(v);
			
		}
		break;
	case RPC_DEREFCLASS__MANAGEDOBJECT_:
		{
			ManagedObject obj = inv->getDereferencedSerializableParameter<ManagedObject >();
			
			derefClass(obj);
			
		}
		break;
	case RPC_DEREFFINALCLASS__MANAGEDOBJECT_:
		{
			 ManagedObject obj = inv->getDereferencedSerializableParameter<ManagedObject >();
			
			derefFinalClass(obj);
			
		}
		break;
	case RPC_DEREFFINALSTRING__STRING_:
		{
			 String s; inv->getAsciiParameter(s);
			
			derefFinalString(s);
			
		}
		break;
	case RPC_DEREFGENERICCLASS__VECTOR_:
		{
			Vector<ManagedReference<ManagedObject* > > v = inv->getDereferencedSerializableParameter<Vector<ManagedReference<ManagedObject* > > >();
			
			derefGenericClass(v);
			
		}
		break;
	case RPC_RAWWITHSTAR__REFERENCE_:
		{
			Reference<ManagedObject* >* x = static_cast<Reference*>(inv->getObjectParameter());
			
			rawWithStar(x);
			
		}
		break;
	case RPC_RAWNOSTAR__REFERENCE_:
		{
			Reference<ManagedObject >* x = static_cast<Reference*>(inv->getObjectParameter());
			
			rawNoStar(x);
			
		}
		break;
	case RPC_DEFAULTINT__INT_:
		{
			int x = inv->getSignedIntParameter();
			
			defaultInt(x);
			
		}
		break;
	case RPC_DEFAULTBOOL__BOOL_:
		{
			bool b = inv->getBooleanParameter();
			
			defaultBool(b);
			
		}
		break;
	case RPC_DEFAULTNULL__MANAGEDOBJECT_:
		{
			ManagedObject* obj = static_cast<ManagedObject*>(inv->getObjectParameter());
			
			defaultNull(obj);
			
		}
		break;
	case RPC_DEFAULTLONG__LONG_:
		{
			long long n = inv->getSignedLongParameter();
			
			defaultLong(n);
			
		}
		break;
	case RPC_DEFAULTLONGHEX__LONG_:
		{
			long long n = inv->getSignedLongParameter();
			
			defaultLongHex(n);
			
		}
		break;
	case RPC_MULTIDEFAULTS__INT_INT_INT_:
		{
			int x = inv->getSignedIntParameter();
			int y = inv->getSignedIntParameter();
			int z = inv->getSignedIntParameter();
			
			multiDefaults(x, y, z);
			
		}
		break;
	default:
		ManagedObjectAdapter::invokeMethod(methid, inv);
	}
}

void ParamsAdapter::plainInt(int x) {
	(static_cast<Params*>(stub))->plainInt(x);
}

void ParamsAdapter::plainString(String& s) {
	(static_cast<Params*>(stub))->plainString(s);
}

void ParamsAdapter::plainClass(ManagedObject* obj) {
	(static_cast<Params*>(stub))->plainClass(obj);
}

void ParamsAdapter::plainGenericPrim(Vector<int>* v) {
	(static_cast<Params*>(stub))->plainGenericPrim(v);
}

void ParamsAdapter::plainGenericClass(Vector<ManagedReference<ManagedObject* > >* v) {
	(static_cast<Params*>(stub))->plainGenericClass(v);
}

void ParamsAdapter::finalInt(const int x) {
	(static_cast<Params*>(stub))->finalInt(x);
}

void ParamsAdapter::finalString(const String& s) {
	(static_cast<Params*>(stub))->finalString(s);
}

void ParamsAdapter::finalClass(const ManagedObject* obj) {
	(static_cast<Params*>(stub))->finalClass(obj);
}

void ParamsAdapter::finalGenericClass(const Vector<ManagedReference<ManagedObject* > >* v) {
	(static_cast<Params*>(stub))->finalGenericClass(v);
}

void ParamsAdapter::derefClass(ManagedObject& obj) {
	(static_cast<Params*>(stub))->derefClass(obj);
}

void ParamsAdapter::derefFinalClass(const ManagedObject& obj) {
	(static_cast<Params*>(stub))->derefFinalClass(obj);
}

void ParamsAdapter::derefFinalString(const String& s) {
	(static_cast<Params*>(stub))->derefFinalString(s);
}

void ParamsAdapter::derefGenericClass(Vector<ManagedReference<ManagedObject* > >& v) {
	(static_cast<Params*>(stub))->derefGenericClass(v);
}

void ParamsAdapter::rawWithStar(Reference<ManagedObject* >* x) {
	(static_cast<Params*>(stub))->rawWithStar(x);
}

void ParamsAdapter::rawNoStar(Reference<ManagedObject >* x) {
	(static_cast<Params*>(stub))->rawNoStar(x);
}

void ParamsAdapter::defaultInt(int x) {
	(static_cast<Params*>(stub))->defaultInt(x);
}

void ParamsAdapter::defaultBool(bool b) {
	(static_cast<Params*>(stub))->defaultBool(b);
}

void ParamsAdapter::defaultNull(ManagedObject* obj) {
	(static_cast<Params*>(stub))->defaultNull(obj);
}

void ParamsAdapter::defaultLong(long long n) {
	(static_cast<Params*>(stub))->defaultLong(n);
}

void ParamsAdapter::defaultLongHex(long long n) {
	(static_cast<Params*>(stub))->defaultLongHex(n);
}

void ParamsAdapter::multiDefaults(int x, int y, int z) {
	(static_cast<Params*>(stub))->multiDefaults(x, y, z);
}

/*
 *	ParamsHelper
 */

ParamsHelper* ParamsHelper::staticInitializer = ParamsHelper::instance();

ParamsHelper::ParamsHelper() {
	className = "Params";

	Core::getObjectBroker()->registerClass(className, this);
}

void ParamsHelper::finalizeHelper() {
	ParamsHelper::finalize();
}

DistributedObject* ParamsHelper::instantiateObject() {
	return new Params(DummyConstructorParameter::instance());
}

DistributedObjectServant* ParamsHelper::instantiateServant() {
	return new ParamsImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* ParamsHelper::instantiatePOD() {
	return new ParamsPOD();
}

DistributedObjectAdapter* ParamsHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new ParamsAdapter(static_cast<Params*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	ParamsPOD
 */

ParamsPOD::~ParamsPOD() {
}

ParamsPOD::ParamsPOD(void) {
	_className = "Params";
}


void ParamsPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ParamsPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ParamsPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

bool ParamsPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void ParamsPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ParamsPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void ParamsPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ManagedObjectPOD::writeObjectCompact(stream);


}

