/*
 *	autogen/probe/Params.h generated by engine3 IDL compiler 0.70
 */

#ifndef PARAMS_H_
#define PARAMS_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "system/util/Vector.h"

#include "engine/core/ManagedObject.h"

#include "system/lang/ref/Reference.h"

namespace probe {

class Params : public ManagedObject {
public:
	void plainInt(int x);

	void plainString(String& s);

	void plainClass(ManagedObject* obj);

	void plainGenericPrim(Vector<int>* v);

	void plainGenericClass(Vector<ManagedReference<ManagedObject* > >* v);

	void finalInt(const int x);

	void finalString(const String& s);

	void finalClass(const ManagedObject* obj);

	void finalGenericClass(const Vector<ManagedReference<ManagedObject* > >* v);

	void derefClass(ManagedObject& obj);

	void derefFinalClass(const ManagedObject& obj);

	void derefFinalString(const String& s);

	void derefGenericClass(Vector<ManagedReference<ManagedObject* > >& v);

	void rawWithStar(Reference<ManagedObject* >* x);

	void rawNoStar(Reference<ManagedObject >* x);

	void defaultInt(int x = 5);

	void defaultBool(bool b = true);

	void defaultNull(ManagedObject* obj = NULL);

	void defaultLong(long long n = 0);

	void defaultLongHex(long long n = 0xFF);

	void multiDefaults(int x, int y = 5, int z = 10);

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	Params(DummyConstructorParameter* param);

	virtual ~Params();

	friend class ParamsHelper;
};

} // namespace probe

using namespace probe;

namespace probe {

class ParamsImplementation : public ManagedObjectImplementation {

public:
	ParamsImplementation();
	ParamsImplementation(DummyConstructorParameter* param);

	void plainInt(int x);

	void plainString(String& s);

	void plainClass(ManagedObject* obj);

	void plainGenericPrim(Vector<int>* v);

	void plainGenericClass(Vector<ManagedReference<ManagedObject* > >* v);

	void finalInt(const int x);

	void finalString(const String& s);

	void finalClass(const ManagedObject* obj);

	void finalGenericClass(const Vector<ManagedReference<ManagedObject* > >* v);

	void derefClass(ManagedObject& obj);

	void derefFinalClass(const ManagedObject& obj);

	void derefFinalString(const String& s);

	void derefGenericClass(Vector<ManagedReference<ManagedObject* > >& v);

	void rawWithStar(Reference<ManagedObject* >* x);

	void rawNoStar(Reference<ManagedObject >* x);

	void defaultInt(int x = 5);

	void defaultBool(bool b = true);

	void defaultNull(ManagedObject* obj = NULL);

	void defaultLong(long long n = 0);

	void defaultLongHex(long long n = 0xFF);

	void multiDefaults(int x, int y = 5, int z = 10);

	WeakReference<Params*> _this;

	operator const Params*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~ParamsImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class Params;
};

class ParamsAdapter : public ManagedObjectAdapter {
public:
	ParamsAdapter(Params* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	void plainInt(int x);

	void plainString(String& s);

	void plainClass(ManagedObject* obj);

	void plainGenericPrim(Vector<int>* v);

	void plainGenericClass(Vector<ManagedReference<ManagedObject* > >* v);

	void finalInt(const int x);

	void finalString(const String& s);

	void finalClass(const ManagedObject* obj);

	void finalGenericClass(const Vector<ManagedReference<ManagedObject* > >* v);

	void derefClass(ManagedObject& obj);

	void derefFinalClass(const ManagedObject& obj);

	void derefFinalString(const String& s);

	void derefGenericClass(Vector<ManagedReference<ManagedObject* > >& v);

	void rawWithStar(Reference<ManagedObject* >* x);

	void rawNoStar(Reference<ManagedObject >* x);

	void defaultInt(int x);

	void defaultBool(bool b);

	void defaultNull(ManagedObject* obj);

	void defaultLong(long long n);

	void defaultLongHex(long long n);

	void multiDefaults(int x, int y, int z);

};

class ParamsHelper : public DistributedObjectClassHelper, public Singleton<ParamsHelper> {
	static ParamsHelper* staticInitializer;

public:
	ParamsHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<ParamsHelper>;
};

} // namespace probe

using namespace probe;

namespace probe {

class ParamsPOD : public ManagedObjectPOD {
public:

	ParamsPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~ParamsPOD();

};

} // namespace probe

using namespace probe;

#endif /*PARAMSPOD_H_*/
