/*
 *	autogen/probe/ParentFields.cpp generated by engine3 IDL compiler 0.70
 */

#include "ParentFields.h"

/*
 *	ParentFieldsStub
 */

ParentFields::ParentFields(DummyConstructorParameter* param) : ParentFieldsBase(param) {
	_setClassName("ParentFields");
}

ParentFields::~ParentFields() {
}



void ParentFields::plainParentAccess() {
	ParentFieldsImplementation* _implementation = static_cast<ParentFieldsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->plainParentAccess();
	}
}

void ParentFields::weakParentAccess() {
	ParentFieldsImplementation* _implementation = static_cast<ParentFieldsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->weakParentAccess();
	}
}

void ParentFields::chainedThroughPlainField() {
	ParentFieldsImplementation* _implementation = static_cast<ParentFieldsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->chainedThroughPlainField();
	}
}

DistributedObjectServant* ParentFields::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* ParentFields::_getImplementationForRead() const {
	return _impl;
}

void ParentFields::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	ParentFieldsImplementation
 */

ParentFieldsImplementation::ParentFieldsImplementation() : ParentFieldsBaseImplementation() {
	_initializeImplementation();
}

ParentFieldsImplementation::ParentFieldsImplementation(DummyConstructorParameter* param) : ParentFieldsBaseImplementation(param) {
	_initializeImplementation();
}


ParentFieldsImplementation::~ParentFieldsImplementation() {
}


void ParentFieldsImplementation::finalize() {
}

void ParentFieldsImplementation::_initializeImplementation() {
	_setClassHelper(ParentFieldsHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void ParentFieldsImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<ParentFields*>(stub);
	ParentFieldsBaseImplementation::_setStub(stub);
}

DistributedObjectStub* ParentFieldsImplementation::_getStub() {
	return _this.get();
}

ParentFieldsImplementation::operator const ParentFields*() {
	return _this.get();
}

void ParentFieldsImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void ParentFieldsImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void ParentFieldsImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void ParentFieldsImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void ParentFieldsImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void ParentFieldsImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void ParentFieldsImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void ParentFieldsImplementation::_serializationHelperMethod() {
	ParentFieldsBaseImplementation::_serializationHelperMethod();

	_setClassName("ParentFields");

}

void ParentFieldsImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ParentFieldsImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool ParentFieldsImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ParentFieldsBaseImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void ParentFieldsImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ParentFieldsImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ParentFieldsImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ParentFieldsBaseImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

void ParentFieldsImplementation::plainParentAccess() {
	// probe/ParentFields.idl():  		super.plainField.updateForWrite();
	ParentFieldsBaseImplementation::plainField.getForUpdate()->updateForWrite();
}

void ParentFieldsImplementation::weakParentAccess() {
	// probe/ParentFields.idl():  		super.weakField.updateForWrite();
	ParentFieldsBaseImplementation::weakField.getForUpdate().get()->updateForWrite();
}

void ParentFieldsImplementation::chainedThroughPlainField() {
	// probe/ParentFields.idl():  		super.plainField.updateForWrite();
	ParentFieldsBaseImplementation::plainField.getForUpdate()->updateForWrite();
	// probe/ParentFields.idl():  		super.plainField.lock();
	ParentFieldsBaseImplementation::plainField.getForUpdate()->lock();
}

/*
 *	ParentFieldsAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


ParentFieldsAdapter::ParentFieldsAdapter(ParentFields* obj) : ParentFieldsBaseAdapter(obj) {
}

void ParentFieldsAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	default:
		ParentFieldsBaseAdapter::invokeMethod(methid, inv);
	}
}

/*
 *	ParentFieldsHelper
 */

ParentFieldsHelper* ParentFieldsHelper::staticInitializer = ParentFieldsHelper::instance();

ParentFieldsHelper::ParentFieldsHelper() {
	className = "ParentFields";

	Core::getObjectBroker()->registerClass(className, this);
}

void ParentFieldsHelper::finalizeHelper() {
	ParentFieldsHelper::finalize();
}

DistributedObject* ParentFieldsHelper::instantiateObject() {
	return new ParentFields(DummyConstructorParameter::instance());
}

DistributedObjectServant* ParentFieldsHelper::instantiateServant() {
	return new ParentFieldsImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* ParentFieldsHelper::instantiatePOD() {
	return new ParentFieldsPOD();
}

DistributedObjectAdapter* ParentFieldsHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new ParentFieldsAdapter(static_cast<ParentFields*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	ParentFieldsPOD
 */

ParentFieldsPOD::~ParentFieldsPOD() {
}

ParentFieldsPOD::ParentFieldsPOD(void) {
	_className = "ParentFields";
}


void ParentFieldsPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ParentFieldsPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ParentFieldsPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ParentFieldsBasePOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

bool ParentFieldsPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ParentFieldsBasePOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void ParentFieldsPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ParentFieldsPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void ParentFieldsPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ParentFieldsBasePOD::writeObjectCompact(stream);


}

