/*
 *	autogen/probe/ParentFields.h generated by engine3 IDL compiler 0.70
 */

#ifndef PARENTFIELDS_H_
#define PARENTFIELDS_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "engine/core/ManagedObject.h"

#include "probe/ParentFieldsBase.h"

namespace probe {

class ParentFields : public ParentFieldsBase {
public:
	void plainParentAccess();

	void weakParentAccess();

	void chainedThroughPlainField();

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	ParentFields(DummyConstructorParameter* param);

	virtual ~ParentFields();

	friend class ParentFieldsHelper;
};

} // namespace probe

using namespace probe;

namespace probe {

class ParentFieldsImplementation : public ParentFieldsBaseImplementation {

public:
	ParentFieldsImplementation();
	ParentFieldsImplementation(DummyConstructorParameter* param);

	void plainParentAccess();

	void weakParentAccess();

	void chainedThroughPlainField();

	WeakReference<ParentFields*> _this;

	operator const ParentFields*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~ParentFieldsImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class ParentFields;
};

class ParentFieldsAdapter : public ParentFieldsBaseAdapter {
public:
	ParentFieldsAdapter(ParentFields* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

};

class ParentFieldsHelper : public DistributedObjectClassHelper, public Singleton<ParentFieldsHelper> {
	static ParentFieldsHelper* staticInitializer;

public:
	ParentFieldsHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<ParentFieldsHelper>;
};

} // namespace probe

using namespace probe;

namespace probe {

class ParentFieldsPOD : public ParentFieldsBasePOD {
public:

	ParentFieldsPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~ParentFieldsPOD();

};

} // namespace probe

using namespace probe;

#endif /*PARENTFIELDSPOD_H_*/
