/*
 *	autogen/probe/ParentFieldsBase.cpp generated by engine3 IDL compiler 0.70
 */

#include "ParentFieldsBase.h"

/*
 *	ParentFieldsBaseStub
 */

ParentFieldsBase::ParentFieldsBase(DummyConstructorParameter* param) : ManagedObject(param) {
	_setClassName("ParentFieldsBase");
}

ParentFieldsBase::~ParentFieldsBase() {
}



DistributedObjectServant* ParentFieldsBase::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* ParentFieldsBase::_getImplementationForRead() const {
	return _impl;
}

void ParentFieldsBase::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	ParentFieldsBaseImplementation
 */

ParentFieldsBaseImplementation::ParentFieldsBaseImplementation() : ManagedObjectImplementation() {
	_initializeImplementation();
}

ParentFieldsBaseImplementation::ParentFieldsBaseImplementation(DummyConstructorParameter* param) : ManagedObjectImplementation(param) {
	_initializeImplementation();
}


ParentFieldsBaseImplementation::~ParentFieldsBaseImplementation() {
}


void ParentFieldsBaseImplementation::finalize() {
}

void ParentFieldsBaseImplementation::_initializeImplementation() {
	_setClassHelper(ParentFieldsBaseHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void ParentFieldsBaseImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<ParentFieldsBase*>(stub);
	ManagedObjectImplementation::_setStub(stub);
}

DistributedObjectStub* ParentFieldsBaseImplementation::_getStub() {
	return _this.get();
}

ParentFieldsBaseImplementation::operator const ParentFieldsBase*() {
	return _this.get();
}

void ParentFieldsBaseImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void ParentFieldsBaseImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void ParentFieldsBaseImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void ParentFieldsBaseImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void ParentFieldsBaseImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void ParentFieldsBaseImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void ParentFieldsBaseImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void ParentFieldsBaseImplementation::_serializationHelperMethod() {
	ManagedObjectImplementation::_serializationHelperMethod();

	_setClassName("ParentFieldsBase");

}

void ParentFieldsBaseImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ParentFieldsBaseImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool ParentFieldsBaseImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0xc07f22b6: //ParentFieldsBase.plainField
		TypeInfo<ManagedReference<ManagedObject* > >::parseFromBinaryStream(&plainField, stream);
		return true;

	case 0xfc16e61a: //ParentFieldsBase.weakField
		TypeInfo<ManagedWeakReference<ManagedObject* > >::parseFromBinaryStream(&weakField, stream);
		return true;

	}

	return false;
}

void ParentFieldsBaseImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ParentFieldsBaseImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ParentFieldsBaseImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0xc07f22b6; //ParentFieldsBase.plainField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedReference<ManagedObject* > >::toBinaryStream(&plainField, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;

	_nameHashCode = 0xfc16e61a; //ParentFieldsBase.weakField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedWeakReference<ManagedObject* > >::toBinaryStream(&weakField, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

/*
 *	ParentFieldsBaseAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


ParentFieldsBaseAdapter::ParentFieldsBaseAdapter(ParentFieldsBase* obj) : ManagedObjectAdapter(obj) {
}

void ParentFieldsBaseAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	default:
		ManagedObjectAdapter::invokeMethod(methid, inv);
	}
}

/*
 *	ParentFieldsBaseHelper
 */

ParentFieldsBaseHelper* ParentFieldsBaseHelper::staticInitializer = ParentFieldsBaseHelper::instance();

ParentFieldsBaseHelper::ParentFieldsBaseHelper() {
	className = "ParentFieldsBase";

	Core::getObjectBroker()->registerClass(className, this);
}

void ParentFieldsBaseHelper::finalizeHelper() {
	ParentFieldsBaseHelper::finalize();
}

DistributedObject* ParentFieldsBaseHelper::instantiateObject() {
	return new ParentFieldsBase(DummyConstructorParameter::instance());
}

DistributedObjectServant* ParentFieldsBaseHelper::instantiateServant() {
	return new ParentFieldsBaseImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* ParentFieldsBaseHelper::instantiatePOD() {
	return new ParentFieldsBasePOD();
}

DistributedObjectAdapter* ParentFieldsBaseHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new ParentFieldsBaseAdapter(static_cast<ParentFieldsBase*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	ParentFieldsBasePOD
 */

ParentFieldsBasePOD::~ParentFieldsBasePOD() {
}

ParentFieldsBasePOD::ParentFieldsBasePOD(void) {
	_className = "ParentFieldsBase";
}


void ParentFieldsBasePOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ParentFieldsBasePOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ParentFieldsBasePOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (plainField) {
	_nameHashCode = 0xc07f22b6; //ParentFieldsBase.plainField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedReference<ManagedObjectPOD* > >::toBinaryStream(&plainField.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}

	if (weakField) {
	_nameHashCode = 0xfc16e61a; //ParentFieldsBase.weakField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedWeakReference<ManagedObjectPOD* > >::toBinaryStream(&weakField.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool ParentFieldsBasePOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0xc07f22b6: //ParentFieldsBase.plainField
		{
			ManagedReference<ManagedObjectPOD* > _mnplainField;
			TypeInfo<ManagedReference<ManagedObjectPOD* > >::parseFromBinaryStream(&_mnplainField, stream);
			plainField = std::move(_mnplainField);
		}
		return true;

	case 0xfc16e61a: //ParentFieldsBase.weakField
		{
			ManagedWeakReference<ManagedObjectPOD* > _mnweakField;
			TypeInfo<ManagedWeakReference<ManagedObjectPOD* > >::parseFromBinaryStream(&_mnweakField, stream);
			weakField = std::move(_mnweakField);
		}
		return true;

	}

	return false;
}

void ParentFieldsBasePOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ParentFieldsBasePOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void ParentFieldsBasePOD::writeObjectCompact(ObjectOutputStream* stream) {
	ManagedObjectPOD::writeObjectCompact(stream);

	TypeInfo<ManagedReference<ManagedObjectPOD* > >::toBinaryStream(&plainField.value(), stream);

	TypeInfo<ManagedWeakReference<ManagedObjectPOD* > >::toBinaryStream(&weakField.value(), stream);


}

