/*
 *	autogen/probe/RawDereferenced.cpp generated by engine3 IDL compiler 0.70
 */

#include "RawDereferenced.h"

/*
 *	RawDereferencedStub
 */

enum {RPC_GETDEREFERENCEDREF__ = 1517703269,RPC_GETPOINTERREF__};

RawDereferenced::RawDereferenced(DummyConstructorParameter* param) : ManagedObject(param) {
	_setClassName("RawDereferenced");
}

RawDereferenced::~RawDereferenced() {
}



WeakReference<ManagedObject* > RawDereferenced::getDereferencedRef() {
	RawDereferencedImplementation* _implementation = static_cast<RawDereferencedImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETDEREFERENCEDREF__);

		return static_cast<WeakReference<ManagedObject* >>(method.executeWithObjectReturn());
	} else {
		return _implementation->getDereferencedRef();
	}
}

Reference<ManagedObject* >* RawDereferenced::getPointerRef() {
	RawDereferencedImplementation* _implementation = static_cast<RawDereferencedImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETPOINTERREF__);

		return static_cast<Reference<ManagedObject* >*>(method.executeWithObjectReturn());
	} else {
		return _implementation->getPointerRef();
	}
}

DistributedObjectServant* RawDereferenced::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* RawDereferenced::_getImplementationForRead() const {
	return _impl;
}

void RawDereferenced::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	RawDereferencedImplementation
 */

RawDereferencedImplementation::RawDereferencedImplementation() : ManagedObjectImplementation() {
	_initializeImplementation();
}

RawDereferencedImplementation::RawDereferencedImplementation(DummyConstructorParameter* param) : ManagedObjectImplementation(param) {
	_initializeImplementation();
}


RawDereferencedImplementation::~RawDereferencedImplementation() {
}


void RawDereferencedImplementation::finalize() {
}

void RawDereferencedImplementation::_initializeImplementation() {
	_setClassHelper(RawDereferencedHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void RawDereferencedImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<RawDereferenced*>(stub);
	ManagedObjectImplementation::_setStub(stub);
}

DistributedObjectStub* RawDereferencedImplementation::_getStub() {
	return _this.get();
}

RawDereferencedImplementation::operator const RawDereferenced*() {
	return _this.get();
}

void RawDereferencedImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void RawDereferencedImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void RawDereferencedImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void RawDereferencedImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void RawDereferencedImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void RawDereferencedImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void RawDereferencedImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void RawDereferencedImplementation::_serializationHelperMethod() {
	ManagedObjectImplementation::_serializationHelperMethod();

	_setClassName("RawDereferenced");

}

void RawDereferencedImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(RawDereferencedImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool RawDereferencedImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void RawDereferencedImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = RawDereferencedImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int RawDereferencedImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

/*
 *	RawDereferencedAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


RawDereferencedAdapter::RawDereferencedAdapter(RawDereferenced* obj) : ManagedObjectAdapter(obj) {
}

void RawDereferencedAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_GETDEREFERENCEDREF__:
		{
			
			DistributedObject* _m_res = getDereferencedRef();
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	case RPC_GETPOINTERREF__:
		{
			
			DistributedObject* _m_res = getPointerRef();
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	default:
		ManagedObjectAdapter::invokeMethod(methid, inv);
	}
}

WeakReference<ManagedObject* > RawDereferencedAdapter::getDereferencedRef() {
	return (static_cast<RawDereferenced*>(stub))->getDereferencedRef();
}

Reference<ManagedObject* >* RawDereferencedAdapter::getPointerRef() {
	return (static_cast<RawDereferenced*>(stub))->getPointerRef();
}

/*
 *	RawDereferencedHelper
 */

RawDereferencedHelper* RawDereferencedHelper::staticInitializer = RawDereferencedHelper::instance();

RawDereferencedHelper::RawDereferencedHelper() {
	className = "RawDereferenced";

	Core::getObjectBroker()->registerClass(className, this);
}

void RawDereferencedHelper::finalizeHelper() {
	RawDereferencedHelper::finalize();
}

DistributedObject* RawDereferencedHelper::instantiateObject() {
	return new RawDereferenced(DummyConstructorParameter::instance());
}

DistributedObjectServant* RawDereferencedHelper::instantiateServant() {
	return new RawDereferencedImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* RawDereferencedHelper::instantiatePOD() {
	return new RawDereferencedPOD();
}

DistributedObjectAdapter* RawDereferencedHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new RawDereferencedAdapter(static_cast<RawDereferenced*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	RawDereferencedPOD
 */

RawDereferencedPOD::~RawDereferencedPOD() {
}

RawDereferencedPOD::RawDereferencedPOD(void) {
	_className = "RawDereferenced";
}


void RawDereferencedPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = RawDereferencedPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int RawDereferencedPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

bool RawDereferencedPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void RawDereferencedPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(RawDereferencedPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void RawDereferencedPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ManagedObjectPOD::writeObjectCompact(stream);


}

