/*
 *	autogen/probe/RawDereferenced.h generated by engine3 IDL compiler 0.70
 */

#ifndef RAWDEREFERENCED_H_
#define RAWDEREFERENCED_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "system/lang/ref/WeakReference.h"

#include "system/lang/ref/Reference.h"

#include "engine/core/ManagedObject.h"

namespace probe {

class RawDereferenced : public ManagedObject {
public:
	WeakReference<ManagedObject* > getDereferencedRef();

	Reference<ManagedObject* >* getPointerRef();

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	RawDereferenced(DummyConstructorParameter* param);

	virtual ~RawDereferenced();

	friend class RawDereferencedHelper;
};

} // namespace probe

using namespace probe;

namespace probe {

class RawDereferencedImplementation : public ManagedObjectImplementation {

public:
	RawDereferencedImplementation();
	RawDereferencedImplementation(DummyConstructorParameter* param);

	WeakReference<ManagedObject* > getDereferencedRef();

	Reference<ManagedObject* >* getPointerRef();

	WeakReference<RawDereferenced*> _this;

	operator const RawDereferenced*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~RawDereferencedImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class RawDereferenced;
};

class RawDereferencedAdapter : public ManagedObjectAdapter {
public:
	RawDereferencedAdapter(RawDereferenced* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	WeakReference<ManagedObject* > getDereferencedRef();

	Reference<ManagedObject* >* getPointerRef();

};

class RawDereferencedHelper : public DistributedObjectClassHelper, public Singleton<RawDereferencedHelper> {
	static RawDereferencedHelper* staticInitializer;

public:
	RawDereferencedHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<RawDereferencedHelper>;
};

} // namespace probe

using namespace probe;

namespace probe {

class RawDereferencedPOD : public ManagedObjectPOD {
public:

	RawDereferencedPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~RawDereferencedPOD();

};

} // namespace probe

using namespace probe;

#endif /*RAWDEREFERENCEDPOD_H_*/
