/*
 *	autogen/probe/Returns.h generated by engine3 IDL compiler 0.70
 */

#ifndef RETURNS_H_
#define RETURNS_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "system/util/Vector.h"

#include "engine/core/ManagedObject.h"

namespace probe {

class Returns : public ManagedObject {
public:
	int retInt();

	String retString();

	ManagedObject* retClass();

	Vector<int>* retVecPrim();

	Vector<ManagedReference<ManagedObject* > >* retVecClass();

	const int finalInt();

	const String finalString();

	const ManagedObject* finalClass();

	Reference<ManagedObject* > refClass();

	Reference<const ManagedObject* > refFinalClass();

	ManagedWeakReference<ManagedObject* > weakClass();

	ManagedWeakReference<const ManagedObject* > weakFinalClass();

	ManagedObject derefClass();

	const ManagedObject derefFinalClass();

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	Returns(DummyConstructorParameter* param);

	virtual ~Returns();

	friend class ReturnsHelper;
};

} // namespace probe

using namespace probe;

namespace probe {

class ReturnsImplementation : public ManagedObjectImplementation {

public:
	ReturnsImplementation();
	ReturnsImplementation(DummyConstructorParameter* param);

	int retInt();

	String retString();

	ManagedObject* retClass();

	Vector<int>* retVecPrim();

	Vector<ManagedReference<ManagedObject* > >* retVecClass();

	const int finalInt();

	const String finalString();

	const ManagedObject* finalClass();

	Reference<ManagedObject* > refClass();

	Reference<const ManagedObject* > refFinalClass();

	ManagedWeakReference<ManagedObject* > weakClass();

	ManagedWeakReference<const ManagedObject* > weakFinalClass();

	ManagedObject derefClass();

	const ManagedObject derefFinalClass();

	WeakReference<Returns*> _this;

	operator const Returns*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~ReturnsImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class Returns;
};

class ReturnsAdapter : public ManagedObjectAdapter {
public:
	ReturnsAdapter(Returns* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	int retInt();

	String retString();

	ManagedObject* retClass();

	Vector<int>* retVecPrim();

	Vector<ManagedReference<ManagedObject* > >* retVecClass();

	const int finalInt();

	const String finalString();

	const ManagedObject* finalClass();

	Reference<ManagedObject* > refClass();

	Reference<const ManagedObject* > refFinalClass();

	ManagedWeakReference<ManagedObject* > weakClass();

	ManagedWeakReference<const ManagedObject* > weakFinalClass();

	ManagedObject derefClass();

	const ManagedObject derefFinalClass();

};

class ReturnsHelper : public DistributedObjectClassHelper, public Singleton<ReturnsHelper> {
	static ReturnsHelper* staticInitializer;

public:
	ReturnsHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<ReturnsHelper>;
};

} // namespace probe

using namespace probe;

namespace probe {

class ReturnsPOD : public ManagedObjectPOD {
public:

	ReturnsPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~ReturnsPOD();

};

} // namespace probe

using namespace probe;

#endif /*RETURNSPOD_H_*/
