/*
 *	autogen/probe/Returns.cpp generated by engine3 IDL compiler 0.70
 */

#include "Returns.h"

/*
 *	ReturnsStub
 */

enum {RPC_RETINT__ = 664163704,RPC_RETSTRING__,RPC_RETCLASS__,RPC_RETVECPRIM__,RPC_RETVECCLASS__,RPC_FINALINT__,RPC_FINALSTRING__,RPC_FINALCLASS__,RPC_REFCLASS__,RPC_REFFINALCLASS__,RPC_WEAKCLASS__,RPC_WEAKFINALCLASS__,RPC_DEREFCLASS__,RPC_DEREFFINALCLASS__};

Returns::Returns(DummyConstructorParameter* param) : ManagedObject(param) {
	_setClassName("Returns");
}

Returns::~Returns() {
}



int Returns::retInt() {
	ReturnsImplementation* _implementation = static_cast<ReturnsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_RETINT__);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->retInt();
	}
}

String Returns::retString() {
	ReturnsImplementation* _implementation = static_cast<ReturnsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_RETSTRING__);

		String _return_retString;
		method.executeWithAsciiReturn(_return_retString);
		return _return_retString;
	} else {
		return _implementation->retString();
	}
}

ManagedObject* Returns::retClass() {
	ReturnsImplementation* _implementation = static_cast<ReturnsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_RETCLASS__);

		return static_cast<ManagedObject*>(method.executeWithObjectReturn());
	} else {
		return _implementation->retClass();
	}
}

Vector<int>* Returns::retVecPrim() {
	ReturnsImplementation* _implementation = static_cast<ReturnsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_RETVECPRIM__);

		return static_cast<Vector<int>*>(method.executeWithObjectReturn());
	} else {
		return _implementation->retVecPrim();
	}
}

Vector<ManagedReference<ManagedObject* > >* Returns::retVecClass() {
	ReturnsImplementation* _implementation = static_cast<ReturnsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_RETVECCLASS__);

		return static_cast<Vector<ManagedReference<ManagedObject* > >*>(method.executeWithObjectReturn());
	} else {
		return _implementation->retVecClass();
	}
}

const int Returns::finalInt() {
	ReturnsImplementation* _implementation = static_cast<ReturnsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_FINALINT__);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->finalInt();
	}
}

const String Returns::finalString() {
	ReturnsImplementation* _implementation = static_cast<ReturnsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_FINALSTRING__);

		String _return_finalString;
		method.executeWithAsciiReturn(_return_finalString);
		return _return_finalString;
	} else {
		return _implementation->finalString();
	}
}

const ManagedObject* Returns::finalClass() {
	ReturnsImplementation* _implementation = static_cast<ReturnsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_FINALCLASS__);

		return static_cast<const ManagedObject*>(method.executeWithObjectReturn());
	} else {
		return _implementation->finalClass();
	}
}

Reference<ManagedObject* > Returns::refClass() {
	ReturnsImplementation* _implementation = static_cast<ReturnsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_REFCLASS__);

		return static_cast<ManagedObject*>(method.executeWithObjectReturn());
	} else {
		return _implementation->refClass();
	}
}

Reference<const ManagedObject* > Returns::refFinalClass() {
	ReturnsImplementation* _implementation = static_cast<ReturnsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_REFFINALCLASS__);

		return static_cast<const ManagedObject*>(method.executeWithObjectReturn());
	} else {
		return _implementation->refFinalClass();
	}
}

ManagedWeakReference<ManagedObject* > Returns::weakClass() {
	ReturnsImplementation* _implementation = static_cast<ReturnsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_WEAKCLASS__);

		return static_cast<ManagedObject*>(method.executeWithObjectReturn());
	} else {
		return _implementation->weakClass();
	}
}

ManagedWeakReference<const ManagedObject* > Returns::weakFinalClass() {
	ReturnsImplementation* _implementation = static_cast<ReturnsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_WEAKFINALCLASS__);

		return static_cast<const ManagedObject*>(method.executeWithObjectReturn());
	} else {
		return _implementation->weakFinalClass();
	}
}

ManagedObject Returns::derefClass() {
	ReturnsImplementation* _implementation = static_cast<ReturnsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_DEREFCLASS__);

		return static_cast<ManagedObject>(method.executeWithObjectReturn());
	} else {
		return _implementation->derefClass();
	}
}

const ManagedObject Returns::derefFinalClass() {
	ReturnsImplementation* _implementation = static_cast<ReturnsImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_DEREFFINALCLASS__);

		return static_cast<const ManagedObject>(method.executeWithObjectReturn());
	} else {
		return _implementation->derefFinalClass();
	}
}

DistributedObjectServant* Returns::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* Returns::_getImplementationForRead() const {
	return _impl;
}

void Returns::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	ReturnsImplementation
 */

ReturnsImplementation::ReturnsImplementation() : ManagedObjectImplementation() {
	_initializeImplementation();
}

ReturnsImplementation::ReturnsImplementation(DummyConstructorParameter* param) : ManagedObjectImplementation(param) {
	_initializeImplementation();
}


ReturnsImplementation::~ReturnsImplementation() {
}


void ReturnsImplementation::finalize() {
}

void ReturnsImplementation::_initializeImplementation() {
	_setClassHelper(ReturnsHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void ReturnsImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<Returns*>(stub);
	ManagedObjectImplementation::_setStub(stub);
}

DistributedObjectStub* ReturnsImplementation::_getStub() {
	return _this.get();
}

ReturnsImplementation::operator const Returns*() {
	return _this.get();
}

void ReturnsImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void ReturnsImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void ReturnsImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void ReturnsImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void ReturnsImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void ReturnsImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void ReturnsImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void ReturnsImplementation::_serializationHelperMethod() {
	ManagedObjectImplementation::_serializationHelperMethod();

	_setClassName("Returns");

}

void ReturnsImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ReturnsImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool ReturnsImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void ReturnsImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ReturnsImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ReturnsImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

/*
 *	ReturnsAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


ReturnsAdapter::ReturnsAdapter(Returns* obj) : ManagedObjectAdapter(obj) {
}

void ReturnsAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_RETINT__:
		{
			
			int _m_res = retInt();
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_RETSTRING__:
		{
			
			String _m_res = retString();
			resp->insertAscii(_m_res);
		}
		break;
	case RPC_RETCLASS__:
		{
			
			DistributedObject* _m_res = retClass();
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	case RPC_RETVECPRIM__:
		{
			
			DistributedObject* _m_res = retVecPrim();
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	case RPC_RETVECCLASS__:
		{
			
			DistributedObject* _m_res = retVecClass();
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	case RPC_FINALINT__:
		{
			
			const int _m_res = finalInt();
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_FINALSTRING__:
		{
			
			const String _m_res = finalString();
			resp->insertAscii(_m_res);
		}
		break;
	case RPC_FINALCLASS__:
		{
			
			DistributedObject* _m_res = finalClass();
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	case RPC_REFCLASS__:
		{
			
			DistributedObject* _m_res = refClass();
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	case RPC_REFFINALCLASS__:
		{
			
			DistributedObject* _m_res = refFinalClass();
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	case RPC_WEAKCLASS__:
		{
			
			DistributedObject* _m_res = weakClass().get();
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	case RPC_WEAKFINALCLASS__:
		{
			
			DistributedObject* _m_res = weakFinalClass().get();
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	case RPC_DEREFCLASS__:
		{
			
			DistributedObject* _m_res = derefClass();
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	case RPC_DEREFFINALCLASS__:
		{
			
			DistributedObject* _m_res = derefFinalClass();
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	default:
		ManagedObjectAdapter::invokeMethod(methid, inv);
	}
}

int ReturnsAdapter::retInt() {
	return (static_cast<Returns*>(stub))->retInt();
}

String ReturnsAdapter::retString() {
	return (static_cast<Returns*>(stub))->retString();
}

ManagedObject* ReturnsAdapter::retClass() {
	return (static_cast<Returns*>(stub))->retClass();
}

Vector<int>* ReturnsAdapter::retVecPrim() {
	return (static_cast<Returns*>(stub))->retVecPrim();
}

Vector<ManagedReference<ManagedObject* > >* ReturnsAdapter::retVecClass() {
	return (static_cast<Returns*>(stub))->retVecClass();
}

const int ReturnsAdapter::finalInt() {
	return (static_cast<Returns*>(stub))->finalInt();
}

const String ReturnsAdapter::finalString() {
	return (static_cast<Returns*>(stub))->finalString();
}

const ManagedObject* ReturnsAdapter::finalClass() {
	return (static_cast<Returns*>(stub))->finalClass();
}

Reference<ManagedObject* > ReturnsAdapter::refClass() {
	return (static_cast<Returns*>(stub))->refClass();
}

Reference<const ManagedObject* > ReturnsAdapter::refFinalClass() {
	return (static_cast<Returns*>(stub))->refFinalClass();
}

ManagedWeakReference<ManagedObject* > ReturnsAdapter::weakClass() {
	return (static_cast<Returns*>(stub))->weakClass();
}

ManagedWeakReference<const ManagedObject* > ReturnsAdapter::weakFinalClass() {
	return (static_cast<Returns*>(stub))->weakFinalClass();
}

ManagedObject ReturnsAdapter::derefClass() {
	return (static_cast<Returns*>(stub))->derefClass();
}

const ManagedObject ReturnsAdapter::derefFinalClass() {
	return (static_cast<Returns*>(stub))->derefFinalClass();
}

/*
 *	ReturnsHelper
 */

ReturnsHelper* ReturnsHelper::staticInitializer = ReturnsHelper::instance();

ReturnsHelper::ReturnsHelper() {
	className = "Returns";

	Core::getObjectBroker()->registerClass(className, this);
}

void ReturnsHelper::finalizeHelper() {
	ReturnsHelper::finalize();
}

DistributedObject* ReturnsHelper::instantiateObject() {
	return new Returns(DummyConstructorParameter::instance());
}

DistributedObjectServant* ReturnsHelper::instantiateServant() {
	return new ReturnsImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* ReturnsHelper::instantiatePOD() {
	return new ReturnsPOD();
}

DistributedObjectAdapter* ReturnsHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new ReturnsAdapter(static_cast<Returns*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	ReturnsPOD
 */

ReturnsPOD::~ReturnsPOD() {
}

ReturnsPOD::ReturnsPOD(void) {
	_className = "Returns";
}


void ReturnsPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ReturnsPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ReturnsPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

bool ReturnsPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void ReturnsPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ReturnsPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void ReturnsPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ManagedObjectPOD::writeObjectCompact(stream);


}

