/*
 *	autogen/probe/Scriptable.h generated by engine3 IDL compiler 0.70
 */

#ifndef SCRIPTABLE_H_
#define SCRIPTABLE_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "engine/lua/Luna.h"

#include "engine/core/ManagedObject.h"

namespace probe {

class Scriptable : public ManagedObject {
public:
	bool isReady();

	int getCount();

	void setCount(int n);

	void setName(const String& s);

	void addObject(ManagedObject* obj);

	ManagedObject* getOwner();

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	Scriptable(DummyConstructorParameter* param);

	virtual ~Scriptable();

	friend class ScriptableHelper;
};

} // namespace probe

using namespace probe;

namespace probe {

class ScriptableImplementation : public ManagedObjectImplementation {
protected:
	int count;

public:
	ScriptableImplementation();
	ScriptableImplementation(DummyConstructorParameter* param);

	bool isReady();

	int getCount();

	void setCount(int n);

	void setName(const String& s);

	void addObject(ManagedObject* obj);

	ManagedObject* getOwner();

	WeakReference<Scriptable*> _this;

	operator const Scriptable*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~ScriptableImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class Scriptable;
};

class ScriptableAdapter : public ManagedObjectAdapter {
public:
	ScriptableAdapter(Scriptable* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

	bool isReady();

	int getCount();

	void setCount(int n);

	void setName(const String& s);

	void addObject(ManagedObject* obj);

	ManagedObject* getOwner();

};

class ScriptableHelper : public DistributedObjectClassHelper, public Singleton<ScriptableHelper> {
	static ScriptableHelper* staticInitializer;

public:
	ScriptableHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<ScriptableHelper>;
};

class LuaScriptable {
public:
	static const char className[];
	static Luna<LuaScriptable>::RegType Register[];

	LuaScriptable(lua_State *L);
	virtual ~LuaScriptable();

	int _setObject(lua_State *L);
	int _getObject(lua_State *L);
	int isReady(lua_State *L);
	int getCount(lua_State *L);
	int setCount(lua_State *L);
	int setName(lua_State *L);
	int addObject(lua_State *L);
	int getOwner(lua_State *L);

	Reference<Scriptable*> realObject;
};

} // namespace probe

using namespace probe;

namespace probe {

class ScriptablePOD : public ManagedObjectPOD {
public:
	Optional<int> count;

	String _className;
	ScriptablePOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~ScriptablePOD();

};

} // namespace probe

using namespace probe;

#endif /*SCRIPTABLEPOD_H_*/
