/*
 *	autogen/probe/Scriptable.cpp generated by engine3 IDL compiler 0.70
 */

#include "Scriptable.h"

/*
 *	ScriptableStub
 */

enum {RPC_ISREADY__ = 3020311965,RPC_GETCOUNT__,RPC_SETCOUNT__INT_,RPC_SETNAME__STRING_,RPC_ADDOBJECT__MANAGEDOBJECT_,RPC_GETOWNER__};

Scriptable::Scriptable(DummyConstructorParameter* param) : ManagedObject(param) {
	_setClassName("Scriptable");
}

Scriptable::~Scriptable() {
}



bool Scriptable::isReady() {
	ScriptableImplementation* _implementation = static_cast<ScriptableImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ISREADY__);

		return method.executeWithBooleanReturn();
	} else {
		return _implementation->isReady();
	}
}

int Scriptable::getCount() {
	ScriptableImplementation* _implementation = static_cast<ScriptableImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETCOUNT__);

		return method.executeWithSignedIntReturn();
	} else {
		return _implementation->getCount();
	}
}

void Scriptable::setCount(int n) {
	ScriptableImplementation* _implementation = static_cast<ScriptableImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETCOUNT__INT_);
		method.addSignedIntParameter(n);

		method.executeWithVoidReturn();
	} else {
		_implementation->setCount(n);
	}
}

void Scriptable::setName(const String& s) {
	ScriptableImplementation* _implementation = static_cast<ScriptableImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_SETNAME__STRING_);
		method.addAsciiParameter(s);

		method.executeWithVoidReturn();
	} else {
		_implementation->setName(s);
	}
}

void Scriptable::addObject(ManagedObject* obj) {
	ScriptableImplementation* _implementation = static_cast<ScriptableImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_ADDOBJECT__MANAGEDOBJECT_);
		method.addObjectParameter(obj);

		method.executeWithVoidReturn();
	} else {
		_implementation->addObject(obj);
	}
}

ManagedObject* Scriptable::getOwner() {
	ScriptableImplementation* _implementation = static_cast<ScriptableImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		if (!deployed)
			throw ObjectNotDeployedException(this);

		DistributedMethod method(this, RPC_GETOWNER__);

		return static_cast<ManagedObject*>(method.executeWithObjectReturn());
	} else {
		return _implementation->getOwner();
	}
}

DistributedObjectServant* Scriptable::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* Scriptable::_getImplementationForRead() const {
	return _impl;
}

void Scriptable::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	ScriptableImplementation
 */

ScriptableImplementation::ScriptableImplementation() : ManagedObjectImplementation() {
	_initializeImplementation();
}

ScriptableImplementation::ScriptableImplementation(DummyConstructorParameter* param) : ManagedObjectImplementation(param) {
	_initializeImplementation();
}


ScriptableImplementation::~ScriptableImplementation() {
}


void ScriptableImplementation::finalize() {
}

void ScriptableImplementation::_initializeImplementation() {
	_setClassHelper(ScriptableHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void ScriptableImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<Scriptable*>(stub);
	ManagedObjectImplementation::_setStub(stub);
}

DistributedObjectStub* ScriptableImplementation::_getStub() {
	return _this.get();
}

ScriptableImplementation::operator const Scriptable*() {
	return _this.get();
}

void ScriptableImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void ScriptableImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void ScriptableImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void ScriptableImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void ScriptableImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void ScriptableImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void ScriptableImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void ScriptableImplementation::_serializationHelperMethod() {
	ManagedObjectImplementation::_serializationHelperMethod();

	_setClassName("Scriptable");

}

void ScriptableImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ScriptableImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool ScriptableImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x51dc11b3: //Scriptable.count
		TypeInfo<int >::parseFromBinaryStream(&count, stream);
		return true;

	}

	return false;
}

void ScriptableImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ScriptableImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ScriptableImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0x51dc11b3; //Scriptable.count
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&count, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

bool ScriptableImplementation::isReady() {
	// probe/Scriptable.idl():  		return true;
	return true;
}

int ScriptableImplementation::getCount() {
	// probe/Scriptable.idl():  		return count;
	return count;
}

void ScriptableImplementation::setCount(int n) {
	// probe/Scriptable.idl():  		count = n;
	count = n;
}

void ScriptableImplementation::setName(const String& s) {
}

/*
 *	ScriptableAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


ScriptableAdapter::ScriptableAdapter(Scriptable* obj) : ManagedObjectAdapter(obj) {
}

void ScriptableAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	case RPC_ISREADY__:
		{
			
			bool _m_res = isReady();
			resp->insertBoolean(_m_res);
		}
		break;
	case RPC_GETCOUNT__:
		{
			
			int _m_res = getCount();
			resp->insertSignedInt(_m_res);
		}
		break;
	case RPC_SETCOUNT__INT_:
		{
			int n = inv->getSignedIntParameter();
			
			setCount(n);
			
		}
		break;
	case RPC_SETNAME__STRING_:
		{
			 String s; inv->getAsciiParameter(s);
			
			setName(s);
			
		}
		break;
	case RPC_ADDOBJECT__MANAGEDOBJECT_:
		{
			ManagedObject* obj = static_cast<ManagedObject*>(inv->getObjectParameter());
			
			addObject(obj);
			
		}
		break;
	case RPC_GETOWNER__:
		{
			
			DistributedObject* _m_res = getOwner();
			resp->insertLong(_m_res == NULL ? 0 : _m_res->_getObjectID());
		}
		break;
	default:
		ManagedObjectAdapter::invokeMethod(methid, inv);
	}
}

bool ScriptableAdapter::isReady() {
	return (static_cast<Scriptable*>(stub))->isReady();
}

int ScriptableAdapter::getCount() {
	return (static_cast<Scriptable*>(stub))->getCount();
}

void ScriptableAdapter::setCount(int n) {
	(static_cast<Scriptable*>(stub))->setCount(n);
}

void ScriptableAdapter::setName(const String& s) {
	(static_cast<Scriptable*>(stub))->setName(s);
}

void ScriptableAdapter::addObject(ManagedObject* obj) {
	(static_cast<Scriptable*>(stub))->addObject(obj);
}

ManagedObject* ScriptableAdapter::getOwner() {
	return (static_cast<Scriptable*>(stub))->getOwner();
}

/*
 *	ScriptableHelper
 */

ScriptableHelper* ScriptableHelper::staticInitializer = ScriptableHelper::instance();

ScriptableHelper::ScriptableHelper() {
	className = "Scriptable";

	Core::getObjectBroker()->registerClass(className, this);
}

void ScriptableHelper::finalizeHelper() {
	ScriptableHelper::finalize();
}

DistributedObject* ScriptableHelper::instantiateObject() {
	return new Scriptable(DummyConstructorParameter::instance());
}

DistributedObjectServant* ScriptableHelper::instantiateServant() {
	return new ScriptableImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* ScriptableHelper::instantiatePOD() {
	return new ScriptablePOD();
}

DistributedObjectAdapter* ScriptableHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new ScriptableAdapter(static_cast<Scriptable*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

const char LuaScriptable::className[] = "LuaScriptable";

Luna<LuaScriptable>::RegType LuaScriptable::Register[] = {
	{ "_setObject", &LuaScriptable::_setObject },
	{ "_getObject", &LuaScriptable::_getObject },
	{ "isReady", &LuaScriptable::isReady },
	{ "getCount", &LuaScriptable::getCount },
	{ "setCount", &LuaScriptable::setCount },
	{ "setName", &LuaScriptable::setName },
	{ "addObject", &LuaScriptable::addObject },
	{ "getOwner", &LuaScriptable::getOwner },
	{ 0, 0 }
};

LuaScriptable::LuaScriptable(lua_State *L) {
	realObject = static_cast<Scriptable*>(lua_touserdata(L, 1));
}

LuaScriptable::~LuaScriptable() {
}

int LuaScriptable::_setObject(lua_State* L) {
	realObject = static_cast<Scriptable*>(lua_touserdata(L, -1));

	return 0;
}

int LuaScriptable::_getObject(lua_State* L) {
	lua_pushlightuserdata(L, realObject.get());

	return 1;
}

int LuaScriptable::isReady(lua_State *L) {
	int parameterCount = lua_gettop(L) - 1;
	
	if (parameterCount == 0) {
		bool result = realObject->isReady();

		lua_pushboolean(L, result);
		return 1;
	} else {
		throw LuaCallbackException(L, "invalid argument count " + String::valueOf(parameterCount) + " for lua method 'Scriptable:isReady()'");
	}
	return 0;
}

int LuaScriptable::getCount(lua_State *L) {
	int parameterCount = lua_gettop(L) - 1;
	
	if (parameterCount == 0) {
		int result = realObject->getCount();

		lua_pushinteger(L, result);
		return 1;
	} else {
		throw LuaCallbackException(L, "invalid argument count " + String::valueOf(parameterCount) + " for lua method 'Scriptable:getCount()'");
	}
	return 0;
}

int LuaScriptable::setCount(lua_State *L) {
	int parameterCount = lua_gettop(L) - 1;
	
	if (lua_isnumber(L, -1)) {
		if (parameterCount == 1) {
			int n = lua_tointeger(L, -1);

			realObject->setCount(n);

			return 0;
		} else {
			throw LuaCallbackException(L, "invalid argument count " + String::valueOf(parameterCount) + " for lua method 'Scriptable:setCount(integer)'");
		}
	} else {
		throw LuaCallbackException(L, "invalid argument at 0 for lua method 'Scriptable:setCount(integer)'");
	}
	return 0;
}

int LuaScriptable::setName(lua_State *L) {
	int parameterCount = lua_gettop(L) - 1;
	
	if (lua_isstring(L, -1)) {
		if (parameterCount == 1) {
			const String s = lua_tostring(L, -1);

			realObject->setName(s);

			return 0;
		} else {
			throw LuaCallbackException(L, "invalid argument count " + String::valueOf(parameterCount) + " for lua method 'Scriptable:setName(string)'");
		}
	} else {
		throw LuaCallbackException(L, "invalid argument at 0 for lua method 'Scriptable:setName(string)'");
	}
	return 0;
}

int LuaScriptable::addObject(lua_State *L) {
	int parameterCount = lua_gettop(L) - 1;
	
	if (lua_isuserdata(L, -1)) {
		if (parameterCount == 1) {
			ManagedObject* obj = static_cast<ManagedObject*>(lua_touserdata(L, -1));

			realObject->addObject(obj);

			return 0;
		} else {
			throw LuaCallbackException(L, "invalid argument count " + String::valueOf(parameterCount) + " for lua method 'Scriptable:addObject(userdata)'");
		}
	} else {
		throw LuaCallbackException(L, "invalid argument at 0 for lua method 'Scriptable:addObject(userdata)'");
	}
	return 0;
}

int LuaScriptable::getOwner(lua_State *L) {
	int parameterCount = lua_gettop(L) - 1;
	
	if (parameterCount == 0) {
		ManagedObject* result = realObject->getOwner();

		if (result != NULL)
			lua_pushlightuserdata(L, result);
		else
			lua_pushnil(L);
		return 1;
	} else {
		throw LuaCallbackException(L, "invalid argument count " + String::valueOf(parameterCount) + " for lua method 'Scriptable:getOwner()'");
	}
	return 0;
}

/*
 *	ScriptablePOD
 */

ScriptablePOD::~ScriptablePOD() {
}

ScriptablePOD::ScriptablePOD(void) {
	_className = "Scriptable";
}


void ScriptablePOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = ScriptablePOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int ScriptablePOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (count) {
	_nameHashCode = 0x51dc11b3; //Scriptable.count
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<int >::toBinaryStream(&count.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool ScriptablePOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x51dc11b3: //Scriptable.count
		{
			int _mncount;
			TypeInfo<int >::parseFromBinaryStream(&_mncount, stream);
			count = std::move(_mncount);
		}
		return true;

	}

	return false;
}

void ScriptablePOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(ScriptablePOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void ScriptablePOD::writeObjectCompact(ObjectOutputStream* stream) {
	ManagedObjectPOD::writeObjectCompact(stream);

	TypeInfo<int >::toBinaryStream(&count.value(), stream);


}

