/*
 *	autogen/probe/StaticField.cpp generated by engine3 IDL compiler 0.70
 */

#include "StaticField.h"

/*
 *	StaticFieldStub
 */

StaticField::StaticField(DummyConstructorParameter* param) : ManagedObject(param) {
	_setClassName("StaticField");
}

StaticField::~StaticField() {
}



DistributedObjectServant* StaticField::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* StaticField::_getImplementationForRead() const {
	return _impl;
}

void StaticField::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	StaticFieldImplementation
 */

StaticFieldImplementation::StaticFieldImplementation() : ManagedObjectImplementation() {
	_initializeImplementation();
}

StaticFieldImplementation::StaticFieldImplementation(DummyConstructorParameter* param) : ManagedObjectImplementation(param) {
	_initializeImplementation();
}


StaticFieldImplementation::~StaticFieldImplementation() {
}


void StaticFieldImplementation::finalize() {
}

void StaticFieldImplementation::_initializeImplementation() {
	_setClassHelper(StaticFieldHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void StaticFieldImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<StaticField*>(stub);
	ManagedObjectImplementation::_setStub(stub);
}

DistributedObjectStub* StaticFieldImplementation::_getStub() {
	return _this.get();
}

StaticFieldImplementation::operator const StaticField*() {
	return _this.get();
}

void StaticFieldImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void StaticFieldImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void StaticFieldImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void StaticFieldImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void StaticFieldImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void StaticFieldImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void StaticFieldImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void StaticFieldImplementation::_serializationHelperMethod() {
	ManagedObjectImplementation::_serializationHelperMethod();

	_setClassName("StaticField");

}

void StaticFieldImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(StaticFieldImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool StaticFieldImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void StaticFieldImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = StaticFieldImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int StaticFieldImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

/*
 *	StaticFieldAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


StaticFieldAdapter::StaticFieldAdapter(StaticField* obj) : ManagedObjectAdapter(obj) {
}

void StaticFieldAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	default:
		ManagedObjectAdapter::invokeMethod(methid, inv);
	}
}

/*
 *	StaticFieldHelper
 */

StaticFieldHelper* StaticFieldHelper::staticInitializer = StaticFieldHelper::instance();

StaticFieldHelper::StaticFieldHelper() {
	className = "StaticField";

	Core::getObjectBroker()->registerClass(className, this);
}

void StaticFieldHelper::finalizeHelper() {
	StaticFieldHelper::finalize();
}

DistributedObject* StaticFieldHelper::instantiateObject() {
	return new StaticField(DummyConstructorParameter::instance());
}

DistributedObjectServant* StaticFieldHelper::instantiateServant() {
	return new StaticFieldImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* StaticFieldHelper::instantiatePOD() {
	return new StaticFieldPOD();
}

DistributedObjectAdapter* StaticFieldHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new StaticFieldAdapter(static_cast<StaticField*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	StaticFieldPOD
 */

StaticFieldPOD::~StaticFieldPOD() {
}

StaticFieldPOD::StaticFieldPOD(void) {
	_className = "StaticField";
}


void StaticFieldPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = StaticFieldPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int StaticFieldPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

bool StaticFieldPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void StaticFieldPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(StaticFieldPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void StaticFieldPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ManagedObjectPOD::writeObjectCompact(stream);


}

