/*
 *	autogen/probe/StaticField.h generated by engine3 IDL compiler 0.70
 */

#ifndef STATICFIELD_H_
#define STATICFIELD_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "engine/core/ManagedObject.h"

namespace probe {

class StaticField : public ManagedObject {
public:
	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	StaticField(DummyConstructorParameter* param);

	virtual ~StaticField();

	friend class StaticFieldHelper;
};

} // namespace probe

using namespace probe;

namespace probe {

class StaticFieldImplementation : public ManagedObjectImplementation {
public:
	static int counter;

	unsigned static int total;

	static byte version;

	static float scale;

	static int reverseOrder;

	int regular;

	StaticFieldImplementation();
	StaticFieldImplementation(DummyConstructorParameter* param);

	WeakReference<StaticField*> _this;

	operator const StaticField*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~StaticFieldImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class StaticField;
};

class StaticFieldAdapter : public ManagedObjectAdapter {
public:
	StaticFieldAdapter(StaticField* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

};

class StaticFieldHelper : public DistributedObjectClassHelper, public Singleton<StaticFieldHelper> {
	static StaticFieldHelper* staticInitializer;

public:
	StaticFieldHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<StaticFieldHelper>;
};

} // namespace probe

using namespace probe;

namespace probe {

class StaticFieldPOD : public ManagedObjectPOD {
public:
	String _className;
	StaticFieldPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~StaticFieldPOD();

};

} // namespace probe

using namespace probe;

#endif /*STATICFIELDPOD_H_*/
