/*
 *	autogen/probe/SuperMethodBase.cpp generated by engine3 IDL compiler 0.70
 */

#include "SuperMethodBase.h"

/*
 *	SuperMethodBaseStub
 */

SuperMethodBase::SuperMethodBase(DummyConstructorParameter* param) : ManagedObject(param) {
	_setClassName("SuperMethodBase");
}

SuperMethodBase::~SuperMethodBase() {
}



void SuperMethodBase::parentVoidMethod() {
	SuperMethodBaseImplementation* _implementation = static_cast<SuperMethodBaseImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->parentVoidMethod();
	}
}

int SuperMethodBase::parentMethodWithArgs(int x, int y) {
	SuperMethodBaseImplementation* _implementation = static_cast<SuperMethodBaseImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		return _implementation->parentMethodWithArgs(x, y);
	}
}

ManagedObject* SuperMethodBase::parentReturningClass() {
	SuperMethodBaseImplementation* _implementation = static_cast<SuperMethodBaseImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		return _implementation->parentReturningClass();
	}
}

DistributedObjectServant* SuperMethodBase::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* SuperMethodBase::_getImplementationForRead() const {
	return _impl;
}

void SuperMethodBase::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	SuperMethodBaseImplementation
 */

SuperMethodBaseImplementation::SuperMethodBaseImplementation() : ManagedObjectImplementation() {
	_initializeImplementation();
}

SuperMethodBaseImplementation::SuperMethodBaseImplementation(DummyConstructorParameter* param) : ManagedObjectImplementation(param) {
	_initializeImplementation();
}


SuperMethodBaseImplementation::~SuperMethodBaseImplementation() {
}


void SuperMethodBaseImplementation::finalize() {
}

void SuperMethodBaseImplementation::_initializeImplementation() {
	_setClassHelper(SuperMethodBaseHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void SuperMethodBaseImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<SuperMethodBase*>(stub);
	ManagedObjectImplementation::_setStub(stub);
}

DistributedObjectStub* SuperMethodBaseImplementation::_getStub() {
	return _this.get();
}

SuperMethodBaseImplementation::operator const SuperMethodBase*() {
	return _this.get();
}

void SuperMethodBaseImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void SuperMethodBaseImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void SuperMethodBaseImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void SuperMethodBaseImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void SuperMethodBaseImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void SuperMethodBaseImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void SuperMethodBaseImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void SuperMethodBaseImplementation::_serializationHelperMethod() {
	ManagedObjectImplementation::_serializationHelperMethod();

	_setClassName("SuperMethodBase");

}

void SuperMethodBaseImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(SuperMethodBaseImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool SuperMethodBaseImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void SuperMethodBaseImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = SuperMethodBaseImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int SuperMethodBaseImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

/*
 *	SuperMethodBaseAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


SuperMethodBaseAdapter::SuperMethodBaseAdapter(SuperMethodBase* obj) : ManagedObjectAdapter(obj) {
}

void SuperMethodBaseAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	default:
		ManagedObjectAdapter::invokeMethod(methid, inv);
	}
}

/*
 *	SuperMethodBaseHelper
 */

SuperMethodBaseHelper* SuperMethodBaseHelper::staticInitializer = SuperMethodBaseHelper::instance();

SuperMethodBaseHelper::SuperMethodBaseHelper() {
	className = "SuperMethodBase";

	Core::getObjectBroker()->registerClass(className, this);
}

void SuperMethodBaseHelper::finalizeHelper() {
	SuperMethodBaseHelper::finalize();
}

DistributedObject* SuperMethodBaseHelper::instantiateObject() {
	return new SuperMethodBase(DummyConstructorParameter::instance());
}

DistributedObjectServant* SuperMethodBaseHelper::instantiateServant() {
	return new SuperMethodBaseImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* SuperMethodBaseHelper::instantiatePOD() {
	return new SuperMethodBasePOD();
}

DistributedObjectAdapter* SuperMethodBaseHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new SuperMethodBaseAdapter(static_cast<SuperMethodBase*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	SuperMethodBasePOD
 */

SuperMethodBasePOD::~SuperMethodBasePOD() {
}

SuperMethodBasePOD::SuperMethodBasePOD(void) {
	_className = "SuperMethodBase";
}


void SuperMethodBasePOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = SuperMethodBasePOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int SuperMethodBasePOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

bool SuperMethodBasePOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void SuperMethodBasePOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(SuperMethodBasePOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void SuperMethodBasePOD::writeObjectCompact(ObjectOutputStream* stream) {
	ManagedObjectPOD::writeObjectCompact(stream);


}

