/*
 *	autogen/probe/SuperMethod.h generated by engine3 IDL compiler 0.70
 */

#ifndef SUPERMETHOD_H_
#define SUPERMETHOD_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "engine/core/ManagedObject.h"

#include "probe/SuperMethodBase.h"

namespace probe {

class SuperMethod : public SuperMethodBase {
public:
	void callsVoidMethod();

	int callsMethodWithArgs(int a, int b);

	void chainAfterSuperMethod();

	void multipleSuperCallsInOneBody();

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	SuperMethod(DummyConstructorParameter* param);

	virtual ~SuperMethod();

	friend class SuperMethodHelper;
};

} // namespace probe

using namespace probe;

namespace probe {

class SuperMethodImplementation : public SuperMethodBaseImplementation {

public:
	SuperMethodImplementation();
	SuperMethodImplementation(DummyConstructorParameter* param);

	void callsVoidMethod();

	int callsMethodWithArgs(int a, int b);

	void chainAfterSuperMethod();

	void multipleSuperCallsInOneBody();

	WeakReference<SuperMethod*> _this;

	operator const SuperMethod*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~SuperMethodImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class SuperMethod;
};

class SuperMethodAdapter : public SuperMethodBaseAdapter {
public:
	SuperMethodAdapter(SuperMethod* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

};

class SuperMethodHelper : public DistributedObjectClassHelper, public Singleton<SuperMethodHelper> {
	static SuperMethodHelper* staticInitializer;

public:
	SuperMethodHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<SuperMethodHelper>;
};

} // namespace probe

using namespace probe;

namespace probe {

class SuperMethodPOD : public SuperMethodBasePOD {
public:

	SuperMethodPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~SuperMethodPOD();

};

} // namespace probe

using namespace probe;

#endif /*SUPERMETHODPOD_H_*/
