/*
 *	autogen/probe/SuperMethodBase.h generated by engine3 IDL compiler 0.70
 */

#ifndef SUPERMETHODBASE_H_
#define SUPERMETHODBASE_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "engine/core/ManagedObject.h"

namespace probe {

class SuperMethodBase : public ManagedObject {
public:
	void parentVoidMethod();

	int parentMethodWithArgs(int x, int y);

	ManagedObject* parentReturningClass();

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	SuperMethodBase(DummyConstructorParameter* param);

	virtual ~SuperMethodBase();

	friend class SuperMethodBaseHelper;
};

} // namespace probe

using namespace probe;

namespace probe {

class SuperMethodBaseImplementation : public ManagedObjectImplementation {

public:
	SuperMethodBaseImplementation();
	SuperMethodBaseImplementation(DummyConstructorParameter* param);

	void parentVoidMethod();

	int parentMethodWithArgs(int x, int y);

	ManagedObject* parentReturningClass();

	WeakReference<SuperMethodBase*> _this;

	operator const SuperMethodBase*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~SuperMethodBaseImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class SuperMethodBase;
};

class SuperMethodBaseAdapter : public ManagedObjectAdapter {
public:
	SuperMethodBaseAdapter(SuperMethodBase* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

};

class SuperMethodBaseHelper : public DistributedObjectClassHelper, public Singleton<SuperMethodBaseHelper> {
	static SuperMethodBaseHelper* staticInitializer;

public:
	SuperMethodBaseHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<SuperMethodBaseHelper>;
};

} // namespace probe

using namespace probe;

namespace probe {

class SuperMethodBasePOD : public ManagedObjectPOD {
public:

	SuperMethodBasePOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~SuperMethodBasePOD();

};

} // namespace probe

using namespace probe;

#endif /*SUPERMETHODBASEPOD_H_*/
