/*
 *	autogen/probe/SuperMethod.cpp generated by engine3 IDL compiler 0.70
 */

#include "SuperMethod.h"

/*
 *	SuperMethodStub
 */

SuperMethod::SuperMethod(DummyConstructorParameter* param) : SuperMethodBase(param) {
	_setClassName("SuperMethod");
}

SuperMethod::~SuperMethod() {
}



void SuperMethod::callsVoidMethod() {
	SuperMethodImplementation* _implementation = static_cast<SuperMethodImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->callsVoidMethod();
	}
}

int SuperMethod::callsMethodWithArgs(int a, int b) {
	SuperMethodImplementation* _implementation = static_cast<SuperMethodImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		return _implementation->callsMethodWithArgs(a, b);
	}
}

void SuperMethod::chainAfterSuperMethod() {
	SuperMethodImplementation* _implementation = static_cast<SuperMethodImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->chainAfterSuperMethod();
	}
}

void SuperMethod::multipleSuperCallsInOneBody() {
	SuperMethodImplementation* _implementation = static_cast<SuperMethodImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->multipleSuperCallsInOneBody();
	}
}

DistributedObjectServant* SuperMethod::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* SuperMethod::_getImplementationForRead() const {
	return _impl;
}

void SuperMethod::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	SuperMethodImplementation
 */

SuperMethodImplementation::SuperMethodImplementation() : SuperMethodBaseImplementation() {
	_initializeImplementation();
}

SuperMethodImplementation::SuperMethodImplementation(DummyConstructorParameter* param) : SuperMethodBaseImplementation(param) {
	_initializeImplementation();
}


SuperMethodImplementation::~SuperMethodImplementation() {
}


void SuperMethodImplementation::finalize() {
}

void SuperMethodImplementation::_initializeImplementation() {
	_setClassHelper(SuperMethodHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void SuperMethodImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<SuperMethod*>(stub);
	SuperMethodBaseImplementation::_setStub(stub);
}

DistributedObjectStub* SuperMethodImplementation::_getStub() {
	return _this.get();
}

SuperMethodImplementation::operator const SuperMethod*() {
	return _this.get();
}

void SuperMethodImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void SuperMethodImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void SuperMethodImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void SuperMethodImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void SuperMethodImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void SuperMethodImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void SuperMethodImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void SuperMethodImplementation::_serializationHelperMethod() {
	SuperMethodBaseImplementation::_serializationHelperMethod();

	_setClassName("SuperMethod");

}

void SuperMethodImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(SuperMethodImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool SuperMethodImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (SuperMethodBaseImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void SuperMethodImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = SuperMethodImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int SuperMethodImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = SuperMethodBaseImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

void SuperMethodImplementation::callsVoidMethod() {
	// probe/SuperMethod.idl():  		super.parentVoidMethod();
	SuperMethodBaseImplementation::parentVoidMethod();
}

int SuperMethodImplementation::callsMethodWithArgs(int a, int b) {
	// probe/SuperMethod.idl():  		return super.parentMethodWithArgs(a, b);
	return SuperMethodBaseImplementation::parentMethodWithArgs(a, b);
}

void SuperMethodImplementation::chainAfterSuperMethod() {
	// probe/SuperMethod.idl():  		super.parentReturningClass().updateForWrite();
	SuperMethodBaseImplementation::parentReturningClass()->updateForWrite();
}

void SuperMethodImplementation::multipleSuperCallsInOneBody() {
	// probe/SuperMethod.idl():  		super.parentVoidMethod();
	SuperMethodBaseImplementation::parentVoidMethod();
	// probe/SuperMethod.idl():  		super.parentMethodWithArgs(1, 2);
	SuperMethodBaseImplementation::parentMethodWithArgs(1, 2);
}

/*
 *	SuperMethodAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


SuperMethodAdapter::SuperMethodAdapter(SuperMethod* obj) : SuperMethodBaseAdapter(obj) {
}

void SuperMethodAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	default:
		SuperMethodBaseAdapter::invokeMethod(methid, inv);
	}
}

/*
 *	SuperMethodHelper
 */

SuperMethodHelper* SuperMethodHelper::staticInitializer = SuperMethodHelper::instance();

SuperMethodHelper::SuperMethodHelper() {
	className = "SuperMethod";

	Core::getObjectBroker()->registerClass(className, this);
}

void SuperMethodHelper::finalizeHelper() {
	SuperMethodHelper::finalize();
}

DistributedObject* SuperMethodHelper::instantiateObject() {
	return new SuperMethod(DummyConstructorParameter::instance());
}

DistributedObjectServant* SuperMethodHelper::instantiateServant() {
	return new SuperMethodImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* SuperMethodHelper::instantiatePOD() {
	return new SuperMethodPOD();
}

DistributedObjectAdapter* SuperMethodHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new SuperMethodAdapter(static_cast<SuperMethod*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	SuperMethodPOD
 */

SuperMethodPOD::~SuperMethodPOD() {
}

SuperMethodPOD::SuperMethodPOD(void) {
	_className = "SuperMethod";
}


void SuperMethodPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = SuperMethodPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int SuperMethodPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = SuperMethodBasePOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;

	return _count;
}

bool SuperMethodPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (SuperMethodBasePOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	}

	return false;
}

void SuperMethodPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(SuperMethodPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void SuperMethodPOD::writeObjectCompact(ObjectOutputStream* stream) {
	SuperMethodBasePOD::writeObjectCompact(stream);


}

