/*
 *	autogen/probe/WeakRef.cpp generated by engine3 IDL compiler 0.70
 */

#include "WeakRef.h"

/*
 *	WeakRefStub
 */

WeakRef::WeakRef(DummyConstructorParameter* param) : ManagedObject(param) {
	_setClassName("WeakRef");
}

WeakRef::~WeakRef() {
}



void WeakRef::methodAccess() {
	WeakRefImplementation* _implementation = static_cast<WeakRefImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->methodAccess();
	}
}

void WeakRef::clearAssignment() {
	WeakRefImplementation* _implementation = static_cast<WeakRefImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->clearAssignment();
	}
}

void WeakRef::boolCheck() {
	WeakRefImplementation* _implementation = static_cast<WeakRefImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->boolCheck();
	}
}

void WeakRef::copyToStrong() {
	WeakRefImplementation* _implementation = static_cast<WeakRefImplementation*>(_getImplementation());
	if (unlikely(_implementation == NULL)) {
		throw ObjectNotLocalException(this);

	} else {
		_implementation->copyToStrong();
	}
}

DistributedObjectServant* WeakRef::_getImplementation() {

	 if (!_updated) _updated = true;
	return _impl;
}

DistributedObjectServant* WeakRef::_getImplementationForRead() const {
	return _impl;
}

void WeakRef::_setImplementation(DistributedObjectServant* servant) {
	_impl = servant;
}

/*
 *	WeakRefImplementation
 */

WeakRefImplementation::WeakRefImplementation() : ManagedObjectImplementation() {
	_initializeImplementation();
}

WeakRefImplementation::WeakRefImplementation(DummyConstructorParameter* param) : ManagedObjectImplementation(param) {
	_initializeImplementation();
}


WeakRefImplementation::~WeakRefImplementation() {
}


void WeakRefImplementation::finalize() {
}

void WeakRefImplementation::_initializeImplementation() {
	_setClassHelper(WeakRefHelper::instance());

	_this = NULL;

	_serializationHelperMethod();
}

void WeakRefImplementation::_setStub(DistributedObjectStub* stub) {
	_this = static_cast<WeakRef*>(stub);
	ManagedObjectImplementation::_setStub(stub);
}

DistributedObjectStub* WeakRefImplementation::_getStub() {
	return _this.get();
}

WeakRefImplementation::operator const WeakRef*() {
	return _this.get();
}

void WeakRefImplementation::lock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->lock(doLock);
}

void WeakRefImplementation::lock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->lock(obj);
}

void WeakRefImplementation::rlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->rlock(doLock);
}

void WeakRefImplementation::wlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->wlock(doLock);
}

void WeakRefImplementation::wlock(ManagedObject* obj) {
	_this.getReferenceUnsafeStaticCast()->wlock(obj);
}

void WeakRefImplementation::unlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->unlock(doLock);
}

void WeakRefImplementation::runlock(bool doLock) {
	_this.getReferenceUnsafeStaticCast()->runlock(doLock);
}

void WeakRefImplementation::_serializationHelperMethod() {
	ManagedObjectImplementation::_serializationHelperMethod();

	_setClassName("WeakRef");

}

void WeakRefImplementation::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(WeakRefImplementation::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

	initializeTransientMembers();
}

bool WeakRefImplementation::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectImplementation::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x21457580: //WeakRef.weakField
		TypeInfo<ManagedWeakReference<ManagedObject* > >::parseFromBinaryStream(&weakField, stream);
		return true;

	}

	return false;
}

void WeakRefImplementation::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = WeakRefImplementation::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int WeakRefImplementation::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectImplementation::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	_nameHashCode = 0x21457580; //WeakRef.weakField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedWeakReference<ManagedObject* > >::toBinaryStream(&weakField, stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;


	return _count;
}

void WeakRefImplementation::methodAccess() {
	// probe/WeakRef.idl():  		weakField.updateForWrite();
	weakField.get()->updateForWrite();
}

void WeakRefImplementation::clearAssignment() {
	// probe/WeakRef.idl():  		weakField = null;
	weakField = NULL;
}

void WeakRefImplementation::boolCheck() {
	// probe/WeakRef.idl():  	}
	if (weakField)	// probe/WeakRef.idl():  			weakField.lock();
	weakField.get()->lock();
}

void WeakRefImplementation::copyToStrong() {
	// probe/WeakRef.idl():  		ManagedObject strong = weakField;
	ManagedReference<ManagedObject* > strong = weakField;
	// probe/WeakRef.idl():  		strong.updateForWrite();
	strong->updateForWrite();
}

/*
 *	WeakRefAdapter
 */


#include "engine/orb/messages/InvokeMethodMessage.h"


WeakRefAdapter::WeakRefAdapter(WeakRef* obj) : ManagedObjectAdapter(obj) {
}

void WeakRefAdapter::invokeMethod(uint32 methid, DistributedMethod* inv) {
	DOBMessage* resp = inv->getInvocationMessage();

	switch (methid) {
	default:
		ManagedObjectAdapter::invokeMethod(methid, inv);
	}
}

/*
 *	WeakRefHelper
 */

WeakRefHelper* WeakRefHelper::staticInitializer = WeakRefHelper::instance();

WeakRefHelper::WeakRefHelper() {
	className = "WeakRef";

	Core::getObjectBroker()->registerClass(className, this);
}

void WeakRefHelper::finalizeHelper() {
	WeakRefHelper::finalize();
}

DistributedObject* WeakRefHelper::instantiateObject() {
	return new WeakRef(DummyConstructorParameter::instance());
}

DistributedObjectServant* WeakRefHelper::instantiateServant() {
	return new WeakRefImplementation(DummyConstructorParameter::instance());
}

DistributedObjectPOD* WeakRefHelper::instantiatePOD() {
	return new WeakRefPOD();
}

DistributedObjectAdapter* WeakRefHelper::createAdapter(DistributedObjectStub* obj) {
	DistributedObjectAdapter* adapter = new WeakRefAdapter(static_cast<WeakRef*>(obj));

	obj->_setClassName(className);
	obj->_setClassHelper(this);

	adapter->setStub(obj);

	return adapter;
}

/*
 *	WeakRefPOD
 */

WeakRefPOD::~WeakRefPOD() {
}

WeakRefPOD::WeakRefPOD(void) {
	_className = "WeakRef";
}


void WeakRefPOD::writeObject(ObjectOutputStream* stream) {
	int _currentOffset = stream->getOffset();
	stream->writeShort(0);
	int _varCount = WeakRefPOD::writeObjectMembers(stream);
	stream->writeShort(_currentOffset, _varCount);
}

int WeakRefPOD::writeObjectMembers(ObjectOutputStream* stream) {
	int _count = ManagedObjectPOD::writeObjectMembers(stream);

	uint32 _nameHashCode;
	int _offset;
	uint32 _totalSize;
	if (weakField) {
	_nameHashCode = 0x21457580; //WeakRef.weakField
	TypeInfo<uint32>::toBinaryStream(&_nameHashCode, stream);
	_offset = stream->getOffset();
	stream->writeInt(0);
	TypeInfo<ManagedWeakReference<ManagedObjectPOD* > >::toBinaryStream(&weakField.value(), stream);
	_totalSize = (uint32) (stream->getOffset() - (_offset + 4));
	stream->writeInt(_offset, _totalSize);
	_count++;
	}


	return _count;
}

bool WeakRefPOD::readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode) {
	if (ManagedObjectPOD::readObjectMember(stream, nameHashCode))
		return true;

	switch(nameHashCode) {
	case 0x21457580: //WeakRef.weakField
		{
			ManagedWeakReference<ManagedObjectPOD* > _mnweakField;
			TypeInfo<ManagedWeakReference<ManagedObjectPOD* > >::parseFromBinaryStream(&_mnweakField, stream);
			weakField = std::move(_mnweakField);
		}
		return true;

	}

	return false;
}

void WeakRefPOD::readObject(ObjectInputStream* stream) {
	uint16 _varCount = stream->readShort();
	for (int i = 0; i < _varCount; ++i) {
		uint32 _nameHashCode;
		TypeInfo<uint32>::parseFromBinaryStream(&_nameHashCode, stream);

		uint32 _varSize = stream->readInt();

		int _currentOffset = stream->getOffset();

		if(WeakRefPOD::readObjectMember(stream, _nameHashCode)) {
		}

		stream->setOffset(_currentOffset + _varSize);
	}

}

void WeakRefPOD::writeObjectCompact(ObjectOutputStream* stream) {
	ManagedObjectPOD::writeObjectCompact(stream);

	TypeInfo<ManagedWeakReference<ManagedObjectPOD* > >::toBinaryStream(&weakField.value(), stream);


}

