/*
 *	autogen/probe/WeakRef.h generated by engine3 IDL compiler 0.70
 */

#ifndef WEAKREF_H_
#define WEAKREF_H_

#include "engine/core/Core.h"

#include "engine/core/ManagedReference.h"

#include "engine/core/ManagedWeakReference.h"

#include "system/util/Optional.h"

#ifndef likely
#ifdef __GNUC__
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
#else
#define likely(x)       (x)
#define unlikely(x)     (x)
#endif
#endif
#include "engine/util/json_utils.h"

#include "engine/core/ManagedObject.h"

namespace probe {

class WeakRef : public ManagedObject {
public:
	void methodAccess();

	void clearAssignment();

	void boolCheck();

	void copyToStrong();

	DistributedObjectServant* _getImplementation();
	DistributedObjectServant* _getImplementationForRead() const;

	void _setImplementation(DistributedObjectServant* servant);

protected:
	WeakRef(DummyConstructorParameter* param);

	virtual ~WeakRef();

	friend class WeakRefHelper;
};

} // namespace probe

using namespace probe;

namespace probe {

class WeakRefImplementation : public ManagedObjectImplementation {
	ManagedWeakReference<ManagedObject* > weakField;

public:
	WeakRefImplementation();
	WeakRefImplementation(DummyConstructorParameter* param);

	void methodAccess();

	void clearAssignment();

	void boolCheck();

	void copyToStrong();

	WeakReference<WeakRef*> _this;

	operator const WeakRef*();

	DistributedObjectStub* _getStub();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
protected:
	virtual ~WeakRefImplementation();

	void finalize();

	void _initializeImplementation();

	void _setStub(DistributedObjectStub* stub);

	void lock(bool doLock = true);

	void lock(ManagedObject* obj);

	void rlock(bool doLock = true);

	void wlock(bool doLock = true);

	void wlock(ManagedObject* obj);

	void unlock(bool doLock = true);

	void runlock(bool doLock = true);

	void _serializationHelperMethod();
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);

	friend class WeakRef;
};

class WeakRefAdapter : public ManagedObjectAdapter {
public:
	WeakRefAdapter(WeakRef* impl);

	void invokeMethod(sys::uint32 methid, DistributedMethod* method);

};

class WeakRefHelper : public DistributedObjectClassHelper, public Singleton<WeakRefHelper> {
	static WeakRefHelper* staticInitializer;

public:
	WeakRefHelper();

	void finalizeHelper();

	DistributedObject* instantiateObject();

	DistributedObjectPOD* instantiatePOD();

	DistributedObjectServant* instantiateServant();

	DistributedObjectAdapter* createAdapter(DistributedObjectStub* obj);

	friend class Singleton<WeakRefHelper>;
};

} // namespace probe

using namespace probe;

namespace probe {

class WeakRefPOD : public ManagedObjectPOD {
public:
	Optional<ManagedWeakReference<ManagedObjectPOD* >> weakField;

	String _className;
	WeakRefPOD();
	virtual void readObject(ObjectInputStream* stream);
	virtual void writeObject(ObjectOutputStream* stream);
	bool readObjectMember(ObjectInputStream* stream, const uint32& nameHashCode);
	int writeObjectMembers(ObjectOutputStream* stream);
	void writeObjectCompact(ObjectOutputStream* stream);



	virtual ~WeakRefPOD();

};

} // namespace probe

using namespace probe;

#endif /*WEAKREFPOD_H_*/
