#!/usr/bin/env bash
# Populate testdata/idl/ and testdata/autogen/ from Core3.
#
# The corpus is .gitignored — Core3 sources are licensed and can't be
# redistributed as part of idlc-go, so each contributor / CI run
# repopulates locally.
#
# What this does, per corpus entry:
#   1. Copy <Class>.idl from Core3 src → testdata/idl/<Class>.idl
#   2. Run the JAR over it (with `-sd <core3_src> -cp <engine3_src>`)
#   3. Copy the generated .h/.cpp → testdata/autogen/<pkg>/
#
# The JAR runs from inside Core3's source tree because the corpus IDLs
# reference sibling classes (ZoneServer, CreatureObject, etc.) that
# live there. Output goes to a temp dir under <core3_src>/_idlc_go_out/
# and is cleaned up at the end.
#
# Override: `CORE3_PATH=/abs/path bash scripts/fetch-corpus-from-core3.sh`.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CORE3_PATH="${CORE3_PATH:-${REPO_ROOT}/submodules/Core3}"
CORE3_SRC="${CORE3_PATH}/MMOCoreORB/src"
ENGINE3_SRC="${CORE3_PATH}/MMOCoreORB/utils/engine3/MMOEngine/src"
JAR="${CORE3_PATH}/MMOCoreORB/utils/engine3/MMOEngine/lib/idlc.jar"

if [[ ! -d "${CORE3_SRC}" ]]; then
	echo "missing Core3 source: ${CORE3_SRC}" >&2
	echo "Clone SWGEmu/Core3 to ./submodules/Core3 or set CORE3_PATH=/abs/path." >&2
	exit 1
fi
if [[ ! -f "${JAR}" ]]; then
	echo "missing JAR: ${JAR}" >&2
	echo "(Core3's engine3 submodule may not be initialised — re-clone with --recursive.)" >&2
	exit 1
fi

# CORPUS lists "<src-tree>:<rel-pkg-path>:<class>" entries.
# <src-tree> is e3 (engine3) or c3 (Core3).
CORPUS=(
	"e3:engine/core:ManagedObject"
	"e3:engine/core:ManagedService"
	"e3:engine/core/util:ManagedVector"
	"e3:engine/util:Facade"
	"e3:engine/util:Observable"
	"e3:engine/util:Observer"
	"e3:testsuite3/tests:TestIDLClass"
	"e3:testsuite3/tests:TestNoOrbClass"
	"c3:server/chat:ChatMessage"
	"c3:server/chat:PendingMessageList"
	"c3:server/chat:PersistentMessage"
	"c3:server/chat:ChatManager"
	"c3:server/chat/room:ChatRoom"
	"c3:server/zone:Zone"
	"c3:server/zone:GroundZone"
	"c3:server/zone:SpaceZone"
	"c3:server/zone:TreeEntry"
	"c3:server/zone:ZoneClientSession"
	"c3:server/zone:ZoneProcessServer"
	"c3:server/zone:ZoneServer"
	"c3:server/utils:LambdaObserver"
)

# `OD_REL=autogen` matches Core3's CMake invocation. The JAR embeds
# this string verbatim in the file-header comment of every generated
# file (`autogen/<pkg>/Foo.h generated by engine3 IDL compiler 0.70`).
# Picking anything else means our regenerated goldens won't match the
# original ones byte-for-byte.
OD_REL="autogen"
trap 'rm -rf "${CORE3_SRC}/${OD_REL}" "${ENGINE3_SRC}/${OD_REL}" 2>/dev/null || true' EXIT

mkdir -p "${REPO_ROOT}/testdata/idl"
mkdir -p "${REPO_ROOT}/testdata/autogen"
mkdir -p "${REPO_ROOT}/testdata/mock"

count=0
for entry in "${CORPUS[@]}"; do
	tree="${entry%%:*}"
	rest="${entry#*:}"
	pkg="${rest%:*}"
	class="${rest##*:}"

	case "${tree}" in
		e3) src_root="${ENGINE3_SRC}" ;;
		c3) src_root="${CORE3_SRC}" ;;
		*)  echo "unknown tree marker '${tree}'" >&2; exit 2 ;;
	esac

	idl_src="${src_root}/${pkg}/${class}.idl"
	if [[ ! -f "${idl_src}" ]]; then
		echo "  missing IDL: ${idl_src}" >&2
		continue
	fi

	cp "${idl_src}" "${REPO_ROOT}/testdata/idl/${class}.idl"

	rm -rf "${src_root}/${OD_REL}"
	java -cp "${JAR}" org.sr.idlc.compiler.Compiler \
		-cp "${ENGINE3_SRC}" \
		-sd "${src_root}" \
		-od "${OD_REL}" \
		-silence -rbcpp "${pkg}/${class}.idl" >/dev/null

	gen_h="${src_root}/${OD_REL}/${pkg}/${class}.h"
	gen_cpp="${src_root}/${OD_REL}/${pkg}/${class}.cpp"
	if [[ ! -f "${gen_h}" || ! -f "${gen_cpp}" ]]; then
		echo "  no autogen for ${class} (looked in ${gen_h})" >&2
		continue
	fi

	mkdir -p "${REPO_ROOT}/testdata/autogen/${pkg}"
	cp "${gen_h}" "${REPO_ROOT}/testdata/autogen/${pkg}/${class}.h"
	cp "${gen_cpp}" "${REPO_ROOT}/testdata/autogen/${pkg}/${class}.cpp"

	# If the JAR emitted a `MockX` class block (because the IDL has
	# `@mock`), extract the MOCK_METHOD lines into testdata/mock/X.mock.
	# The .mock fixture format is: every `\tMOCK_METHOD…(…);` line from
	# the MockX block, terminated by a trailing blank line (the JAR's
	# `};` close needs a separator before it — see the GroundZone-mock
	# trailing-blank-line quirk).
	if grep -q "^class Mock${class} :" "${gen_h}"; then
		awk -v cls="Mock${class}" '
			$0 ~ "^class " cls " :" { in_mock = 1; next }
			in_mock && /^\};/ { in_mock = 0; exit }
			in_mock && /MOCK_METHOD/ { print }
		' "${gen_h}" > "${REPO_ROOT}/testdata/mock/${class}.mock"
		printf "\n" >> "${REPO_ROOT}/testdata/mock/${class}.mock"
	fi

	count=$((count + 1))
done

echo "[corpus] populated ${count} IDLs + autogen from Core3 into testdata/"
echo "[corpus] mock fixtures extracted from JAR autogen for any @mock classes"
